from __future__ import annotations

"""
AdCP Python Client Library

Official Python client for the Ad Context Protocol (AdCP).
Supports both A2A and MCP protocols with full type safety.

``import adcp`` is lightweight: the generated Pydantic schema graph and the
client / server / protocol stack are imported lazily, the first time a name
that needs them is accessed. ``from adcp import Product`` builds the type
graph; ``from adcp import ADCPError`` does not. Names resolve through the
module-level ``__getattr__`` (PEP 562); type checkers see the full surface
via the ``TYPE_CHECKING`` block at the bottom of this module.
"""

import importlib
import importlib.util
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    # ``__version__`` is resolved lazily at runtime (see ``_resolve_version``)
    # so ``import adcp`` doesn't pay the ~15ms ``importlib.metadata`` cost.
    __version__: str

# Cache for the resolved SDK version. NOT named ``_version`` — that would
# collide with the ``adcp._version`` submodule, which clobbers the cache the
# moment anything imports it.
_sdk_version: str | None = None


def _resolve_version() -> str:
    """Return the installed SDK version, resolved once and cached.

    Deferred out of module import: ``importlib.metadata`` pulls in a sizable
    stdlib subtree (~15ms), and most importers never read ``__version__``.
    """
    global _sdk_version
    if _sdk_version is None:
        from importlib.metadata import PackageNotFoundError
        from importlib.metadata import version as _pkg_version

        try:
            _sdk_version = _pkg_version("adcp")
        except PackageNotFoundError:
            # Running from a source tree without an installed distribution.
            _sdk_version = "0.0.0+unknown"
    return _sdk_version


# Types removed in 4.0 — raise an informative ImportError instead of the
# default "cannot import name" traceback, and point at the specific
# section in the migration guide so the reader doesn't have to ctrl-F.
# Each tuple is ``(replacement hint, migration-guide anchor fragment)``.
# Keep anchors in sync with MIGRATION_v3_to_v4.md headings.
_REMOVED_IN_V4: dict[str, tuple[str, str]] = {
    "BrandManifest": (
        "use `BrandReference(domain=...)` on requests; "
        "read `ResolvedBrand.brand` from the registry",
        "brandmanifest--brandreference",
    ),
    "FormatCategory": (
        "removed without replacement — format metadata carries category info",
        "formatcategory--removed",
    ),
    "DeliverTo": (
        "use `publisher_properties` on the request instead",
        "deliverto--publisher_properties",
    ),
    "PromotedProducts": (
        "use the spec-current `offerings` shape",
        "promotedproducts--promotedofferings--offerings",
    ),
    "PromotedOfferings": (
        "use the spec-current `offerings` shape",
        "promotedproducts--promotedofferings--offerings",
    ),
    "Pricing": (
        "use the discriminated pricing classes (e.g. `CpmFixedRatePricingOption`)",
        "pricing--discriminated-pricingoption",
    ),
    "PackageStatus": (
        "package status moved onto `MediaBuyStatus`",
        "packagestatus--mediabuystatus",
    ),
}


# Lazy re-export map: owning module -> the public names it provides. These
# used to be eager ``from <module> import (...)`` blocks at module top.
# ``__getattr__`` imports the owning module on first access to any of its
# names and caches the result. Grouped by module (and mirrored verbatim in the
# ``TYPE_CHECKING`` block at the bottom) so it stays readable and auditable.
_LAZY_MODULES: dict[str, tuple[str, ...]] = {
    "adcp.acceptance": (
        "AcceptancePolicyAssessment",
        "AcceptancePolicyDiagnostic",
        "AcceptancePolicyDiagnosticCode",
        "AcceptancePolicyOutcome",
        "AcceptancePolicyRegistry",
        "AcceptancePolicyResolution",
        "AcceptancePolicyResolver",
        "AcceptancePolicySurface",
        "DEFAULT_ACCEPTANCE_CATALOG_CACHE_ENTRIES",
        "DEFAULT_ACCEPTANCE_CATALOG_MAX_BYTES",
        "DEFAULT_ACCEPTANCE_CATALOG_TIMEOUT_SECONDS",
    ),
    "adcp.media_buy_actions": (
        "ActionAvailabilityStatus",
        "ActionDiagnostic",
        "ActionDiagnosticCode",
        "ActionDispatchClient",
        "ActionIntent",
        "ActionKnowledge",
        "ActionTask",
        "ChangeTermSelection",
        "ConstraintCheck",
        "ConstraintOutcome",
        "MediaBuyActionAssessment",
        "MediaBuyActionError",
        "MediaBuyActionProjection",
        "ProjectedMediaBuyAction",
        "assess_media_buy_action",
        "assess_update_media_buy_actions",
        "dispatch_media_buy_action",
        "evaluate_action_constraints",
        "materialize_change_terms",
        "project_available_actions",
        "reassess_media_buy_action",
        "route_media_buy_action",
    ),
    "adcp.adagents": (
        "AdagentsCacheEntry",
        "AdagentsEntryError",
        "AdagentsFetchResult",
        "AdagentsValidationReport",
        "AdAgentsValidationResult",
        "AgentAuthorizationsDirectoryResult",
        "AuthorizationContext",
        "DirectoryDiscoveryMethod",
        "DirectoryEdgeStatus",
        "DirectoryPublisherEntry",
        "DiscoveryMethod",
        "DivergenceReport",
        "EntryErrorKind",
        "PublisherDivergence",
        "detect_publisher_properties_divergence",
        "domain_matches",
        "fetch_adagents",
        "fetch_adagents_with_cache",
        "fetch_agent_authorizations",
        "fetch_agent_authorizations_from_directory",
        "filter_revoked_selectors",
        "get_all_properties",
        "get_all_tags",
        "get_properties_by_agent",
        "identifiers_match",
        "resolve_properties_for_agent",
        "validate_adagents_domain",
        "validate_adagents_structure",
        "verify_agent_authorization",
        "verify_agent_for_property",
    ),
    "adcp.canonical_formats": (
        "format_is_supported",
        "formats_are_equivalent",
        "upgrade_legacy_format_id",
    ),
    "adcp.capabilities": (
        "FeatureResolver",
        "build_synthetic_capabilities",
        "looks_like_v3_capabilities",
        "validate_capabilities",
    ),
    "adcp.client": (
        "ADCPClient",
        "ADCPMultiAgentClient",
        "Checkpoint",
    ),
    "adcp.task_options": (
        "TaskOptions",
        "TaskRecoveryMetadata",
    ),
    "adcp.observability": (
        "get_tracer",
        "inject_trace_headers",
        "is_tracing_available",
    ),
    "adcp.oauth": (
        "InMemoryPendingOAuthFlowStore",
        "OAuthAuthorizationError",
        "OAuthAuthorizationRequest",
        "OAuthAuthorizationServerMetadata",
        "OAuthClientError",
        "OAuthDiscoveryError",
        "OAuthFlowStoreError",
        "OAuthIssuerBinding",
        "OAuthTokenExchangeError",
        "OAuthTokenSet",
        "PendingOAuthAuthorization",
        "PendingOAuthFlowStore",
        "complete_oauth_authorization",
        "discover_oauth_metadata",
        "start_oauth_authorization",
    ),
    "adcp.exceptions": (
        "AdagentsAccessBlockedError",
        "AdagentsNotFoundError",
        "AdagentsTimeoutError",
        "AdagentsValidationError",
        "ADCPAuthenticationError",
        "ADCPConnectionError",
        "ADCPError",
        "ADCPFeatureUnsupportedError",
        "ADCPProtocolError",
        "ADCPSigningRequiredError",
        "ADCPTaskError",
        "ADCPTimeoutError",
        "ADCPToolNotFoundError",
        "ADCPWebhookError",
        "ADCPWebhookSignatureError",
        "ConfigurationError",
        "IdempotencyConflictError",
        "IdempotencyExpiredError",
        "IdempotencyScopeError",
        "IdempotencyUnsupportedError",
        "RegistryError",
        "RegistryErrorDetails",
        "RegistryValidationIssue",
    ),
    "adcp.feed_mirror": (
        "EventHandler",
        "FeedMirror",
        "FeedMirrorClient",
        "FeedMirrorError",
        "FeedState",
        "FeedStateStore",
        "RefreshResult",
    ),
    "adcp.property_registry": ("PropertyRegistry",),
    "adcp.registry": ("RegistryClient",),
    "adcp.registry_sync": (
        "ChangeHandler",
        "CursorStore",
        "FileCursorStore",
        "RegistrySync",
    ),
    "adcp.substitution": (
        "MacroMapping",
        "MacroMappingEntry",
        "NativeMacroMapping",
        "TranslateUniversalMacrosResult",
        "UniversalMacroTranslationError",
        "UniversalMacroTranslationErrorCode",
        "ValueMacroMapping",
        "encode_unreserved",
        "translate_universal_macros",
    ),
    "adcp.testing": (
        "CREATIVE_AGENT_CONFIG",
        "TEST_AGENT_A2A_CONFIG",
        "TEST_AGENT_A2A_NO_AUTH_CONFIG",
        "TEST_AGENT_MCP_CONFIG",
        "TEST_AGENT_MCP_NO_AUTH_CONFIG",
        "TEST_AGENT_TOKEN",
        "create_test_agent",
        "creative_agent",
        "test_agent",
        "test_agent_a2a",
        "test_agent_a2a_no_auth",
        "test_agent_client",
        "test_agent_no_auth",
    ),
    "adcp.types": (
        "AcceptProposalRequest",
        "AcceptProposalResponse",
        "AcceptedLoss",
        "AcceptanceContext",
        "AcceptancePolicyCatalog",
        "AcceptancePolicyDiscovery",
        "AcceptancePolicyProfile",
        "AcceptancePolicyProfileId",
        "AcceptancePolicyProfileIds",
        "AcceptancePolicyRequirement",
        "AcceptancePolicyRule",
        "CanonicalMediaBuyAction",
        "CanonicalMediaBuyActionMode",
        "CanonicalMediaBuyActionName",
        "CanonicalProductAction",
        "CommercialTerms",
        "MediaBuyAvailableAction",
        "MediaBuyActionMode",
        "MediaBuyChangeTerm",
        "MediaBuyChangeTermConstraints",
        "MediaBuyChangeTermId",
        "MediaBuyValidAction",
        "BudgetChangeConstraints",
        "EffectiveTimingChangeConstraints",
        "FlightChangeConstraints",
        "PackageCountChangeConstraints",
        "ProductAllowedAction",
        "RegistryAcceptancePolicyProfileReference",
        "BuyProductsRequest",
        "BuyProductsResponse",
        "ControlMediaBuyRequest",
        "ControlMediaBuyResponse",
        "CompatibilityPurchaseCoordinatorInput",
        "DeclineProposalsRequest",
        "DeclineProposalsResponse",
        "ListProductsRequest",
        "ListProductsResponse",
        "RefineProposalsRequest",
        "RefineProposalsResponse",
        "RequestProposalsRequest",
        "RequestProposalsResponse",
        "ReportPlanAdjustmentRequest",
        "ReportPlanAdjustmentResponse",
        "SyncAgentNotificationConfigsRequest",
        "SyncAgentNotificationConfigsResponse",
        "AccountAuthorization",
        "AccountReference",
        "AccountScope",
        "AccountWithAuthorization",
        "AcquireRightsRequest",
        "AcquireRightsResponse",
        "ActivateSignalRequest",
        "ActivateSignalResponse",
        "AdvertiserIndustry",
        "ArtifactWebhookPayload",
        "AssetContentType",
        "AssetInstance",
        "AssetInstanceType",
        "AssetVariant",
        "AudioContent",
        "AudienceSource",
        "CssContent",
        "DaastAsset",
        "HtmlContent",
        "ImageContent",
        "JavascriptContent",
        "MarkdownAsset",
        "TextContent",
        "UrlContent",
        "VastAsset",
        "VideoContent",
        "WebhookContent",
        "AuthorizationRequiredDetails",
        "BrandIdentity",
        "BrandReference",
        "BrandSource",
        "BriefAsset",
        "BuyingMode",
        "CardAsset",
        "Catalog",
        "CatalogAction",
        "CatalogAsset",
        "CatalogFieldBinding",
        "CatalogFieldMapping",
        "CatalogGroupBinding",
        "CatalogItemStatus",
        "CatalogRequirements",
        "CatalogType",
        "CheckGovernanceRequest",
        "CheckGovernanceResponse",
        "ComplyTestControllerRequest",
        "ComplyTestControllerResponse",
        "ConsentBasis",
        "ContentIdType",
        "ContextMatchRequest",
        "ContextMatchResponse",
        "ContextObject",
        "CpaPricingOption",
        "CpcPricingOption",
        "CpcvPricingOption",
        "CpmAuctionPricingOption",
        "CpmFixedRatePricingOption",
        "CpmPricingOption",
        "CppPricingOption",
        "CpvPricingOption",
        "CreateMediaBuyRequest",
        "CreateMediaBuyResponse",
        "CreateMediaBuyResponse1",
        "CreateMediaBuySubmittedResponse",
        "CreateMediaBuySuccessResponse",
        "CreateMediaBuyErrorResponse",
        "Creative",
        "CreativeApproval",
        "CreativeApprovalStatus",
        "CreativeFilters",
        "CreativeManifest",
        "CreativeStatus",
        "CreativeVariant",
        "DateRange",
        "DaastTrackerAsset",
        "DatetimeRange",
        "DeliveryStatus",
        "DevicePlatform",
        "DeviceType",
        "DownstreamConnectionRequirement",
        "Duration",
        "Error",
        "ErrorCode",
        "EventType",
        "ExtensionObject",
        "FeedFormat",
        "FlatRatePricingOption",
        "Format",
        "FormatOptionReference",
        "GeneratedTaskStatus",
        "GetAccountFinancialsRequest",
        "GetAccountFinancialsResponse",
        "GetBrandIdentityRequest",
        "GetBrandIdentityResponse",
        "GetCreativeDeliveryRequest",
        "GetCreativeDeliveryResponse",
        "GetCreativeFeaturesRequest",
        "GetCreativeFeaturesResponse",
        "GetMediaBuyDeliveryRequest",
        "GetMediaBuyDeliveryResponse",
        "GetMediaBuysRequest",
        "GetMediaBuysResponse",
        "GetPlanAuditLogsRequest",
        "GetPlanAuditLogsResponse",
        "GetProductsRequest",
        "GetProductsResponse",
        "GetRightsRequest",
        "GetRightsResponse",
        "GetSignalsRequest",
        "GetSignalsResponse",
        "GetTaskStatusRequest",
        "GetTaskStatusResponse",
        "Gtin",
        "IdentityMatchRequest",
        "IdentityMatchResponse",
        "IdentityMatchTmpxMacro",
        "KellerType",
        "LegacyCreateMediaBuyRequest",
        "LegacyBuildCreativeErrorResponse",
        "LegacyBuildCreativeRequest",
        "LegacyBuildCreativeResponse",
        "LegacyBuildCreativeResponse1",
        "LegacyBuildCreativeResponse2",
        "LegacyBuildCreativeResponse3",
        "LegacyBuildCreativeResponse4",
        "LegacyBuildCreativeResponse5",
        "LegacyBuildCreativeResponse6",
        "LegacyBuildCreativeSubmittedResponse",
        "LegacyBuildCreativeSuccessResponse",
        "LegacyCreativeAsset",
        "LegacyCreativeFilters",
        "LegacyFormat",
        "LegacyFormatId",
        "LegacyFormatReferenceStructuredObject",
        "LegacyGetCreativeDeliveryResponse",
        "LegacyGetMediaBuyDeliveryResponse",
        "LegacyGetMediaBuysResponse",
        "LegacyGetProductsRequest",
        "LegacyGetProductsResponse",
        "LegacyListCreativeFormatsRequest",
        "LegacyListCreativeFormatsResponse",
        "LegacyListCreativesRequest",
        "LegacyListCreativesResponse",
        "LegacyPackage",
        "LegacyPackageRequest",
        "LegacyPackageUpdate",
        "LegacyPlacement",
        "LegacyPreviewCreativeBatchResponse",
        "LegacyPreviewCreativeRequest",
        "LegacyPreviewCreativeResponse",
        "LegacyPreviewCreativeResponse1",
        "LegacyPreviewCreativeResponse2",
        "LegacyPreviewCreativeResponse3",
        "LegacyPreviewCreativeSingleResponse",
        "LegacyPreviewCreativeVariantResponse",
        "LegacyProduct",
        "LegacyProductFormatDeclaration",
        "LegacyProductFilters",
        "LegacySyncCreativesRequest",
        "LegacyUpdateMediaBuyRequest",
        "ListAccountsRequest",
        "ListAccountsResponse",
        "ListAccountChangesRequest",
        "ListAccountChangesResponse",
        "ListCreativesRequest",
        "ListCreativesResponse",
        "ListTasksRequest",
        "ListTasksResponse",
        "ListTransformersRequest",
        "ListTransformersResponse",
        "LogEventRequest",
        "LogEventResponse",
        "McpWebhookPayload",
        "MediaBuy",
        "MediaBuyDeliveryStatus",
        "MediaBuyDeliveryWebhookResult",
        "MediaBuyPackage",
        "MediaBuyStatus",
        "MediaChannel",
        "NotificationConfig",
        "OfferingAssetConstraint",
        "OfferingAssetGroup",
        "OptimizationGoal",
        "Overlay",
        "Package",
        "PackageRequest",
        "PackageSignalTargeting",
        "PackageSignalTargetingGroup",
        "PackageSignalTargetingGroups",
        "PaginationRequest",
        "PixelTrackerAsset",
        "Placement",
        "PlacementPresentationDocument",
        "PlacementPresentationReference",
        "PlacementReference",
        "PreviewRendererMetadata",
        "PriceGuidance",
        "PricingCurrency",
        "PricingModel",
        "ProviderRegistrationTmpxMacro",
        "Product",
        "PublishedPostAsset",
        "PublisherDesignatedPreviewProvider",
        "ProductFormatDeclaration",
        "ProductFilters",
        "ProductSignalTargetingOption",
        "Property",
        "PropertyIdActivationKey",
        "PropertyTagActivationKey",
        "Proposal",
        "ProvidePerformanceFeedbackRequest",
        "ProvidePerformanceFeedbackResponse",
        "PushNotificationConfig",
        "Refine",
        "ReportPlanOutcomeRequest",
        "ReportPlanOutcomeResponse",
        "ReportUsageRequest",
        "ReportUsageResponse",
        "ResponsePayloadJwsEnvelope",
        "ReferenceRenderer",
        "SellerAgentReference",
        "SignalAvailabilityType",
        "SignalCatalogType",
        "SignalDefinitionEnrichment",
        "SignalFilters",
        "SignalListing",
        "SignalPricingOption",
        "SignalRef",
        "SignalTargeting",
        "SignalTargetingExpression",
        "SignalTargetingRules",
        "Snapshot",
        "SnapshotUnavailableReason",
        "SyncAccountsRequest",
        "SyncAccountsResponse",
        "SyncAudiencesRequest",
        "SyncAudiencesResponse",
        "SyncCatalogsInputRequired",
        "SyncCatalogsRequest",
        "SyncCatalogsResponse",
        "SyncCatalogsSubmitted",
        "SyncCatalogsWorking",
        "SyncCreativesRequest",
        "SyncCreativesResponse",
        "SyncEventSourcesRequest",
        "SyncEventSourcesResponse",
        "SyncPlansRequest",
        "SyncPlansResponse",
        "TargetingOverlay",
        "TimeBasedPricingOption",
        "TimeUnit",
        "Transform",
        "UpdateFrequency",
        "UpdateMediaBuyRequest",
        "UpdateMediaBuyResponse",
        "UpdateMediaBuyResponse1",
        "UpdateMediaBuyResponse3",
        "UpdateMediaBuySubmittedResponse",
        "UpdateMediaBuySuccessResponse",
        "UpdateMediaBuyErrorResponse",
        "ValidateInputRequest",
        "ValidateInputResponse",
        "VcpmAuctionPricingOption",
        "VcpmFixedRatePricingOption",
        "VcpmPricingOption",
        "VastTrackerAsset",
        "VerifyBrandClaimPayload",
        "VerifyBrandClaimRequest",
        "VerifyBrandClaimResponse",
        "VerifyBrandClaimsErrorResponse",
        "VerifyBrandClaimSignedResponse",
        "VerifyBrandClaimSignedSuccessPayload",
        "VerifyBrandClaimsPayload",
        "VerifyBrandClaimsRequest",
        "ZipAsset",
        "VerifyBrandClaimsRequestBulk",
        "VerifyBrandClaimsResponse",
        "VerifyBrandClaimsResponseBulk",
        "VerifyBrandClaimsSignedResponse",
        "VerifyBrandClaimsSignedSuccessPayload",
        "WcagLevel",
        "WebhookChallenge",
        "WebhookChallengeResponse",
        "WholesaleFeedEvent",
        "WholesaleFeedWebhook",
        "aliases",
        "generated",
    ),
    "adcp.types.aliases": (
        "AccountReferenceById",
        "AccountReferenceByNaturalKey",
        "AcquireRightsAcquiredResponse",
        "AcquireRightsErrorResponse",
        "AcquireRightsPendingResponse",
        "AcquireRightsRejectedResponse",
        "AcquireRightsResponse1",
        "ActivateSignalErrorResponse",
        "ActivateSignalResponse1",
        "ActivateSignalSuccessResponse",
        "AgentDeployment",
        "AgentDestination",
        "AuthorizedAgent",
        "AuthorizedAgentsByInlineProperties",
        "AuthorizedAgentsByPropertyId",
        "AuthorizedAgentsByPropertyTag",
        "AuthorizedAgentsByPublisherProperties",
        "AuthorizedAgentsBySignalId",
        "AuthorizedAgentsBySignalTag",
        "BothPreviewRender",
        "CalibrateContentErrorResponse",
        "CalibrateContentResponse1",
        "CalibrateContentSuccessResponse",
        "ComplyTestControllerResponse1",
        "CreateContentStandardsErrorResponse",
        "CreateContentStandardsResponse1",
        "CreateContentStandardsSuccessResponse",
        "Deployment",
        "Destination",
        "GetAccountFinancialsErrorResponse",
        "GetAccountFinancialsResponse1",
        "GetAccountFinancialsSuccessResponse",
        "GetBrandIdentityErrorResponse",
        "GetBrandIdentityResponse1",
        "GetBrandIdentitySuccessResponse",
        "GetContentStandardsErrorResponse",
        "GetContentStandardsResponse1",
        "GetContentStandardsSuccessResponse",
        "GetCreativeDeliveryByBuyerRefRequest",
        "GetCreativeDeliveryByCreativeRequest",
        "GetCreativeDeliveryByMediaBuyRequest",
        "GetCreativeFeaturesErrorResponse",
        "GetCreativeFeaturesResponse1",
        "GetCreativeFeaturesSuccessResponse",
        "GetMediaBuyArtifactsErrorResponse",
        "GetMediaBuyArtifactsResponse1",
        "GetMediaBuyArtifactsSuccessResponse",
        "GetProductsBriefRequest",
        "GetProductsRefineRequest",
        "GetProductsWholesaleRequest",
        "GetRightsErrorResponse",
        "GetRightsResponse1",
        "GetRightsSuccessResponse",
        "GetSignalsDiscoveryRequest",
        "GetSignalsLookupRequest",
        "HtmlPreviewRender",
        "InlineDaastAsset",
        "InlineVastAsset",
        "KeyValueActivationKey",
        "ListContentStandardsErrorResponse",
        "ListContentStandardsResponse1",
        "ListContentStandardsSuccessResponse",
        "LogEventErrorResponse",
        "LogEventResponse1",
        "LogEventSuccessResponse",
        "PlatformDeployment",
        "PlatformDestination",
        "PricingOption",
        "PropertyId",
        "PropertyTag",
        "ProvidePerformanceFeedbackByBuyerRefRequest",
        "ProvidePerformanceFeedbackByMediaBuyRequest",
        "ProvidePerformanceFeedbackErrorResponse",
        "ProvidePerformanceFeedbackResponse1",
        "ProvidePerformanceFeedbackSuccessResponse",
        "PublisherProperties",
        "PublisherPropertiesAll",
        "PublisherPropertiesById",
        "PublisherPropertiesByTag",
        "SegmentIdActivationKey",
        "SiSendActionResponseRequest",
        "SiSendTextMessageRequest",
        "SyncAccountsErrorResponse",
        "SyncAccountsResponse1",
        "SyncAccountsSuccessResponse",
        "SyncAudiencesAudience",
        "SyncAudiencesErrorResponse",
        "SyncAudiencesResponse1",
        "SyncAudiencesSubmittedResponse",
        "SyncAudiencesSuccessResponse",
        "SyncCatalogResult",
        "SyncCatalogsErrorResponse",
        "SyncCatalogsResponse1",
        "SyncCatalogsSubmittedResponse",
        "SyncCatalogsSuccessResponse",
        "SyncCreativeResult",
        "SyncCreativesErrorResponse",
        "SyncCreativesResponse1",
        "SyncCreativesResponse3",
        "SyncCreativesSubmittedResponse",
        "SyncCreativesSuccessResponse",
        "SyncEventSourcesErrorResponse",
        "SyncEventSourcesResponse1",
        "SyncEventSourcesSuccessResponse",
        "UpdateContentStandardsErrorResponse",
        "UpdateContentStandardsResponse1",
        "UpdateContentStandardsSuccessResponse",
        "UpdateMediaBuyPackagesRequest",
        "UpdateMediaBuyPropertiesRequest",
        "UrlDaastAsset",
        "UrlPreviewRender",
        "UrlVastAsset",
        "ValidateContentDeliveryErrorResponse",
        "ValidateContentDeliveryResponse1",
        "ValidateContentDeliverySuccessResponse",
    ),
    "adcp.types.core": (
        "AgentConfig",
        "Member",
        "Policy",
        "PolicyExemplar",
        "PolicyExemplars",
        "PolicyHistory",
        "PolicyRevision",
        "PolicySummary",
        "Protocol",
        "ResolvedBrand",
        "ResolvedProperty",
        "TaskResult",
        "TaskStatus",
        "WebhookMetadata",
    ),
    "adcp.types.guards": (
        "is_adcp_error",
        "is_adcp_success",
    ),
    "adcp.types.registry": (
        "AgentCapabilities",
        "AgentCompliance",
        "AgentHealth",
        "AgentStats",
        "BrandActivity",
        "BrandRegistryItem",
        "DomainLookupResult",
        "FederatedAgentWithDetails",
        "FederatedPublisher",
        "FeedEvent",
        "FeedPage",
        "PropertyActivity",
        "PropertyIdentifier",
        "PropertyRegistryItem",
        "PropertySummary",
        "ValidationResult",
    ),
    "adcp.utils": (
        "get_asset_count",
        "get_format_assets",
        "get_individual_assets",
        "get_optional_assets",
        "get_repeatable_groups",
        "get_required_assets",
        "has_assets",
        "normalize_assets_required",
        "uses_deprecated_assets_field",
    ),
    "adcp.validation": (
        "SchemaValidationError",
        "UnknownFieldPolicy",
        "ValidationError",
        "ValidationHookConfig",
        "ValidationIssue",
        "ValidationMode",
        "ValidationOutcome",
        "validate_adagents",
        "validate_agent_authorization",
        "validate_product",
        "validate_publisher_properties_item",
    ),
    "adcp.webhooks": (
        "LegacyHmacFallback",
        "MemoryBackend",
        "PreparedWebhook",
        "ScopePermanentlyUnknown",
        "ScopeTransientlyUnavailable",
        "WebhookChallengeError",
        "WebhookChallengeResult",
        "WebhookDedupStore",
        "WebhookDestinationPolicy",
        "WebhookReceiver",
        "WebhookReceiverConfig",
        "WebhookSender",
        "WebhookSenderResolution",
        "WebhookSenderResolver",
        "WebhookVerifyOptions",
        "challenge_webhook_destination",
        "create_a2a_webhook_payload",
        "create_mcp_webhook_payload",
        "create_webhook_challenge_payload",
        "extract_webhook_result_data",
        "generate_webhook_challenge_value",
        "generate_webhook_idempotency_key",
        "get_adcp_signed_headers_for_webhook",
        "sign_legacy_webhook",
        "sign_webhook",
        "to_wire_dict",
        "validate_webhook_challenge_response",
    ),
}

# name -> owning module (inverted once at import; cheap, strings only).
_LAZY: dict[str, str] = {name: module for module, names in _LAZY_MODULES.items() for name in names}


if not TYPE_CHECKING:
    # Defined under ``not TYPE_CHECKING`` so type checkers do NOT see a
    # module-level ``__getattr__`` (which would silence missing-attribute
    # errors and type every unknown name as ``object``). At type-check time the
    # surface comes only from the explicit ``TYPE_CHECKING`` block at the bottom
    # of this module, so ``from adcp import Typo`` is flagged. At runtime these
    # provide the lazy PEP 562 resolution.

    def __getattr__(name):
        """Lazily resolve the public ``adcp`` surface (PEP 562).

        Resolution order: (1) ``__version__`` resolves on demand; (2) names
        removed in 4.0 raise an informative :class:`ImportError`; (3) re-exported
        symbols are imported from their owning module and cached; (4) real
        submodules pass through to the import system so ``adcp.<submodule>``
        attribute access keeps working.
        """
        if name == "__version__":
            value = _resolve_version()
            globals()["__version__"] = value
            return value

        if name in _REMOVED_IN_V4:
            hint, anchor = _REMOVED_IN_V4[name]
            raise ImportError(
                f"`{name}` was removed in adcp 4.0: {hint}. See MIGRATION_v3_to_v4.md#{anchor}."
            )

        module_path = _LAZY.get(name)
        if module_path is not None:
            value = getattr(importlib.import_module(module_path), name)
            globals()[name] = value  # cache: __getattr__ fires once per name
            return value

        # Submodule passthrough — expose ``adcp.<name>`` for real submodules so
        # attribute access (not just ``import adcp.<name>``) resolves as before.
        if not name.startswith("__") and importlib.util.find_spec(f"adcp.{name}") is not None:
            module = importlib.import_module(f"adcp.{name}")
            globals()[name] = module
            return module

        raise AttributeError(f"module 'adcp' has no attribute {name!r}")

    def __dir__():
        return sorted(set(__all__) | set(_LAZY) | set(globals()) | {"__version__"})


def get_adcp_spec_version() -> str:
    """Get the AdCP specification version this SDK is built against.

    Pinned at build time from the ``ADCP_VERSION`` file packaged with
    the SDK. The version determines which AdCP schemas
    (``adcp.types.generated_poc``) ship with this release.

    Use this when you need to surface spec version to clients (agent
    cards, capability responses, debug endpoints) or validate
    cross-compatibility with a peer agent's advertised spec version.

    For the SDK package version (``4.0.0b1``, ``4.1.2``, etc.), use
    :func:`get_adcp_sdk_version` or the ``adcp.__version__`` attribute.

    Returns:
        AdCP specification version (e.g., ``"2.5.0"``, ``"latest"``).

    Raises:
        FileNotFoundError: If the packaged ``ADCP_VERSION`` file is
            missing — typically an indicator of a corrupt install.
    """
    from importlib.resources import files

    version_file = files("adcp") / "ADCP_VERSION"
    return version_file.read_text().strip()


def get_adcp_sdk_version() -> str:
    """Get this SDK's package version (e.g., ``"4.0.0b1"``).

    Prefer this function when pairing with :func:`get_adcp_spec_version`
    — the symmetric function form makes call sites read unambiguously.
    For a single-value import without the spec-vs-SDK context, use
    :attr:`adcp.__version__` directly.

    Returns:
        SDK package version string. Falls back to ``"0.0.0+unknown"``
        when running from an uninstalled source tree.
    """
    return _resolve_version()


def get_adcp_version() -> str:
    """Return the AdCP *spec* version (legacy name).

    .. deprecated:: 4.1
        Kept for backwards compatibility with pre-4.1 callers. Prefer
        :func:`get_adcp_spec_version` (spec version) or
        :func:`get_adcp_sdk_version` / :attr:`adcp.__version__` (SDK
        package version) — the split disambiguates what the caller
        actually wants at the call site.
    """
    import warnings

    warnings.warn(
        "get_adcp_version() is deprecated; use get_adcp_spec_version() "
        "for the AdCP spec version or get_adcp_sdk_version() / "
        "adcp.__version__ for the SDK package version.",
        DeprecationWarning,
        stacklevel=2,
    )
    return get_adcp_spec_version()


__all__ = [
    # Version functions
    "get_adcp_version",
    # Client classes
    "ADCPClient",
    "ADCPMultiAgentClient",
    "Checkpoint",
    "TaskOptions",
    "TaskRecoveryMetadata",
    "get_tracer",
    "inject_trace_headers",
    "is_tracing_available",
    # Seller acceptance-policy discovery and advisory assessment
    "AcceptancePolicyAssessment",
    "AcceptancePolicyDiagnostic",
    "AcceptancePolicyDiagnosticCode",
    "AcceptancePolicyOutcome",
    "AcceptancePolicyRegistry",
    "AcceptancePolicyResolution",
    "AcceptancePolicyResolver",
    "AcceptancePolicySurface",
    "DEFAULT_ACCEPTANCE_CATALOG_CACHE_ENTRIES",
    "DEFAULT_ACCEPTANCE_CATALOG_MAX_BYTES",
    "DEFAULT_ACCEPTANCE_CATALOG_TIMEOUT_SECONDS",
    "AcceptanceContext",
    "AcceptancePolicyCatalog",
    "AcceptancePolicyDiscovery",
    "AcceptancePolicyProfile",
    "AcceptancePolicyProfileId",
    "AcceptancePolicyProfileIds",
    "AcceptancePolicyRequirement",
    "AcceptancePolicyRule",
    "RegistryAcceptancePolicyProfileReference",
    # Proposal-bound MediaBuy action assessment and seller projection
    "ActionAvailabilityStatus",
    "ActionDiagnostic",
    "ActionDiagnosticCode",
    "ActionDispatchClient",
    "ActionIntent",
    "ActionKnowledge",
    "ActionTask",
    "ChangeTermSelection",
    "ConstraintCheck",
    "ConstraintOutcome",
    "MediaBuyActionAssessment",
    "MediaBuyActionError",
    "MediaBuyActionProjection",
    "ProjectedMediaBuyAction",
    "assess_media_buy_action",
    "assess_update_media_buy_actions",
    "dispatch_media_buy_action",
    "evaluate_action_constraints",
    "materialize_change_terms",
    "project_available_actions",
    "reassess_media_buy_action",
    "route_media_buy_action",
    # Generated beta.9 action-contract models
    "CanonicalMediaBuyAction",
    "CanonicalMediaBuyActionMode",
    "CanonicalMediaBuyActionName",
    "CanonicalProductAction",
    "CommercialTerms",
    "MediaBuyAvailableAction",
    "MediaBuyActionMode",
    "MediaBuyChangeTerm",
    "MediaBuyChangeTermConstraints",
    "MediaBuyChangeTermId",
    "MediaBuyValidAction",
    "BudgetChangeConstraints",
    "EffectiveTimingChangeConstraints",
    "FlightChangeConstraints",
    "PackageCountChangeConstraints",
    "ProductAllowedAction",
    # Buyer OAuth authorization-code helpers
    "InMemoryPendingOAuthFlowStore",
    "OAuthAuthorizationError",
    "OAuthAuthorizationRequest",
    "OAuthAuthorizationServerMetadata",
    "OAuthClientError",
    "OAuthDiscoveryError",
    "OAuthFlowStoreError",
    "OAuthIssuerBinding",
    "OAuthTokenExchangeError",
    "OAuthTokenSet",
    "PendingOAuthAuthorization",
    "PendingOAuthFlowStore",
    "complete_oauth_authorization",
    "discover_oauth_metadata",
    "start_oauth_authorization",
    "RegistryClient",
    "PropertyRegistry",
    "RegistrySync",
    "CursorStore",
    "FileCursorStore",
    "ChangeHandler",
    # Universal macro substitution
    "MacroMapping",
    "MacroMappingEntry",
    "NativeMacroMapping",
    "TranslateUniversalMacrosResult",
    "UniversalMacroTranslationError",
    "UniversalMacroTranslationErrorCode",
    "ValueMacroMapping",
    "encode_unreserved",
    "translate_universal_macros",
    # Wholesale feed mirror
    "FeedMirror",
    "FeedMirrorClient",
    "FeedMirrorError",
    "FeedState",
    "FeedStateStore",
    "RefreshResult",
    "EventHandler",
    # Registry types
    "AgentCapabilities",
    "AgentCompliance",
    "AgentHealth",
    "AgentStats",
    "BrandActivity",
    "BrandRegistryItem",
    "DomainLookupResult",
    "FederatedAgentWithDetails",
    "FederatedPublisher",
    "FeedEvent",
    "FeedPage",
    "PropertyActivity",
    "PropertyIdentifier",
    "PropertyRegistryItem",
    "PropertySummary",
    "ValidationResult",
    # Capability validation
    "FeatureResolver",
    "validate_capabilities",
    # Core types
    "AgentConfig",
    "Member",
    "Policy",
    "PolicyExemplar",
    "PolicyExemplars",
    "PolicyHistory",
    "PolicyRevision",
    "PolicySummary",
    "Protocol",
    "ResolvedBrand",
    "ResolvedProperty",
    "TaskResult",
    "TaskStatus",
    "WebhookMetadata",
    # Webhook utilities
    "create_mcp_webhook_payload",
    "create_a2a_webhook_payload",
    "create_webhook_challenge_payload",
    "challenge_webhook_destination",
    "validate_webhook_challenge_response",
    "get_adcp_signed_headers_for_webhook",
    "extract_webhook_result_data",
    "generate_webhook_challenge_value",
    "generate_webhook_idempotency_key",
    "sign_legacy_webhook",
    "sign_webhook",
    "to_wire_dict",
    "WebhookChallengeError",
    "WebhookChallengeResult",
    "WebhookDestinationPolicy",
    "WebhookReceiver",
    "WebhookReceiverConfig",
    "WebhookSender",
    "WebhookSenderResolution",
    "WebhookSenderResolver",
    "ScopePermanentlyUnknown",
    "ScopeTransientlyUnavailable",
    "WebhookVerifyOptions",
    "WebhookDedupStore",
    "MemoryBackend",
    "LegacyHmacFallback",
    "PreparedWebhook",
    "McpWebhookPayload",
    # Account operations
    "AccountAuthorization",
    "AccountReference",
    "AccountWithAuthorization",
    "GetAccountFinancialsRequest",
    "GetAccountFinancialsResponse",
    "GetAccountFinancialsResponse1",
    "GetAccountFinancialsSuccessResponse",
    "GetAccountFinancialsErrorResponse",
    "ReportUsageRequest",
    "ReportUsageResponse",
    # Common request/response types (re-exported for convenience)
    "CheckGovernanceRequest",
    "CheckGovernanceResponse",
    # TMP
    "ContextMatchRequest",
    "ContextMatchResponse",
    "IdentityMatchRequest",
    "IdentityMatchResponse",
    "IdentityMatchTmpxMacro",
    # Brand Rights
    "AcquireRightsRequest",
    "AcquireRightsResponse",
    "AcquireRightsResponse1",
    "AcquireRightsAcquiredResponse",
    "AcquireRightsErrorResponse",
    "AcquireRightsPendingResponse",
    "AcquireRightsRejectedResponse",
    "GetBrandIdentityRequest",
    "GetBrandIdentityResponse",
    "GetBrandIdentityResponse1",
    "GetBrandIdentitySuccessResponse",
    "GetBrandIdentityErrorResponse",
    "GetRightsRequest",
    "GetRightsResponse",
    "GetRightsResponse1",
    "GetRightsSuccessResponse",
    "GetRightsErrorResponse",
    # Compliance
    "ComplyTestControllerRequest",
    "ComplyTestControllerResponse",
    # AdCP 3.2 compact media-buy lifecycle
    "AcceptProposalRequest",
    "AcceptProposalResponse",
    "AcceptedLoss",
    "BuyProductsRequest",
    "BuyProductsResponse",
    "ControlMediaBuyRequest",
    "ControlMediaBuyResponse",
    "CompatibilityPurchaseCoordinatorInput",
    "DeclineProposalsRequest",
    "DeclineProposalsResponse",
    "ListProductsRequest",
    "ListProductsResponse",
    "RefineProposalsRequest",
    "RefineProposalsResponse",
    "RequestProposalsRequest",
    "RequestProposalsResponse",
    "CreateMediaBuyRequest",
    "CreateMediaBuyResponse",
    "GetCreativeDeliveryRequest",
    "GetCreativeDeliveryResponse",
    "GetCreativeFeaturesRequest",
    "GetCreativeFeaturesResponse",
    "GetCreativeFeaturesResponse1",
    "GetCreativeFeaturesSuccessResponse",
    "GetCreativeFeaturesErrorResponse",
    "GetTaskStatusRequest",
    "GetTaskStatusResponse",
    "ListTasksRequest",
    "ListTasksResponse",
    "ListTransformersRequest",
    "ListTransformersResponse",
    "GetPlanAuditLogsRequest",
    "GetPlanAuditLogsResponse",
    "GetMediaBuyDeliveryRequest",
    "GetMediaBuyDeliveryResponse",
    "GetMediaBuysRequest",
    "GetMediaBuysResponse",
    "GetProductsRequest",
    "GetProductsResponse",
    "UpdateMediaBuyRequest",
    "UpdateMediaBuyResponse",
    "ValidateInputRequest",
    "ValidateInputResponse",
    "ListAccountsRequest",
    "ListAccountsResponse",
    "ListAccountChangesRequest",
    "ListAccountChangesResponse",
    "ListCreativesRequest",
    "ListCreativesResponse",
    "LogEventRequest",
    "LogEventResponse",
    "SyncAccountsRequest",
    "SyncAccountsResponse",
    "SyncAudiencesRequest",
    "SyncAudiencesResponse",
    "SyncCatalogsInputRequired",
    "SyncCatalogsRequest",
    "SyncCatalogsResponse",
    "SyncCatalogsSubmitted",
    "SyncCatalogsWorking",
    "SyncCreativesRequest",
    "SyncCreativesResponse",
    "SyncEventSourcesRequest",
    "SyncEventSourcesResponse",
    "AuthorizationRequiredDetails",
    "DownstreamConnectionRequirement",
    "SyncPlansRequest",
    "SyncPlansResponse",
    "SyncAgentNotificationConfigsRequest",
    "SyncAgentNotificationConfigsResponse",
    "ActivateSignalRequest",
    "ActivateSignalResponse",
    "VerifyBrandClaimPayload",
    "VerifyBrandClaimRequest",
    "VerifyBrandClaimResponse",
    "VerifyBrandClaimSignedResponse",
    "VerifyBrandClaimSignedSuccessPayload",
    "VerifyBrandClaimsErrorResponse",
    "VerifyBrandClaimsPayload",
    "VerifyBrandClaimsRequest",
    "VerifyBrandClaimsRequestBulk",
    "VerifyBrandClaimsResponse",
    "VerifyBrandClaimsResponseBulk",
    "VerifyBrandClaimsSignedResponse",
    "VerifyBrandClaimsSignedSuccessPayload",
    "GetSignalsRequest",
    "GetSignalsResponse",
    "SignalFilters",
    "ProvidePerformanceFeedbackRequest",
    "ProvidePerformanceFeedbackResponse",
    "Error",
    "Format",
    "LegacyBuildCreativeErrorResponse",
    "LegacyBuildCreativeRequest",
    "LegacyBuildCreativeResponse",
    "LegacyBuildCreativeResponse1",
    "LegacyBuildCreativeResponse2",
    "LegacyBuildCreativeResponse3",
    "LegacyBuildCreativeResponse4",
    "LegacyBuildCreativeResponse5",
    "LegacyBuildCreativeResponse6",
    "LegacyBuildCreativeSubmittedResponse",
    "LegacyBuildCreativeSuccessResponse",
    "LegacyCreateMediaBuyRequest",
    "LegacyCreativeAsset",
    "LegacyCreativeFilters",
    "LegacyFormat",
    "LegacyFormatId",
    "LegacyFormatReferenceStructuredObject",
    "LegacyGetCreativeDeliveryResponse",
    "LegacyGetMediaBuyDeliveryResponse",
    "LegacyGetMediaBuysResponse",
    "LegacyGetProductsRequest",
    "LegacyGetProductsResponse",
    "LegacyListCreativeFormatsRequest",
    "LegacyListCreativeFormatsResponse",
    "LegacyListCreativesRequest",
    "LegacyListCreativesResponse",
    "LegacyPackage",
    "LegacyPackageRequest",
    "LegacyPackageUpdate",
    "LegacyPlacement",
    "LegacyPreviewCreativeBatchResponse",
    "LegacyPreviewCreativeRequest",
    "LegacyPreviewCreativeResponse",
    "LegacyPreviewCreativeResponse1",
    "LegacyPreviewCreativeResponse2",
    "LegacyPreviewCreativeResponse3",
    "LegacyPreviewCreativeSingleResponse",
    "LegacyPreviewCreativeVariantResponse",
    "LegacyProduct",
    "LegacyProductFormatDeclaration",
    "LegacyProductFilters",
    "LegacySyncCreativesRequest",
    "LegacyUpdateMediaBuyRequest",
    "format_is_supported",
    "formats_are_equivalent",
    "upgrade_legacy_format_id",
    "FormatOptionReference",
    "AssetContentType",
    "AssetInstance",
    "AssetInstanceType",
    "AssetVariant",
    "AudioContent",
    "BriefAsset",
    "CardAsset",
    "CatalogAsset",
    "CssContent",
    "DaastAsset",
    "DaastTrackerAsset",
    "HtmlContent",
    "ImageContent",
    "JavascriptContent",
    "MarkdownAsset",
    "PixelTrackerAsset",
    "PublishedPostAsset",
    "TextContent",
    "UrlContent",
    "VastAsset",
    "VastTrackerAsset",
    "VideoContent",
    "WebhookContent",
    "ZipAsset",
    "Product",
    "ProductFormatDeclaration",
    "ProductFilters",
    "ProductSignalTargetingOption",
    # Catalog types
    "Catalog",
    "CatalogAction",
    "CatalogFieldBinding",
    "CatalogFieldMapping",
    "CatalogItemStatus",
    "CatalogRequirements",
    "CatalogType",
    "ConsentBasis",
    "ContentIdType",
    "FeedFormat",
    "Gtin",
    "OfferingAssetConstraint",
    "OfferingAssetGroup",
    "Transform",
    "UpdateFrequency",
    # Backward compat: these types were removed from upstream schemas
    "Property",
    "SignalAvailabilityType",
    "SignalCatalogType",
    # Core domain types (from stable API)
    "AccountScope",
    "AdvertiserIndustry",
    "ArtifactWebhookPayload",
    "AudienceSource",
    "BrandIdentity",
    "BrandReference",
    "BrandSource",
    "BuyingMode",
    "CatalogGroupBinding",
    "ContextObject",
    "Creative",
    "CreativeApproval",
    "CreativeApprovalStatus",
    "CreativeFilters",
    "CreativeManifest",
    "CreativeVariant",
    "DateRange",
    "DatetimeRange",
    "DevicePlatform",
    "DeviceType",
    "Duration",
    "ErrorCode",
    "EventType",
    "ExtensionObject",
    "KellerType",
    "MediaBuy",
    "MediaBuyDeliveryWebhookResult",
    "MediaBuyDeliveryStatus",
    "MediaBuyPackage",
    "MediaChannel",
    "OptimizationGoal",
    "Overlay",
    "Package",
    "PackageRequest",
    "PackageSignalTargeting",
    "PackageSignalTargetingGroup",
    "PackageSignalTargetingGroups",
    "PaginationRequest",
    "Placement",
    "PlacementPresentationDocument",
    "PlacementPresentationReference",
    "PlacementReference",
    "PreviewRendererMetadata",
    "Proposal",
    "Refine",
    "ReportPlanOutcomeRequest",
    "ReportPlanOutcomeResponse",
    "ReportPlanAdjustmentRequest",
    "ReportPlanAdjustmentResponse",
    "SellerAgentReference",
    "Snapshot",
    "SnapshotUnavailableReason",
    "TargetingOverlay",
    "WcagLevel",
    # Status enums (for control flow)
    "CreativeStatus",
    "DeliveryStatus",
    "MediaBuyStatus",
    "PricingModel",
    "PricingCurrency",
    "ProviderRegistrationTmpxMacro",
    "PublisherDesignatedPreviewProvider",
    "ReferenceRenderer",
    # Pricing-related types
    "CpaPricingOption",
    "CpcPricingOption",
    "CpcvPricingOption",
    "CpmPricingOption",
    "CppPricingOption",
    "CpvPricingOption",
    "FlatRatePricingOption",
    "PriceGuidance",
    "TimeBasedPricingOption",
    "TimeUnit",
    "VcpmPricingOption",
    # Signal pricing types
    "SignalPricingOption",
    "SignalDefinitionEnrichment",
    "SignalListing",
    "SignalRef",
    "SignalTargeting",
    "SignalTargetingExpression",
    "SignalTargetingRules",
    # Configuration types
    "NotificationConfig",
    "PushNotificationConfig",
    "ResponsePayloadJwsEnvelope",
    "WholesaleFeedEvent",
    "WholesaleFeedWebhook",
    "WebhookChallenge",
    "WebhookChallengeResponse",
    # Adagents validation
    "AdAgentsValidationResult",
    "AdagentsCacheEntry",
    "AdagentsEntryError",
    "AdagentsFetchResult",
    "AdagentsValidationReport",
    "AgentAuthorizationsDirectoryResult",
    "AuthorizationContext",
    "DirectoryDiscoveryMethod",
    "DirectoryEdgeStatus",
    "DirectoryPublisherEntry",
    "DiscoveryMethod",
    "DivergenceReport",
    "EntryErrorKind",
    "PublisherDivergence",
    "detect_publisher_properties_divergence",
    "fetch_adagents",
    "fetch_adagents_with_cache",
    "fetch_agent_authorizations",
    "fetch_agent_authorizations_from_directory",
    "filter_revoked_selectors",
    "validate_adagents_domain",
    "validate_adagents_structure",
    "verify_agent_authorization",
    "verify_agent_for_property",
    "domain_matches",
    "identifiers_match",
    "get_all_properties",
    "get_all_tags",
    "get_properties_by_agent",
    "resolve_properties_for_agent",
    # Test helpers
    "test_agent",
    "test_agent_a2a",
    "test_agent_no_auth",
    "test_agent_a2a_no_auth",
    "creative_agent",
    "test_agent_client",
    "create_test_agent",
    "TEST_AGENT_TOKEN",
    "TEST_AGENT_MCP_CONFIG",
    "TEST_AGENT_A2A_CONFIG",
    "TEST_AGENT_MCP_NO_AUTH_CONFIG",
    "TEST_AGENT_A2A_NO_AUTH_CONFIG",
    "CREATIVE_AGENT_CONFIG",
    # Exceptions
    "ADCPError",
    "ADCPFeatureUnsupportedError",
    "ADCPConnectionError",
    "ADCPAuthenticationError",
    "ADCPTimeoutError",
    "ADCPProtocolError",
    "ADCPTaskError",
    "ADCPToolNotFoundError",
    "ADCPSigningRequiredError",
    "ADCPWebhookError",
    "ADCPWebhookSignatureError",
    "AdagentsAccessBlockedError",
    "AdagentsValidationError",
    "AdagentsNotFoundError",
    "AdagentsTimeoutError",
    "ConfigurationError",
    "IdempotencyConflictError",
    "IdempotencyExpiredError",
    "IdempotencyScopeError",
    "IdempotencyUnsupportedError",
    "RegistryError",
    "RegistryErrorDetails",
    "RegistryValidationIssue",
    # Validation utilities
    "SchemaValidationError",
    "UnknownFieldPolicy",
    "ValidationError",
    "ValidationHookConfig",
    "ValidationIssue",
    "ValidationMode",
    "ValidationOutcome",
    "validate_adagents",
    "validate_agent_authorization",
    "validate_product",
    "validate_publisher_properties_item",
    # Format asset utilities
    "get_format_assets",
    "normalize_assets_required",
    "get_required_assets",
    "get_optional_assets",
    "get_individual_assets",
    "get_repeatable_groups",
    "uses_deprecated_assets_field",
    "get_asset_count",
    "has_assets",
    # Generated types modules
    "generated",
    "aliases",
    "GeneratedTaskStatus",
    # Semantic type aliases (for better API ergonomics)
    "AccountReferenceById",
    "AccountReferenceByNaturalKey",
    "AcquireRightsResponse1",
    "ActivateSignalResponse1",
    "ActivateSignalSuccessResponse",
    "ActivateSignalErrorResponse",
    "AgentDeployment",
    "AgentDestination",
    "AuthorizedAgent",
    "AuthorizedAgentsByInlineProperties",
    "AuthorizedAgentsByPropertyId",
    "AuthorizedAgentsByPropertyTag",
    "AuthorizedAgentsByPublisherProperties",
    "AuthorizedAgentsBySignalId",
    "AuthorizedAgentsBySignalTag",
    "BothPreviewRender",
    "CalibrateContentSuccessResponse",
    "CalibrateContentResponse1",
    "CalibrateContentErrorResponse",
    "ComplyTestControllerResponse1",
    "CreateContentStandardsSuccessResponse",
    "CreateContentStandardsResponse1",
    "CreateContentStandardsErrorResponse",
    "CreateMediaBuySuccessResponse",
    "CreateMediaBuyResponse1",
    "CreateMediaBuyErrorResponse",
    "CreateMediaBuySubmittedResponse",
    "Deployment",
    "Destination",
    "GetContentStandardsSuccessResponse",
    "GetContentStandardsResponse1",
    "GetContentStandardsErrorResponse",
    "GetCreativeDeliveryByBuyerRefRequest",
    "GetCreativeDeliveryByCreativeRequest",
    "GetCreativeDeliveryByMediaBuyRequest",
    "GetMediaBuyArtifactsSuccessResponse",
    "GetMediaBuyArtifactsResponse1",
    "GetMediaBuyArtifactsErrorResponse",
    "GetProductsBriefRequest",
    "GetProductsRefineRequest",
    "GetProductsWholesaleRequest",
    "GetSignalsDiscoveryRequest",
    "GetSignalsLookupRequest",
    "HtmlPreviewRender",
    "InlineDaastAsset",
    "InlineVastAsset",
    "KeyValueActivationKey",
    "ListContentStandardsSuccessResponse",
    "ListContentStandardsResponse1",
    "ListContentStandardsErrorResponse",
    "LogEventSuccessResponse",
    "LogEventResponse1",
    "LogEventErrorResponse",
    "PlatformDeployment",
    "PlatformDestination",
    "PricingOption",
    "PropertyId",
    "PropertyTag",
    "ProvidePerformanceFeedbackByBuyerRefRequest",
    "ProvidePerformanceFeedbackByMediaBuyRequest",
    "ProvidePerformanceFeedbackSuccessResponse",
    "ProvidePerformanceFeedbackResponse1",
    "ProvidePerformanceFeedbackErrorResponse",
    "PublisherProperties",
    "PublisherPropertiesAll",
    "PublisherPropertiesById",
    "PublisherPropertiesByTag",
    "SegmentIdActivationKey",
    "SiSendActionResponseRequest",
    "SiSendTextMessageRequest",
    "SyncAccountsSuccessResponse",
    "SyncAccountsResponse1",
    "SyncAccountsErrorResponse",
    "SyncAudiencesAudience",
    "SyncAudiencesSuccessResponse",
    "SyncAudiencesResponse1",
    "SyncAudiencesErrorResponse",
    "SyncAudiencesSubmittedResponse",
    "SyncCatalogResult",
    "SyncCatalogsSuccessResponse",
    "SyncCatalogsResponse1",
    "SyncCatalogsErrorResponse",
    "SyncCatalogsSubmittedResponse",
    "SyncCreativeResult",
    "SyncCreativesSuccessResponse",
    "SyncCreativesResponse1",
    "SyncCreativesErrorResponse",
    "SyncCreativesResponse3",
    "SyncCreativesSubmittedResponse",
    "SyncEventSourcesSuccessResponse",
    "SyncEventSourcesResponse1",
    "SyncEventSourcesErrorResponse",
    "UpdateContentStandardsSuccessResponse",
    "UpdateContentStandardsResponse1",
    "UpdateContentStandardsErrorResponse",
    "UpdateMediaBuySuccessResponse",
    "UpdateMediaBuyResponse1",
    "UpdateMediaBuyErrorResponse",
    "UpdateMediaBuyResponse3",
    "UpdateMediaBuyPackagesRequest",
    "UpdateMediaBuyPropertiesRequest",
    "UpdateMediaBuySubmittedResponse",
    "UrlDaastAsset",
    "UrlPreviewRender",
    "UrlVastAsset",
    "ValidateContentDeliverySuccessResponse",
    "ValidateContentDeliveryResponse1",
    "ValidateContentDeliveryErrorResponse",
    # Backward compat: renamed/removed types
    # Backward compat: pricing type renames
    "CpmAuctionPricingOption",
    "CpmFixedRatePricingOption",
    "VcpmAuctionPricingOption",
    "VcpmFixedRatePricingOption",
    # Backward compat: activation key schema change
    "PropertyIdActivationKey",
    "PropertyTagActivationKey",
    # Backward compat: preview alias renames
    # Backward compat: types removed from upstream schemas
]


if TYPE_CHECKING:
    # Eager re-exports for type checkers / IDEs. Resolved lazily at runtime
    # via ``__getattr__`` so ``import adcp`` does not build the schema graph.
    from adcp.acceptance import (  # noqa: F401
        DEFAULT_ACCEPTANCE_CATALOG_CACHE_ENTRIES,
        DEFAULT_ACCEPTANCE_CATALOG_MAX_BYTES,
        DEFAULT_ACCEPTANCE_CATALOG_TIMEOUT_SECONDS,
        AcceptancePolicyAssessment,
        AcceptancePolicyDiagnostic,
        AcceptancePolicyDiagnosticCode,
        AcceptancePolicyOutcome,
        AcceptancePolicyRegistry,
        AcceptancePolicyResolution,
        AcceptancePolicyResolver,
        AcceptancePolicySurface,
    )
    from adcp.adagents import (
        AdagentsCacheEntry,
        AdagentsEntryError,
        AdagentsFetchResult,
        AdagentsValidationReport,
        AdAgentsValidationResult,
        AgentAuthorizationsDirectoryResult,
        AuthorizationContext,
        DirectoryDiscoveryMethod,
        DirectoryEdgeStatus,
        DirectoryPublisherEntry,
        DiscoveryMethod,
        DivergenceReport,
        EntryErrorKind,
        PublisherDivergence,
        detect_publisher_properties_divergence,
        domain_matches,
        fetch_adagents,
        fetch_adagents_with_cache,
        fetch_agent_authorizations,
        fetch_agent_authorizations_from_directory,
        filter_revoked_selectors,
        get_all_properties,
        get_all_tags,
        get_properties_by_agent,
        identifiers_match,
        resolve_properties_for_agent,
        validate_adagents_domain,
        validate_adagents_structure,
        verify_agent_authorization,
        verify_agent_for_property,
    )
    from adcp.canonical_formats import (
        format_is_supported,
        formats_are_equivalent,
        upgrade_legacy_format_id,
    )
    from adcp.capabilities import (  # noqa: F401
        FeatureResolver,
        build_synthetic_capabilities,
        looks_like_v3_capabilities,
        validate_capabilities,
    )
    from adcp.client import ADCPClient, ADCPMultiAgentClient, Checkpoint
    from adcp.exceptions import (  # noqa: F401
        AdagentsAccessBlockedError,
        AdagentsNotFoundError,
        AdagentsTimeoutError,
        AdagentsValidationError,
        ADCPAuthenticationError,
        ADCPConnectionError,
        ADCPError,
        ADCPFeatureUnsupportedError,
        ADCPProtocolError,
        ADCPSigningRequiredError,
        ADCPTaskError,
        ADCPTimeoutError,
        ADCPToolNotFoundError,
        ADCPWebhookError,
        ADCPWebhookSignatureError,
        ConfigurationError,
        IdempotencyConflictError,
        IdempotencyExpiredError,
        IdempotencyScopeError,
        IdempotencyUnsupportedError,
        RegistryError,
        RegistryErrorDetails,
        RegistryValidationIssue,
    )
    from adcp.feed_mirror import (
        EventHandler,
        FeedMirror,
        FeedMirrorClient,
        FeedMirrorError,
        FeedState,
        FeedStateStore,
        RefreshResult,
    )
    from adcp.media_buy_actions import (  # noqa: F401
        ActionAvailabilityStatus,
        ActionDiagnostic,
        ActionDiagnosticCode,
        ActionDispatchClient,
        ActionIntent,
        ActionKnowledge,
        ActionTask,
        ChangeTermSelection,
        ConstraintCheck,
        ConstraintOutcome,
        MediaBuyActionAssessment,
        MediaBuyActionError,
        MediaBuyActionProjection,
        ProjectedMediaBuyAction,
        assess_media_buy_action,
        assess_update_media_buy_actions,
        dispatch_media_buy_action,
        evaluate_action_constraints,
        materialize_change_terms,
        project_available_actions,
        reassess_media_buy_action,
        route_media_buy_action,
    )
    from adcp.oauth import (
        InMemoryPendingOAuthFlowStore,
        OAuthAuthorizationError,
        OAuthAuthorizationRequest,
        OAuthAuthorizationServerMetadata,
        OAuthClientError,
        OAuthDiscoveryError,
        OAuthFlowStoreError,
        OAuthIssuerBinding,
        OAuthTokenExchangeError,
        OAuthTokenSet,
        PendingOAuthAuthorization,
        PendingOAuthFlowStore,
        complete_oauth_authorization,
        discover_oauth_metadata,
        start_oauth_authorization,
    )
    from adcp.observability import get_tracer, inject_trace_headers, is_tracing_available
    from adcp.property_registry import PropertyRegistry
    from adcp.registry import RegistryClient
    from adcp.registry_sync import (
        ChangeHandler,
        CursorStore,
        FileCursorStore,
        RegistrySync,
    )
    from adcp.substitution import (
        MacroMapping,
        MacroMappingEntry,
        NativeMacroMapping,
        TranslateUniversalMacrosResult,
        UniversalMacroTranslationError,
        UniversalMacroTranslationErrorCode,
        ValueMacroMapping,
        encode_unreserved,
        translate_universal_macros,
    )
    from adcp.task_options import TaskOptions, TaskRecoveryMetadata
    from adcp.testing import (
        CREATIVE_AGENT_CONFIG,
        TEST_AGENT_A2A_CONFIG,
        TEST_AGENT_A2A_NO_AUTH_CONFIG,
        TEST_AGENT_MCP_CONFIG,
        TEST_AGENT_MCP_NO_AUTH_CONFIG,
        TEST_AGENT_TOKEN,
        create_test_agent,
        creative_agent,
        test_agent,
        test_agent_a2a,
        test_agent_a2a_no_auth,
        test_agent_client,
        test_agent_no_auth,
    )
    from adcp.types import (
        AcceptanceContext as AcceptanceContext,
    )
    from adcp.types import (
        AcceptancePolicyCatalog as AcceptancePolicyCatalog,
    )
    from adcp.types import (
        AcceptancePolicyDiscovery as AcceptancePolicyDiscovery,
    )
    from adcp.types import (
        AcceptancePolicyProfile as AcceptancePolicyProfile,
    )
    from adcp.types import (
        AcceptancePolicyProfileId as AcceptancePolicyProfileId,
    )
    from adcp.types import (
        AcceptancePolicyProfileIds as AcceptancePolicyProfileIds,
    )
    from adcp.types import (
        AcceptancePolicyRequirement as AcceptancePolicyRequirement,
    )
    from adcp.types import (
        AcceptancePolicyRule as AcceptancePolicyRule,
    )
    from adcp.types import (
        AcceptedLoss,
        AcceptProposalRequest,
        AcceptProposalResponse,
        # Account types
        AccountAuthorization,
        AccountReference,
        # Type enums from PR #222
        AccountScope,
        AccountWithAuthorization,
        # Brand Rights
        AcquireRightsRequest,
        AcquireRightsResponse,
        # Audience & Targeting
        ActivateSignalRequest,
        ActivateSignalResponse,
        AdvertiserIndustry,
        # Creative types
        ArtifactWebhookPayload,
        AssetContentType,
        AssetInstance,
        AssetInstanceType,
        AssetVariant,
        AudienceSource,
        AudioContent,
        AuthorizationRequiredDetails,
        # Core domain types
        BrandIdentity,
        BrandReference,
        BrandSource,
        # Creative Operations
        BriefAsset,
        BudgetChangeConstraints,
        BuyingMode,
        BuyProductsRequest,
        BuyProductsResponse,
        CanonicalMediaBuyAction,
        CanonicalMediaBuyActionMode,
        CanonicalMediaBuyActionName,
        CanonicalProductAction,
        CardAsset,
        # Catalog types
        Catalog,
        CatalogAction,
        CatalogAsset,
        CatalogFieldBinding,
        CatalogFieldMapping,
        CatalogGroupBinding,
        CatalogItemStatus,
        CatalogRequirements,
        CatalogType,
        CheckGovernanceRequest,
        CheckGovernanceResponse,
        CommercialTerms,
        CompatibilityPurchaseCoordinatorInput,
        ComplyTestControllerRequest,
        ComplyTestControllerResponse,
        ConsentBasis,
        ContentIdType,
        ContextMatchRequest,
        ContextMatchResponse,
        ContextObject,
        ControlMediaBuyRequest,
        ControlMediaBuyResponse,
        # Pricing options (all types for product creation)
        CpaPricingOption,
        CpcPricingOption,
        CpcvPricingOption,
        CpmAuctionPricingOption,
        CpmFixedRatePricingOption,
        CpmPricingOption,
        CppPricingOption,
        CpvPricingOption,
        # Media Buy Operations
        CreateMediaBuyRequest,
        CreateMediaBuyResponse,
        Creative,
        CreativeApproval,
        CreativeApprovalStatus,
        CreativeFilters,
        CreativeManifest,
        # Status enums (for control flow)
        CreativeStatus,
        CreativeVariant,
        CssContent,
        DaastAsset,
        DaastTrackerAsset,
        DateRange,
        DatetimeRange,
        DeclineProposalsRequest,
        DeclineProposalsResponse,
        DeliveryStatus,
        DevicePlatform,
        DeviceType,
        DownstreamConnectionRequirement,
        Duration,
        EffectiveTimingChangeConstraints,
        # Common data types
        Error,
        ErrorCode,
        EventType,
        ExtensionObject,
        FeedFormat,
        FlatRatePricingOption,
        FlightChangeConstraints,
        Format,
        FormatOptionReference,
        GeneratedTaskStatus,
        GetAccountFinancialsRequest,
        GetAccountFinancialsResponse,
        GetBrandIdentityRequest,
        GetBrandIdentityResponse,
        # Creative Delivery
        GetCreativeDeliveryRequest,
        GetCreativeDeliveryResponse,
        GetCreativeFeaturesRequest,
        GetCreativeFeaturesResponse,
        GetMediaBuyDeliveryRequest,
        GetMediaBuyDeliveryResponse,
        GetMediaBuysRequest,
        GetMediaBuysResponse,
        GetPlanAuditLogsRequest,
        GetPlanAuditLogsResponse,
        GetProductsRequest,
        GetProductsResponse,
        GetRightsRequest,
        GetRightsResponse,
        GetSignalsRequest,
        GetSignalsResponse,
        GetTaskStatusRequest,
        GetTaskStatusResponse,
        Gtin,
        HtmlContent,
        IdentityMatchRequest,
        IdentityMatchResponse,
        IdentityMatchTmpxMacro,
        ImageContent,
        JavascriptContent,
        KellerType,
        LegacyBuildCreativeErrorResponse,
        LegacyBuildCreativeRequest,
        LegacyBuildCreativeResponse,
        LegacyBuildCreativeResponse1,
        LegacyBuildCreativeResponse2,
        LegacyBuildCreativeResponse3,
        LegacyBuildCreativeResponse4,
        LegacyBuildCreativeResponse5,
        LegacyBuildCreativeResponse6,
        LegacyBuildCreativeSubmittedResponse,
        LegacyBuildCreativeSuccessResponse,
        LegacyCreateMediaBuyRequest,
        LegacyCreativeAsset,
        LegacyCreativeFilters,
        LegacyFormat,
        LegacyFormatId,
        LegacyFormatReferenceStructuredObject,
        LegacyGetCreativeDeliveryResponse,
        LegacyGetMediaBuyDeliveryResponse,
        LegacyGetMediaBuysResponse,
        LegacyGetProductsRequest,
        LegacyGetProductsResponse,
        LegacyListCreativeFormatsRequest,
        LegacyListCreativeFormatsResponse,
        LegacyListCreativesRequest,
        LegacyListCreativesResponse,
        LegacyPackage,
        LegacyPackageRequest,
        LegacyPackageUpdate,
        LegacyPlacement,
        LegacyPreviewCreativeBatchResponse,
        LegacyPreviewCreativeRequest,
        LegacyPreviewCreativeResponse,
        LegacyPreviewCreativeResponse1,
        LegacyPreviewCreativeResponse2,
        LegacyPreviewCreativeResponse3,
        LegacyPreviewCreativeSingleResponse,
        LegacyPreviewCreativeVariantResponse,
        LegacyProduct,
        LegacyProductFilters,
        LegacyProductFormatDeclaration,
        LegacySyncCreativesRequest,
        LegacyUpdateMediaBuyRequest,
        ListAccountChangesRequest,
        ListAccountChangesResponse,
        # Account Operations
        ListAccountsRequest,
        ListAccountsResponse,
        ListCreativesRequest,
        ListCreativesResponse,
        ListProductsRequest,
        ListProductsResponse,
        ListTasksRequest,
        ListTasksResponse,
        ListTransformersRequest,
        ListTransformersResponse,
        # Event Operations
        LogEventRequest,
        LogEventResponse,
        MarkdownAsset,
        McpWebhookPayload,
        MediaBuy,
        MediaBuyActionMode,
        MediaBuyAvailableAction,
        MediaBuyChangeTerm,
        MediaBuyChangeTermConstraints,
        MediaBuyChangeTermId,
        MediaBuyDeliveryStatus,
        MediaBuyDeliveryWebhookResult,
        MediaBuyPackage,
        MediaBuyStatus,
        MediaBuyValidAction,
        MediaChannel,
        NotificationConfig,
        OfferingAssetConstraint,
        OfferingAssetGroup,
        # Optimization
        OptimizationGoal,
        # Format overlays
        Overlay,
        Package,
        PackageCountChangeConstraints,
        PackageRequest,
        PackageSignalTargeting,
        PackageSignalTargetingGroup,
        PackageSignalTargetingGroups,
        PaginationRequest,
        PixelTrackerAsset,
        Placement,
        PlacementPresentationDocument,
        PlacementPresentationReference,
        PlacementReference,
        PreviewRendererMetadata,
        PriceGuidance,
        PricingCurrency,
        PricingModel,
        Product,
        ProductAllowedAction,
        ProductFilters,
        ProductFormatDeclaration,
        ProductSignalTargetingOption,
        Property,
        PropertyIdActivationKey,
        PropertyTagActivationKey,
        Proposal,
        ProvidePerformanceFeedbackRequest,
        ProvidePerformanceFeedbackResponse,
        ProviderRegistrationTmpxMacro,
        PublishedPostAsset,
        PublisherDesignatedPreviewProvider,
        PushNotificationConfig,
        ReferenceRenderer,
        Refine,
        RefineProposalsRequest,
        RefineProposalsResponse,
        ReportPlanAdjustmentRequest,
        ReportPlanAdjustmentResponse,
        ReportPlanOutcomeRequest,
        ReportPlanOutcomeResponse,
        ReportUsageRequest,
        ReportUsageResponse,
        RequestProposalsRequest,
        RequestProposalsResponse,
        ResponsePayloadJwsEnvelope,
        SellerAgentReference,
        SignalAvailabilityType,
        SignalCatalogType,
        SignalDefinitionEnrichment,
        SignalFilters,
        SignalListing,
        SignalPricingOption,
        SignalRef,
        SignalTargeting,
        SignalTargetingExpression,
        SignalTargetingRules,
        Snapshot,
        SnapshotUnavailableReason,
        SyncAccountsRequest,
        SyncAccountsResponse,
        SyncAgentNotificationConfigsRequest,
        SyncAgentNotificationConfigsResponse,
        SyncAudiencesRequest,
        SyncAudiencesResponse,
        SyncCatalogsInputRequired,
        SyncCatalogsRequest,
        SyncCatalogsResponse,
        SyncCatalogsSubmitted,
        SyncCatalogsWorking,
        SyncCreativesRequest,
        SyncCreativesResponse,
        SyncEventSourcesRequest,
        SyncEventSourcesResponse,
        SyncPlansRequest,
        SyncPlansResponse,
        TargetingOverlay,
        TextContent,
        TimeBasedPricingOption,
        TimeUnit,
        Transform,
        UpdateFrequency,
        UpdateMediaBuyRequest,
        UpdateMediaBuyResponse,
        UrlContent,
        ValidateInputRequest,
        ValidateInputResponse,
        VastAsset,
        VastTrackerAsset,
        VcpmAuctionPricingOption,
        VcpmFixedRatePricingOption,
        VcpmPricingOption,
        VerifyBrandClaimPayload,
        VerifyBrandClaimRequest,
        VerifyBrandClaimResponse,
        VerifyBrandClaimsErrorResponse,
        VerifyBrandClaimSignedResponse,
        VerifyBrandClaimSignedSuccessPayload,
        VerifyBrandClaimsPayload,
        VerifyBrandClaimsRequest,
        VerifyBrandClaimsRequestBulk,
        VerifyBrandClaimsResponse,
        VerifyBrandClaimsResponseBulk,
        VerifyBrandClaimsSignedResponse,
        VerifyBrandClaimsSignedSuccessPayload,
        VideoContent,
        WcagLevel,
        WebhookChallenge,
        WebhookChallengeResponse,
        WebhookContent,
        WholesaleFeedEvent,
        WholesaleFeedWebhook,
        ZipAsset,
        aliases,
    )
    from adcp.types import (
        RegistryAcceptancePolicyProfileReference as RegistryAcceptancePolicyProfileReference,
    )
    from adcp.types import _generated as generated
    from adcp.types.aliases import (
        AccountReferenceById,
        AccountReferenceByNaturalKey,
        AcquireRightsAcquiredResponse,
        AcquireRightsErrorResponse,
        AcquireRightsPendingResponse,
        AcquireRightsRejectedResponse,
        AcquireRightsResponse1,
        ActivateSignalErrorResponse,
        ActivateSignalResponse1,
        ActivateSignalSuccessResponse,
        AgentDeployment,
        AgentDestination,
        AuthorizedAgent,
        AuthorizedAgentsByInlineProperties,
        AuthorizedAgentsByPropertyId,
        AuthorizedAgentsByPropertyTag,
        AuthorizedAgentsByPublisherProperties,
        AuthorizedAgentsBySignalId,
        AuthorizedAgentsBySignalTag,
        BothPreviewRender,
        CalibrateContentErrorResponse,
        CalibrateContentResponse1,
        CalibrateContentSuccessResponse,
        ComplyTestControllerResponse1,
        CreateContentStandardsErrorResponse,
        CreateContentStandardsResponse1,
        CreateContentStandardsSuccessResponse,
        Deployment,
        Destination,
        GetAccountFinancialsErrorResponse,
        GetAccountFinancialsResponse1,
        GetAccountFinancialsSuccessResponse,
        GetBrandIdentityErrorResponse,
        GetBrandIdentityResponse1,
        GetBrandIdentitySuccessResponse,
        GetContentStandardsErrorResponse,
        GetContentStandardsResponse1,
        GetContentStandardsSuccessResponse,
        GetCreativeDeliveryByBuyerRefRequest,
        GetCreativeDeliveryByCreativeRequest,
        GetCreativeDeliveryByMediaBuyRequest,
        GetCreativeFeaturesErrorResponse,
        GetCreativeFeaturesResponse1,
        GetCreativeFeaturesSuccessResponse,
        GetMediaBuyArtifactsErrorResponse,
        GetMediaBuyArtifactsResponse1,
        GetMediaBuyArtifactsSuccessResponse,
        GetProductsBriefRequest,
        GetProductsRefineRequest,
        GetProductsWholesaleRequest,
        GetRightsErrorResponse,
        GetRightsResponse1,
        GetRightsSuccessResponse,
        GetSignalsDiscoveryRequest,
        GetSignalsLookupRequest,
        HtmlPreviewRender,
        InlineDaastAsset,
        InlineVastAsset,
        KeyValueActivationKey,
        ListContentStandardsErrorResponse,
        ListContentStandardsResponse1,
        ListContentStandardsSuccessResponse,
        LogEventErrorResponse,
        LogEventResponse1,
        LogEventSuccessResponse,
        PlatformDeployment,
        PlatformDestination,
        PricingOption,
        PropertyId,
        PropertyTag,
        ProvidePerformanceFeedbackByBuyerRefRequest,
        ProvidePerformanceFeedbackByMediaBuyRequest,
        ProvidePerformanceFeedbackErrorResponse,
        ProvidePerformanceFeedbackResponse1,
        ProvidePerformanceFeedbackSuccessResponse,
        PublisherProperties,
        PublisherPropertiesAll,
        PublisherPropertiesById,
        PublisherPropertiesByTag,
        SegmentIdActivationKey,
        SiSendActionResponseRequest,
        SiSendTextMessageRequest,
        SyncAccountsErrorResponse,
        SyncAccountsResponse1,
        SyncAccountsSuccessResponse,
        SyncAudiencesAudience,
        SyncAudiencesErrorResponse,
        SyncAudiencesResponse1,
        SyncAudiencesSubmittedResponse,
        SyncAudiencesSuccessResponse,
        SyncCatalogResult,
        SyncCatalogsErrorResponse,
        SyncCatalogsResponse1,
        SyncCatalogsSubmittedResponse,
        SyncCatalogsSuccessResponse,
        SyncCreativeResult,
        SyncCreativesErrorResponse,
        SyncCreativesResponse1,
        SyncCreativesResponse3,
        SyncCreativesSubmittedResponse,
        SyncCreativesSuccessResponse,
        SyncEventSourcesErrorResponse,
        SyncEventSourcesResponse1,
        SyncEventSourcesSuccessResponse,
        UpdateContentStandardsErrorResponse,
        UpdateContentStandardsResponse1,
        UpdateContentStandardsSuccessResponse,
        UpdateMediaBuyPackagesRequest,
        UpdateMediaBuyPropertiesRequest,
        UrlDaastAsset,
        UrlPreviewRender,
        UrlVastAsset,
        ValidateContentDeliveryErrorResponse,
        ValidateContentDeliveryResponse1,
        ValidateContentDeliverySuccessResponse,
    )
    from adcp.types.core import (
        AgentConfig,
        Member,
        Policy,
        PolicyExemplar,
        PolicyExemplars,
        PolicyHistory,
        PolicyRevision,
        PolicySummary,
        Protocol,
        ResolvedBrand,
        ResolvedProperty,
        TaskResult,
        TaskStatus,
        WebhookMetadata,
    )
    from adcp.types.guards import is_adcp_error, is_adcp_success  # noqa: F401
    from adcp.types.registry import (
        AgentCapabilities,
        AgentCompliance,
        AgentHealth,
        AgentStats,
        BrandActivity,
        BrandRegistryItem,
        DomainLookupResult,
        FederatedAgentWithDetails,
        FederatedPublisher,
        FeedEvent,
        FeedPage,
        PropertyActivity,
        PropertyIdentifier,
        PropertyRegistryItem,
        PropertySummary,
        ValidationResult,
    )
    from adcp.utils import (
        get_asset_count,
        get_format_assets,
        get_individual_assets,
        get_optional_assets,
        get_repeatable_groups,
        get_required_assets,
        has_assets,
        normalize_assets_required,
        uses_deprecated_assets_field,
    )
    from adcp.validation import (
        SchemaValidationError,
        UnknownFieldPolicy,
        ValidationError,
        ValidationHookConfig,
        ValidationIssue,
        ValidationMode,
        ValidationOutcome,
        validate_adagents,
        validate_agent_authorization,
        validate_product,
        validate_publisher_properties_item,
    )
    from adcp.webhooks import (
        LegacyHmacFallback,
        MemoryBackend,
        PreparedWebhook,
        ScopePermanentlyUnknown,
        ScopeTransientlyUnavailable,
        WebhookChallengeError,
        WebhookChallengeResult,
        WebhookDedupStore,
        WebhookDestinationPolicy,
        WebhookReceiver,
        WebhookReceiverConfig,
        WebhookSender,
        WebhookSenderResolution,
        WebhookSenderResolver,
        WebhookVerifyOptions,
        challenge_webhook_destination,
        create_a2a_webhook_payload,
        create_mcp_webhook_payload,
        create_webhook_challenge_payload,
        extract_webhook_result_data,
        generate_webhook_challenge_value,
        generate_webhook_idempotency_key,
        get_adcp_signed_headers_for_webhook,
        sign_legacy_webhook,
        sign_webhook,
        to_wire_dict,
        validate_webhook_challenge_response,
    )
