# generated by datamodel-codegen:
#   filename:  account/list_account_changes_response.json
#   timestamp: 2026-10-07T15:06:43+00:00

from __future__ import annotations

from adcp.types.base import AdcpResponse, SchemaInt

from adcp.types._str_enum import StrEnum
from typing import Annotated

from adcp.types.base import AdCPBaseModel
from adcp.types._scalar import ScalarStr
from pydantic import AwareDatetime, ConfigDict, Field, StrictBool, model_validator

from ..core import account_change
from ..core import context as context_1
from ..core import error
from ..core import ext as ext_1
from ..core.protocol_envelope import ProtocolEnvelope
from ..core.version_envelope import AdcpVersionEnvelope


from pydantic_core import PydanticCustomError


class Kind(StrEnum):
    seller = 'seller'
    connected_platform = 'connected_platform'


class Status(StrEnum):
    current = 'current'
    delayed = 'delayed'
    unavailable = 'unavailable'
    not_configured = 'not_configured'


class ResourceType(ScalarStr):
    __slots__ = ()
    _constraints = {'max_length': 100, 'min_length': 1, 'pattern': '^[a-z][a-z0-9_.-]{0,99}$'}


class SourceCoverageItem(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    source_id: Annotated[
        str, Field(description='Opaque seller or connection reference.', max_length=255)
    ]
    kind: Kind
    status: Annotated[
        Status,
        Field(
            description='Connector freshness classification. For connected_platform, current means last_successful_sync_at is no older than stale_after_seconds at generated_at and the seller knows of no ingestion gap; delayed means that threshold is exceeded or a gap is known.'
        ),
    ]
    coverage_start: Annotated[
        AwareDatetime | None,
        Field(
            description='Earliest upstream time covered by this source after connection or retention limits.'
        ),
    ] = None
    observed_through: Annotated[
        AwareDatetime | None,
        Field(description='Latest upstream point the seller has successfully observed.'),
    ] = None
    last_successful_sync_at: AwareDatetime | None = None
    stale_after_seconds: Annotated[
        SchemaInt | None,
        Field(
            description='Maximum age of last_successful_sync_at at generated_at for this connected source to self-classify as current. Required by the protocol contract whenever a connected source reports current.',
            ge=1,
            le=2592000,
        ),
    ] = None
    resource_types: Annotated[list[ResourceType], Field(max_length=50)]


class Status22(StrEnum):
    completed = 'completed'
    failed = 'failed'


class ListAccountChangesResponse(AdcpResponse, AdcpVersionEnvelope, ProtocolEnvelope):
    model_config = ConfigDict(
        extra='allow',
    )
    changes: Annotated[
        list[account_change.AccountChange] | None,
        Field(
            description='Matching changes in oldest-first total account order. Timestamps are descriptive and do not define this order.',
            max_length=100,
        ),
    ] = None
    cursor: Annotated[
        str | None,
        Field(
            description='Opaque checkpoint strictly after the high-water scanned by this page. Always persist this value, including when changes is empty or has_more is false. A filtered empty page still advances past scanned nonmatching records.',
            max_length=4096,
            min_length=1,
        ),
    ] = None
    has_more: Annotated[
        StrictBool | None,
        Field(
            description='True when more retained matching changes were available at generation time. False means caught up to seller ingestion, not necessarily to an unavailable or delayed connected source.'
        ),
    ] = None
    available_since: Annotated[
        AwareDatetime | None,
        Field(
            description='Oldest time for which the seller currently retains change records for this account and caller. The capability guarantees at least 90 days after adoption; pre-adoption history is not fabricated.'
        ),
    ] = None
    generated_at: Annotated[
        AwareDatetime | None,
        Field(
            description='Seller time when this page and its source-coverage watermarks were generated.'
        ),
    ] = None
    source_coverage: Annotated[
        list[SourceCoverageItem] | None,
        Field(
            description='Account-specific feed and connector coverage. Buyers use this to distinguish feed catch-up from upstream freshness. Omission means no additional connected-source coverage is declared.',
            max_length=50,
        ),
    ] = None
    errors: list[error.Error] | None = None
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None
    status: Status22

    @model_validator(mode='after')
    def _require_schema_required_group(self) -> ListAccountChangesResponse:
        # ``required`` asks whether the caller supplied the field, which is what
        # model_fields_set answers. An explicit null is a supplied value — on a
        # mutation input it is the command to clear — and a default the caller
        # never sent is not.
        for group in (('status', 'changes', 'cursor', 'has_more', 'available_since', 'generated_at'), ('status', 'adcp_error', 'errors'),):
            if all(name in self.model_fields_set for name in group):
                return self
        # The refusal names the root combinator the groups came from, so a
        # consumer reads the keyword off ``e.errors()[0]["type"]``.
        raise PydanticCustomError(
            'oneOf',
            'ListAccountChangesResponse requires at least one of these field groups: status+changes+cursor+has_more+available_since+generated_at | status+adcp_error+errors',
        )
