# generated by datamodel-codegen:
#   filename:  enums/adcp_domain.json
#   timestamp: 2026-02-12T02:11:19+00:00

from __future__ import annotations

from enum import Enum


class AdcpDomain(Enum):
    media_buy = 'media-buy'
    signals = 'signals'
    governance = 'governance'
    creative = 'creative'
