# generated by datamodel-codegen:
#   filename:  enums/audience_subject_type.json
#   timestamp: 2026-08-17T23:02:13+00:00

from __future__ import annotations

from adcp.types._str_enum import StrEnum


class AudienceSubjectType(StrEnum):
    individual = 'individual'
    household = 'household'
    business = 'business'
    contextual = 'contextual'
    none = 'none'
