# generated by datamodel-codegen:
#   filename:  enums/catalog_action.json
#   timestamp: 2026-05-02T19:36:29+00:00

from __future__ import annotations

from enum import Enum


class CatalogAction(Enum):
    created = 'created'
    updated = 'updated'
    unchanged = 'unchanged'
    failed = 'failed'
    deleted = 'deleted'
