# generated by datamodel-codegen:
#   filename:  enums/catalog_item_status.json
#   timestamp: 2026-05-22T13:15:12+00:00

from __future__ import annotations

from adcp.types._str_enum import StrEnum


class CatalogItemStatus(StrEnum):
    approved = 'approved'
    pending = 'pending'
    rejected = 'rejected'
    warning = 'warning'
    withdrawn = 'withdrawn'
