# generated by datamodel-codegen:
#   filename:  enums/co_branding_requirement.json
#   timestamp: 2026-05-02T19:36:29+00:00

from __future__ import annotations

from adcp.types._str_enum import StrEnum


class CoBrandingRequirement(StrEnum):
    required = 'required'
    optional = 'optional'
    none = 'none'
