# generated by datamodel-codegen:
#   filename:  enums/demographic_system.json
#   timestamp: 2026-04-29T01:11:23+00:00

from __future__ import annotations

from enum import Enum


class DemographicSystem(Enum):
    nielsen = "nielsen"
    barb = "barb"
    agf = "agf"
    oztam = "oztam"
    mediametrie = "mediametrie"
    custom = "custom"
