# generated by datamodel-codegen:
#   filename:  enums/device_platform.json
#   timestamp: 2026-05-02T19:36:29+00:00

from __future__ import annotations

from adcp.types._str_enum import StrEnum


class DevicePlatform(StrEnum):
    ios = 'ios'
    android = 'android'
    windows = 'windows'
    macos = 'macos'
    linux = 'linux'
    chromeos = 'chromeos'
    tvos = 'tvos'
    tizen = 'tizen'
    webos = 'webos'
    fire_os = 'fire_os'
    roku_os = 'roku_os'
    unknown = 'unknown'
