# generated by datamodel-codegen:
#   filename:  enums/distance_unit.json
#   timestamp: 2026-02-22T00:26:42+00:00

from __future__ import annotations

from enum import Enum


class DistanceUnit(Enum):
    km = 'km'
    mi = 'mi'
    m = 'm'
