# generated by datamodel-codegen:
#   filename:  enums/frame_rate_type.json
#   timestamp: 2026-05-02T19:36:29+00:00

from __future__ import annotations

from adcp.types._str_enum import StrEnum


class FrameRateType(StrEnum):
    constant = 'constant'
    variable = 'variable'
