# generated by datamodel-codegen:
#   filename:  enums/geo_level.json
#   timestamp: 2026-05-02T19:36:29+00:00

from __future__ import annotations

from enum import Enum


class GeographicTargetingLevel(Enum):
    country = 'country'
    region = 'region'
    metro = 'metro'
    postal_area = 'postal_area'
