# generated by datamodel-codegen:
#   filename:  enums/legacy_postal_system.json
#   timestamp: 2026-08-17T23:02:13+00:00

from __future__ import annotations

from adcp.types._str_enum import StrEnum


class CountryFusedPostalCodeSystem(StrEnum):
    us_zip = 'us_zip'
    us_zip_plus_four = 'us_zip_plus_four'
    gb_outward = 'gb_outward'
    gb_full = 'gb_full'
    ca_fsa = 'ca_fsa'
    ca_full = 'ca_full'
    de_plz = 'de_plz'
    fr_code_postal = 'fr_code_postal'
    au_postcode = 'au_postcode'
    ch_plz = 'ch_plz'
    at_plz = 'at_plz'
