# generated by datamodel-codegen:
#   filename:  enums/media_buy_action_mode.json
#   timestamp: 2026-08-28T20:03:29+00:00

from __future__ import annotations

from adcp.types._str_enum import StrEnum


class MediaBuyActionMode(StrEnum):
    self_serve = 'self_serve'
    conditional_self_serve = 'conditional_self_serve'
    seller_managed = 'seller_managed'
    requires_approval = 'requires_approval'
