# generated by datamodel-codegen:
#   filename:  enums/promoted_offerings_requirement.json
#   timestamp: 2026-02-18T17:56:28+00:00

from __future__ import annotations

from enum import Enum


class PromotedOfferingsRequirement(Enum):
    si_agent_url = 'si_agent_url'
    offerings = 'offerings'
    brand_logos = 'brand.logos'
    brand_colors = 'brand.colors'
    brand_tone = 'brand.tone'
    brand_assets = 'brand.assets'
    brand_product_catalog = 'brand.product_catalog'
