# generated by datamodel-codegen:
#   filename:  enums/snapshot_unavailable_reason.json
#   timestamp: 2026-05-02T19:36:29+00:00

from __future__ import annotations

from adcp.types._str_enum import StrEnum


class SnapshotUnavailableReason(StrEnum):
    SNAPSHOT_UNSUPPORTED = 'SNAPSHOT_UNSUPPORTED'
    SNAPSHOT_TEMPORARILY_UNAVAILABLE = 'SNAPSHOT_TEMPORARILY_UNAVAILABLE'
    SNAPSHOT_PERMISSION_DENIED = 'SNAPSHOT_PERMISSION_DENIED'
