# generated by datamodel-codegen:
#   filename:  enums/webhook_response_type.json
#   timestamp: 2026-05-02T19:36:29+00:00

from __future__ import annotations

from adcp.types._str_enum import StrEnum


class WebhookResponseType(StrEnum):
    html = 'html'
    json = 'json'
    xml = 'xml'
    javascript = 'javascript'
