# generated by datamodel-codegen:
#   filename:  property/property_list.json
#   timestamp: 2026-04-29T01:11:23+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import AnyUrl, AwareDatetime, ConfigDict, Field

from ..core import account_ref, brand_ref, vendor_pricing_option
from . import base_property_source, property_list_filters


class PropertyList(AdCPBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    list_id: Annotated[str, Field(description="Unique identifier for this property list")]
    name: Annotated[str, Field(description="Human-readable name for the list")]
    description: Annotated[str | None, Field(description="Description of the list's purpose")] = (
        None
    )
    account: Annotated[
        account_ref.AccountReference | None,
        Field(
            description="Account that owns this list. Returned as account_id form (seller-assigned identifier)."
        ),
    ] = None
    base_properties: Annotated[
        list[base_property_source.BasePropertySource] | None,
        Field(
            description="Array of property sources to evaluate. Each entry is a discriminated union: publisher_tags (publisher_domain + tags), publisher_ids (publisher_domain + property_ids), or identifiers (direct identifiers). If omitted, queries the agent's entire property database."
        ),
    ] = None
    filters: Annotated[
        property_list_filters.PropertyListFilters | None,
        Field(description="Dynamic filters applied when resolving the list"),
    ] = None
    brand: Annotated[
        brand_ref.BrandReference | None,
        Field(
            description="Brand reference used to automatically apply appropriate rules. Resolved to full brand identity at execution time."
        ),
    ] = None
    webhook_url: Annotated[
        AnyUrl | None,
        Field(description="URL to receive notifications when the resolved list changes"),
    ] = None
    cache_duration_hours: Annotated[
        int | None,
        Field(
            description="Recommended cache duration for resolved list. Consumers should re-fetch after this period.",
            ge=1,
        ),
    ] = 24
    created_at: Annotated[AwareDatetime | None, Field(description="When the list was created")] = (
        None
    )
    updated_at: Annotated[
        AwareDatetime | None, Field(description="When the list was last modified")
    ] = None
    property_count: Annotated[
        int | None,
        Field(description="Number of properties in the resolved list (at time of last resolution)"),
    ] = None
    pricing_options: Annotated[
        list[vendor_pricing_option.VendorPricingOption] | None,
        Field(
            description="Pricing options for this property list. Present when the requesting account has a billing relationship with the list provider. The buyer passes the selected pricing_option_id in report_usage.",
            min_length=1,
        ),
    ] = None
