# generated by datamodel-codegen:
#   filename:  protocol/get_principal_request.json
#   timestamp: 2026-09-01T19:37:00+00:00

from __future__ import annotations

from pydantic import ConfigDict

from ..core import context as context_1
from ..core import ext as ext_1
from ..core.version_envelope import AdcpVersionEnvelope


class GetPrincipalRequest(AdcpVersionEnvelope):
    model_config = ConfigDict(
        extra='allow',
    )
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None
