# generated by datamodel-codegen:
#   filename:  governance/sync_plans_response.json
#   timestamp: 2026-04-03T18:37:00+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field

from ..enums import policy_enforcement


class Status(Enum):
    active = 'active'
    inactive = 'inactive'


class Category(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    category_id: Annotated[str, Field(description='Validation category identifier.')]
    status: Annotated[Status, Field(description='Whether this category is active for this plan.')]


class Source(Enum):
    explicit = 'explicit'
    auto_applied = 'auto_applied'


class ResolvedPolicy(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    enforcement: Annotated[
        policy_enforcement.PolicyEnforcementLevel,
        Field(description='Enforcement level for this policy.'),
    ]
    policy_id: Annotated[str, Field(description='Registry policy ID.')]
    reason: Annotated[
        str | None,
        Field(
            description="Why this policy was included (e.g., 'Matched jurisdiction US and policy category pharmaceutical_advertising')."
        ),
    ] = None
    source: Annotated[
        Source,
        Field(
            description="How this policy was included. 'explicit': referenced in the brand compliance configuration. 'auto_applied': matched automatically by jurisdiction or policy category."
        ),
    ]


class Status15(Enum):
    active = 'active'
    error = 'error'


class Plan(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    categories: Annotated[
        list[Category] | None, Field(description='Validation categories active for this plan.')
    ] = None
    plan_id: Annotated[str, Field(description='Plan identifier.')]
    resolved_policies: Annotated[
        list[ResolvedPolicy] | None,
        Field(
            description='Policies the governance agent will enforce for this plan. Includes explicitly referenced policies from the brand compliance configuration and auto-applied policies matched by jurisdiction or policy category. Present when the governance agent supports policy resolution.'
        ),
    ] = None
    status: Annotated[
        Status15,
        Field(
            description="Sync result status. 'active' means sync succeeded; 'error' means sync failed."
        ),
    ]
    version: Annotated[int, Field(description='Plan version (increments on each sync).')]


class SyncPlansResponse(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    plans: Annotated[list[Plan], Field(description='Status for each synced plan.')]
