# generated by datamodel-codegen:
#   filename:  sponsored_intelligence/si_send_message_request.json
#   timestamp: 2026-04-03T18:37:00+00:00

from __future__ import annotations

from typing import Annotated, Any

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field

from ..core import ext as ext_1


class ActionResponse(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    action: Annotated[str | None, Field(description='The action that was triggered')] = None
    payload: Annotated[
        dict[str, Any] | None, Field(description='Action-specific response data')
    ] = None


class SiSendMessageRequest(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    action_response: Annotated[
        ActionResponse | None,
        Field(description='Response to a previous action_button (e.g., user clicked checkout)'),
    ] = None
    ext: ext_1.ExtensionObject | None = None
    message: Annotated[str | None, Field(description="User's message to the brand agent")] = None
    session_id: Annotated[str, Field(description='Active session identifier')]
