# generated by datamodel-codegen:
#   filename:  sponsored_intelligence/si_send_message_response.json
#   timestamp: 2026-05-02T19:36:29+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field

from ..a2ui import surface as surface_1
from ..core import context as context_1
from ..core import error
from ..core import ext as ext_1
from ..enums import si_session_status
from . import si_ui_element


class Type(Enum):
    transaction = 'transaction'
    complete = 'complete'


class Price(AdCPBaseModel):
    amount: float | None = None
    currency: str | None = None


class Intent(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    action: Annotated[str | None, Field(description="The commerce action (e.g., 'purchase')")] = (
        None
    )
    product: Annotated[dict[str, Any] | None, Field(description='Product details for checkout')] = (
        None
    )
    price: Annotated[Price | None, Field(description='Price information')] = None


class ContextForCheckout(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    conversation_summary: Annotated[
        str | None, Field(description='Summary of the conversation leading to purchase')
    ] = None
    applied_offers: Annotated[
        list[str] | None, Field(description='Offer IDs that were applied during the conversation')
    ] = None


class Handoff(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Annotated[
        Type | None,
        Field(
            description='Type of handoff: transaction (ready for ACP checkout) or complete (conversation done)'
        ),
    ] = None
    intent: Annotated[
        Intent | None,
        Field(description='For transaction handoffs: what the user wants to purchase'),
    ] = None
    context_for_checkout: Annotated[
        ContextForCheckout | None, Field(description='Context to pass to ACP for seamless checkout')
    ] = None


class Response(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    message: Annotated[str | None, Field(description='Conversational message from brand agent')] = (
        None
    )
    surface: Annotated[
        surface_1.A2UiSurface | None, Field(description='A2UI surface with interactive components')
    ] = None
    ui_elements: Annotated[
        list[si_ui_element.SiUiElement] | None,
        Field(
            deprecated=True,
            description='Visual components to render (DEPRECATED: use surface instead)',
        ),
    ] = None


class SiSendMessageResponse(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    session_id: Annotated[str, Field(description='Session identifier')]
    response: Annotated[Response | None, Field(description="Brand agent's response")] = None
    mcp_resource_uri: Annotated[
        str | None,
        Field(
            description='MCP resource URI for hosts with MCP Apps support (e.g., ui://si/session-abc123)'
        ),
    ] = None
    session_status: Annotated[
        si_session_status.SiSessionStatus,
        Field(
            description='Current session status. On a successful response, one of: active, pending_handoff, or complete. Terminated sessions return error codes (SESSION_NOT_FOUND or SESSION_TERMINATED) instead of a success response.'
        ),
    ]
    handoff: Annotated[
        Handoff | None, Field(description='Handoff request when session_status is pending_handoff')
    ] = None
    errors: list[error.Error] | None = None
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None
