"""Types declared by the AdCP ``core/registry_event`` schema.

One public module per schema, so a type name its own domain declares
more than once is still unambiguous:

    from adcp.types.domains.core.registry_event import <Type>

Auto-generated from the generated_poc module tree. DO NOT EDIT MANUALLY.
Generation date: 2026-10-03 13:36:32 UTC
"""

# ruff: noqa: E501, I001
from __future__ import annotations

from adcp.types.generated_poc.core.registry_event import (
    AgentProfilePayload,
    AuthorizationPayload,
    AuthorizationType,
    BadgeRole,
    ChangedFields,
    Classification,
    CollectionIdentifier,
    CollectionPayload,
    CompliancePayload,
    ComplianceStatus,
    Countries,
    Country,
    DelegationType,
    Domain,
    EntityType,
    EventType,
    Evidence,
    GradingProfile,
    Market,
    Payload,
    Payload1,
    Payload10,
    Payload11,
    Payload12,
    Payload13,
    Payload14,
    Payload2,
    Payload3,
    Payload4,
    Payload5,
    Payload6,
    Payload7,
    Payload8,
    Payload9,
    PropertyPayload,
    PropertySource,
    PublisherAdagentsPayload,
    RegistryEvent,
    RegistryEvent1,
    RegistryEvent10,
    RegistryEvent11,
    RegistryEvent12,
    RegistryEvent13,
    RegistryEvent14,
    RegistryEvent15,
    RegistryEvent16,
    RegistryEvent17,
    RegistryEvent18,
    RegistryEvent19,
    RegistryEvent2,
    RegistryEvent20,
    RegistryEvent3,
    RegistryEvent4,
    RegistryEvent5,
    RegistryEvent6,
    RegistryEvent7,
    RegistryEvent8,
    RegistryEvent9,
    Status,
    Storyboard,
    StoryboardStatus,
    StringArray,
    Tracks,
    Type,
)

# Explicit exports
__all__ = [
    "AgentProfilePayload",
    "AuthorizationPayload",
    "AuthorizationType",
    "BadgeRole",
    "ChangedFields",
    "Classification",
    "CollectionIdentifier",
    "CollectionPayload",
    "CompliancePayload",
    "ComplianceStatus",
    "Countries",
    "Country",
    "DelegationType",
    "Domain",
    "EntityType",
    "EventType",
    "Evidence",
    "GradingProfile",
    "Market",
    "Payload",
    "Payload1",
    "Payload10",
    "Payload11",
    "Payload12",
    "Payload13",
    "Payload14",
    "Payload2",
    "Payload3",
    "Payload4",
    "Payload5",
    "Payload6",
    "Payload7",
    "Payload8",
    "Payload9",
    "PropertyPayload",
    "PropertySource",
    "PublisherAdagentsPayload",
    "RegistryEvent",
    "RegistryEvent1",
    "RegistryEvent10",
    "RegistryEvent11",
    "RegistryEvent12",
    "RegistryEvent13",
    "RegistryEvent14",
    "RegistryEvent15",
    "RegistryEvent16",
    "RegistryEvent17",
    "RegistryEvent18",
    "RegistryEvent19",
    "RegistryEvent2",
    "RegistryEvent20",
    "RegistryEvent3",
    "RegistryEvent4",
    "RegistryEvent5",
    "RegistryEvent6",
    "RegistryEvent7",
    "RegistryEvent8",
    "RegistryEvent9",
    "Status",
    "Storyboard",
    "StoryboardStatus",
    "StringArray",
    "Tracks",
    "Type",
]
