# generated by datamodel-codegen:
#   filename:  media_buy/sync_reporting_receipts_request.json
#   timestamp: 2026-10-07T15:06:43+00:00

from __future__ import annotations

from adcp.types.base import AdcpRequest, SchemaInt

from typing import Annotated

from pydantic import ConfigDict, Field, model_validator

from ..core import canonical_account_ref
from ..core import context as context_1
from ..core import ext as ext_1
from ..core import reporting_adjustment_receipt, reporting_receipt
from ..core.version_envelope import AdcpVersionEnvelope


from pydantic_core import PydanticCustomError


class SyncReportingReceiptsRequest(AdcpRequest, AdcpVersionEnvelope):
    model_config = ConfigDict(
        extra='allow',
    )
    adcp_version: Annotated[
        str | None,
        Field(
            description='Release-precision AdCP version (VERSION.RELEASE, e.g. "3.0", "3.1", "3.1-beta"). On a request: the buyer\'s release pin — the seller validates against its supported_versions and returns VERSION_UNSUPPORTED on cross-major mismatch, or downshifts to the highest supported release within the same major. On a response: the release the seller actually served — clients SHOULD validate the response against that release\'s schema, not against their pin. Patches are not negotiated; surface them as build_version on capabilities for operational visibility. When omitted, falls back to adcp_major_version (deprecated) or server default. Buyers SHOULD emit both adcp_version and adcp_major_version through 3.x to remain compatible with sellers that only read the legacy field. NORMALIZATION: SDKs that read full-semver values from bundle metadata (e.g. ComplianceIndex.published_version = "3.1.0-beta.1") MUST normalize to release-precision ("3.1-beta.1") before emitting on the wire — meta-field values are NOT valid wire values.',
            examples=['3.0', '3.1', '3.1-beta', '3.1-rc.1'],
            pattern='^(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)(?:-[a-zA-Z0-9](?:[a-zA-Z0-9.-]*[a-zA-Z0-9])?)?$',
        ),
    ] = None
    adcp_major_version: Annotated[
        SchemaInt | None,
        Field(
            deprecated=True,
            description="DEPRECATED in favor of adcp_version (release-precision string). Servers MUST continue to honor this field through 3.x. Removed in 4.0. Original semantics: the AdCP major version the buyer's payloads conform to. Sellers validate against their supported major_versions and return VERSION_UNSUPPORTED if unsupported. When omitted, the seller assumes its highest supported version.",
            ge=1,
            le=99,
        ),
    ] = None
    account: canonical_account_ref.CanonicalAccountReference
    idempotency_key: Annotated[
        str,
        Field(
            description='Client-generated batch key. Exact retries reuse the key and body.',
            max_length=255,
            min_length=16,
            pattern='^[A-Za-z0-9_.:-]{16,255}$',
        ),
    ]
    receipts: Annotated[
        list[reporting_receipt.ReportingReceipt] | None, Field(max_length=100, min_length=1)
    ] = None
    adjustment_receipts: Annotated[
        list[reporting_adjustment_receipt.ReportingAdjustmentReceipt] | None,
        Field(
            description='Consumer acceptance or rejection of exact post-official adjustments.',
            max_length=100,
            min_length=1,
        ),
    ] = None
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None

    @model_validator(mode='after')
    def _require_schema_required_group(self) -> SyncReportingReceiptsRequest:
        # ``required`` asks whether the caller supplied the field, which is what
        # model_fields_set answers. An explicit null is a supplied value — on a
        # mutation input it is the command to clear — and a default the caller
        # never sent is not.
        for group in (('receipts',), ('adjustment_receipts',),):
            if all(name in self.model_fields_set for name in group):
                return self
        # The refusal names the root combinator the groups came from, so a
        # consumer reads the keyword off ``e.errors()[0]["type"]``.
        raise PydanticCustomError(
            'anyOf',
            'SyncReportingReceiptsRequest requires at least one of these field groups: receipts | adjustment_receipts',
        )
