# generated by datamodel-codegen:
#   filename:  core/applicable_package_id.json
#   timestamp: 2026-09-14T14:16:02+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel


class ApplicablePackageId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='A package identifier to which a package-scoped media-buy action currently applies.',
            min_length=1,
            title='Applicable Package ID',
        ),
    ]
