# generated by datamodel-codegen:
#   filename:  core/brand_ref.json
#   timestamp: 2026-02-12T02:11:19+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field

from . import brand_id as brand_id_1


class BrandReference(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    brand_id: Annotated[
        brand_id_1.BrandId, Field(description='Brand identifier within the house portfolio')
    ]
    house: Annotated[
        str,
        Field(
            description="Domain where the house's brand.json is hosted (e.g., 'pg.com', 'nikeinc.com')",
            pattern='^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$',
        ),
    ]
