# generated by datamodel-codegen:
#   filename:  core/canonical_audience_evidence_selection.json
#   timestamp: 2026-08-17T23:02:13+00:00

from __future__ import annotations

from adcp.types._str_enum import StrEnum
from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field, RootModel

from . import canonical_audience_evidence
from . import ext as ext_1


class DecisionUse(StrEnum):
    recommendation = 'recommendation'
    eligibility = 'eligibility'
    package_construction = 'package_construction'


class VerifiedAttestationDigest(RootModel[str]):
    root: Annotated[str, Field(pattern='^sha256:[a-f0-9]{64}$')]


class CanonicalAudienceEvidenceSelection(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    evidence_id: Annotated[str, Field(min_length=1)]
    snapshot_id: Annotated[str, Field(min_length=1)]
    version: Annotated[str, Field(min_length=1)]
    content_digest: Annotated[str, Field(pattern='^sha256:[a-f0-9]{64}$')]
    decision_use: DecisionUse
    evidence: canonical_audience_evidence.CanonicalAudienceEvidence | None = None
    verified_attestation_digests: Annotated[
        list[VerifiedAttestationDigest] | None, Field(min_length=1)
    ] = None
    ext: ext_1.ExtensionObject | None = None
