# generated by datamodel-codegen:
#   filename:  core/education_item.json
#   timestamp: 2026-05-22T13:15:12+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import AnyUrl, ConfigDict, Field

from . import ext as ext_1
from . import offering_asset_group
from . import price as price_1


class DegreeType(Enum):
    certificate = 'certificate'
    associate = 'associate'
    bachelor = 'bachelor'
    master = 'master'
    doctorate = 'doctorate'
    professional = 'professional'
    bootcamp = 'bootcamp'


class Level(Enum):
    beginner = 'beginner'
    intermediate = 'intermediate'
    advanced = 'advanced'


class Modality(Enum):
    online = 'online'
    in_person = 'in_person'
    hybrid = 'hybrid'


class EducationItem(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    program_id: Annotated[str, Field(description='Unique identifier for this program or course.')]
    name: Annotated[
        str,
        Field(
            description="Program or course name (e.g., 'MSc Computer Science', 'Digital Marketing Certificate')."
        ),
    ]
    school: Annotated[str, Field(description='Institution or provider name.')]
    description: Annotated[
        str | None,
        Field(description='Program description including curriculum highlights and outcomes.'),
    ] = None
    subject: Annotated[
        str | None,
        Field(
            description="Subject area or field of study (e.g., 'computer-science', 'business', 'healthcare')."
        ),
    ] = None
    degree_type: Annotated[DegreeType | None, Field(description='Type of credential awarded.')] = (
        None
    )
    level: Annotated[Level | None, Field(description='Difficulty or prerequisite level.')] = None
    price: Annotated[price_1.Price | None, Field(description='Tuition or course fee.')] = None
    duration: Annotated[
        str | None,
        Field(
            description="Program duration as a human-readable string (e.g., '4 weeks', '2 years', '6 months')."
        ),
    ] = None
    start_date: Annotated[
        date | None, Field(description='Next available start date (ISO 8601 date).')
    ] = None
    language: Annotated[
        str | None, Field(description="Language of instruction (e.g., 'en', 'nl', 'es').")
    ] = None
    modality: Annotated[Modality | None, Field(description='Delivery format.')] = None
    location: Annotated[
        str | None,
        Field(
            description="Campus or instruction location (e.g., 'Amsterdam, NL'). Omit for fully online programs."
        ),
    ] = None
    image_url: Annotated[AnyUrl | None, Field(description='Program or institution image URL.')] = (
        None
    )
    url: Annotated[AnyUrl | None, Field(description='Program landing page or enrollment URL.')] = (
        None
    )
    tags: Annotated[
        list[str] | None,
        Field(
            description="Tags for filtering (e.g., 'stem', 'scholarship-available', 'evening-classes').",
            min_length=1,
        ),
    ] = None
    assets: Annotated[
        list[offering_asset_group.OfferingAssetGroup] | None,
        Field(
            description="Typed creative asset pools for this program. Uses the same OfferingAssetGroup structure as offering-type catalogs. Standard group IDs: 'images_landscape' (campus/program hero), 'images_vertical' (9:16 for Stories), 'logo' (institution logo). Enables formats to declare typed image requirements that map unambiguously to the right asset regardless of platform.",
            min_length=1,
        ),
    ] = None
    ext: ext_1.ExtensionObject | None = None
