# generated by datamodel-codegen:
#   filename:  core/frequency_cap_impression_constraints.json
#   timestamp: 2026-09-14T14:16:02+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field, RootModel

from . import ext as ext_1


class AllowedValue(RootModel[int]):
    root: Annotated[int, Field(ge=1)]


class FrequencyCapImpressionConstraints(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    minimum: Annotated[int | None, Field(ge=1)] = None
    maximum: Annotated[int | None, Field(ge=1)] = None
    allowed_values: Annotated[list[AllowedValue] | None, Field(min_length=1)] = None
    ext: ext_1.ExtensionObject | None = None
