# generated by datamodel-codegen:
#   filename:  core/media_buy_available_action_id.json
#   timestamp: 2026-10-02T23:18:44+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import Field

from ..enums import media_buy_valid_action


MediaBuyAvailableActionId = Annotated[
    media_buy_valid_action.MediaBuyValidAction | Literal['update_media_buy_frequency_cap'],
    Field(
        description='An action identifier for the structured available_actions surface. It contains every legacy valid_actions value plus structured-only actions introduced after that deprecated flat surface.',
        title='Media Buy Available Action ID',
    ),
]
