# generated by datamodel-codegen:
#   filename:  core/media_buy_legacy_terms_ref.json
#   timestamp: 2026-10-02T13:37:43+00:00

from __future__ import annotations

from adcp.types._scalar import ScalarStr


class MediaBuyTermsReference(ScalarStr):
    __slots__ = ()
    _json_schema_extra = {
        'description': 'Deprecated 3.1 opaque commercial-terms pointer. A 3.2 compatibility projection MAY echo change_term_id here for older buyers, but new buyers MUST prefer change_term_id and MUST NOT assume an arbitrary 3.1 value identifies an accepted change term.',
        'title': 'Media Buy Terms Reference',
    }
