# generated by datamodel-codegen:
#   filename:  core/missing_metric.json
#   timestamp: 2026-06-01T00:32:59+00:00

from __future__ import annotations

from typing import Any, Annotated, Literal

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field, RootModel

from ..enums import attribution_methodology as attribution_methodology_1
from ..enums import available_metric
from ..enums import completion_source as completion_source_1
from ..enums import lift_dimension as lift_dimension_1
from ..enums import viewability_standard as viewability_standard_1
from . import brand_ref, duration, vendor_metric_id


class Qualifier(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    viewability_standard: viewability_standard_1.ViewabilityStandard | None = None
    completion_source: completion_source_1.CompletionSource | None = None
    attribution_methodology: attribution_methodology_1.AttributionMethodology | None = None
    attribution_window: duration.Duration | None = None
    lift_dimension: lift_dimension_1.LiftDimension | None = None


class MissingMetric1(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    scope: Literal['standard'] = 'standard'
    metric_id: available_metric.AvailableMetric
    qualifier: Annotated[
        Qualifier | None,
        Field(
            description='Mirrors the qualifier on `committed_metrics` so the missing entry preserves the contract distinction (e.g., flagging MRC viewability as missing when only GroupM was reported, vendor-attested completion as missing when only seller-attested was reported, or deterministic_purchase attribution as missing when only probabilistic was reported). MUST match the qualifier on the corresponding `committed_metrics` entry the missing flag refers to.'
        ),
    ] = None


class MissingMetric2(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    scope: Literal['vendor'] = 'vendor'
    vendor: brand_ref.BrandReference
    metric_id: vendor_metric_id.VendorMetricId


class MissingMetric(RootModel[MissingMetric1 | MissingMetric2]):
    root: Annotated[
        MissingMetric1 | MissingMetric2,
        Field(
            description='One metric the binding reporting contract declared but that is not populated in a delivery report. Symmetric with `committed_metrics` and discriminated by `scope`.',
            discriminator='scope',
            title='Missing Metric',
        ),
    ]
    def __getattr__(self, name: str) -> Any:
        """Proxy attribute access to the wrapped type."""
        if name.startswith('_'):
            raise AttributeError(name)
        return getattr(self.root, name)
