# generated by datamodel-codegen:
#   filename:  core/package_delivery_metric_value.json
#   timestamp: 2026-09-05T11:09:57+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field

from ..enums import attribution_methodology as attribution_methodology_1
from ..enums import completion_source as completion_source_1
from ..enums import lift_dimension as lift_dimension_1
from ..enums import viewability_standard as viewability_standard_1
from . import duration
from .delivery_metric_aggregate import Field0


class Qualifier(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    viewability_standard: Annotated[
        viewability_standard_1.ViewabilityStandard | None,
        Field(
            description='Viewability standard under which this row was measured. MRC and GroupM define materially different thresholds; never sum across standards.'
        ),
    ] = None
    completion_source: Annotated[
        completion_source_1.CompletionSource | None,
        Field(
            description='Source of `completion_rate` attestation for this row — `seller_attested` from player/ad server, `vendor_attested` from a third-party measurement vendor. The two paths can yield different rates; never sum across sources.'
        ),
    ] = None
    attribution_methodology: Annotated[
        attribution_methodology_1.AttributionMethodology | None,
        Field(
            description='Attribution methodology under which this outcome row was computed (`deterministic_purchase`, `probabilistic`, `panel_based`, `modeled`). Outcome metrics measured under different methodologies represent materially different numbers; never sum across methodologies.'
        ),
    ] = None
    attribution_window: Annotated[
        duration.Duration | None,
        Field(
            description="Attribution window for this outcome row. Object-valued duration (`{interval, unit}`), not a shorthand string. Outcome metrics measured over different windows represent the same metric over different time periods; the partition keeps them as separate rows so buyers don't accidentally aggregate."
        ),
    ] = None
    lift_dimension: Annotated[
        lift_dimension_1.LiftDimension | None,
        Field(
            description='Brand-lift dimension this row represents (awareness, consideration, favorability, purchase intent, or ad recall). Required when `metric_id` is `brand_lift`. Each dimension is a separate surveyed outcome with its own sample size and confidence interval; never sum across dimensions.'
        ),
    ] = None


class PackageDeliveryMetricValue(Field0):
    qualifier: Annotated[
        Qualifier,
        Field(
            description="Qualifier keys disambiguating this row from sibling rows under the same `metric_id`. Symmetric with `committed_metrics.qualifier` today; expected to diverge in future minors as transparency disclosures buyers don't commit to ship delivery-only. Closed (`additionalProperties: false`) — new qualifier keys ship explicitly."
        ),
    ]
