# generated by datamodel-codegen:
#   filename:  core/product_offer_filters.json
#   timestamp: 2026-08-21T04:35:18+00:00

from __future__ import annotations

from datetime import date
from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import AnyUrl, AwareDatetime, ConfigDict, Field, RootModel

from ..enums import audio_distribution_type, available_metric
from ..enums import channels as channels_1
from ..enums import delivery_type as delivery_type_1
from ..enums import exclusivity as exclusivity_1
from ..enums import (
    performance_standard_metric,
    pricing_structure,
    response_type,
    social_placement_surface,
    sponsored_placement_type,
    video_placement_type,
    viewability_standard,
)
from . import brand_key
from . import budget_range as budget_range_1
from . import canonical_format_kind, canonical_media_buy_features
from . import ext as ext_1
from . import (
    format_option_ref,
    product_audience_evidence_requirements,
    property_list_ref,
    vendor_metric_id,
)


class PricingCurrency(RootModel[str]):
    root: Annotated[str, Field(pattern='^[A-Z]{3}$')]


class AvailabilityHorizon(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    start_time: Annotated[
        AwareDatetime,
        Field(description='Inclusive horizon start (RFC 3339 date-time with timezone offset).'),
    ]
    end_time: Annotated[
        AwareDatetime,
        Field(
            description='Exclusive horizon end (RFC 3339 date-time with timezone offset). MUST be after start_time.'
        ),
    ]


class Country(RootModel[str]):
    root: Annotated[str, Field(pattern='^[A-Z]{2}$')]


class Provider(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    agent_url: AnyUrl
    context_match: bool | None = None
    identity_match: bool | None = None


class TrustedMatch(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    providers: Annotated[list[Provider] | None, Field(min_length=1)] = None
    response_types: Annotated[list[response_type.TmpResponseType] | None, Field(min_length=1)] = (
        None
    )


class RequiredPerformanceStandard(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    metric: performance_standard_metric.PerformanceStandardMetric
    threshold: Annotated[float, Field(ge=0.0, le=1.0)]
    standard: viewability_standard.ViewabilityStandard | None = None
    vendor: brand_key.BrandKey


class RequiredVendorMetric(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    vendor: brand_key.BrandKey | None = None
    metric_id: vendor_metric_id.VendorMetricId | None = None


class ProductOfferFilters(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    delivery_type: delivery_type_1.DeliveryType | None = None
    exclusivity: exclusivity_1.Exclusivity | None = None
    is_fixed_price: Annotated[
        bool | None,
        Field(
            description='Filter fixed-price versus auction offers. Contingent pricing matches neither value.'
        ),
    ] = None
    pricing_structures: Annotated[
        list[pricing_structure.PricingStructure] | None, Field(min_length=1)
    ] = None
    pricing_currencies: Annotated[list[PricingCurrency] | None, Field(min_length=1)] = None
    format_kinds: Annotated[
        list[canonical_format_kind.CanonicalFormatKind] | None, Field(min_length=1)
    ] = None
    format_option_refs: Annotated[
        list[format_option_ref.FormatOptionReference] | None, Field(min_length=1)
    ] = None
    standard_formats_only: bool | None = None
    min_exposures: Annotated[int | None, Field(ge=1)] = None
    start_date: Annotated[
        date | None,
        Field(
            description='Fixed-flight availability filter: with end_date, declares the exact flight the buyer intends to run. Returned products MUST be able to serve that flight, and pricing and forecasts are scoped to it. Mutually exclusive with availability_horizon.'
        ),
    ] = None
    end_date: Annotated[
        date | None,
        Field(
            description='Fixed-flight availability filter end. See start_date. Mutually exclusive with availability_horizon.'
        ),
    ] = None
    availability_horizon: Annotated[
        AvailabilityHorizon | None,
        Field(
            description="Flexible-window availability discovery: the buyer is open to any bookable window inside [start_time, end_time) and asks the seller to describe when the returned inventory can run, instead of filtering to one exact flight. Sellers that support this field partition the horizon into time-dimensioned forecast rows (forecast-dimension-time) carrying availability_status; sellers that cannot cover the full horizon signal the gap via the response's incomplete[] mechanism. Unlike start_date/end_date this is not an eligibility filter — products remain returnable when only part of the horizon is open. The resulting availability is a snapshot bounded by the forecast's valid_until, never a hold. Mutually exclusive with start_date and end_date, which declare a fixed flight; buyers that already know their dates use those instead."
        ),
    ] = None
    budget_range: budget_range_1.BudgetRange | None = None
    countries: Annotated[
        list[Country] | None,
        Field(
            description="Filter by country coverage using ISO 3166-1 alpha-2 codes (e.g., ['US', 'CA', 'GB']). Returns products whose geographic coverage includes at least one of the specified countries. This is a product attribute filter, not a delivery-targeting instruction.",
            min_length=1,
        ),
    ] = None
    property_list: Annotated[
        property_list_ref.PropertyListReference | None,
        Field(
            description='Reference to an externally managed property list. When provided, the seller filters products to only those available on properties in the list. This narrows which publisher inventory is returned; it is a product attribute filter, not a delivery-targeting instruction.'
        ),
    ] = None
    channels: Annotated[list[channels_1.MediaChannel] | None, Field(min_length=1)] = None
    video_placement_types: Annotated[
        list[video_placement_type.VideoPlacementType] | None, Field(min_length=1)
    ] = None
    audio_distribution_types: Annotated[
        list[audio_distribution_type.AudioDistributionType] | None, Field(min_length=1)
    ] = None
    sponsored_placement_types: Annotated[
        list[sponsored_placement_type.SponsoredPlacementType] | None, Field(min_length=1)
    ] = None
    social_placement_surfaces: Annotated[
        list[social_placement_surface.SocialPlacementSurface] | None, Field(min_length=1)
    ] = None
    trusted_match: TrustedMatch | None = None
    required_features: Annotated[
        canonical_media_buy_features.CanonicalMediaBuyFeatures | None,
        Field(description='Canonical protocol features the seller must support.'),
    ] = None
    required_performance_standards: Annotated[
        list[RequiredPerformanceStandard] | None, Field(min_length=1)
    ] = None
    required_metrics: Annotated[
        list[available_metric.AvailableMetric] | None, Field(min_length=1)
    ] = None
    required_vendor_metrics: Annotated[list[RequiredVendorMetric] | None, Field(min_length=1)] = (
        None
    )
    audience_evidence_requirements: (
        product_audience_evidence_requirements.ProductAudienceEvidenceRequirements | None
    ) = None
    ext: ext_1.ExtensionObject | None = None
