# generated by datamodel-codegen:
#   filename:  core/reporting_canonical_content_digest.json
#   timestamp: 2026-09-01T19:37:00+00:00

from __future__ import annotations

from typing import Annotated, Literal

from adcp.types.base import AdCPBaseModel
from pydantic import AnyUrl, ConfigDict, Field


class ReportingCanonicalContentDigest(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
        regex_engine="python-re",
    )
    algorithm: Literal['sha256'] = 'sha256'
    value: Annotated[str, Field(pattern='^[A-Fa-f0-9]{64}$')]
    canonicalization_id: Annotated[str, Field(max_length=128, min_length=1)]
    canonicalization_uri: Annotated[
        AnyUrl,
        Field(
            description='Location of the exact immutable canonicalization contract. Consumers verify canonicalization_sha256 before applying it.'
        ),
    ]
    canonicalization_sha256: Annotated[str, Field(pattern='^[A-Fa-f0-9]{64}$')]
