# generated by datamodel-codegen:
#   filename:  core/reporting_report_definition.json
#   timestamp: 2026-09-01T19:37:00+00:00

from __future__ import annotations

from adcp.types._str_enum import StrEnum
from typing import Annotated, Any, Literal

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field, RootModel


class Provider(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    domain: Annotated[
        str, Field(pattern='^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$')
    ]


class Source(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    provider: Provider
    system: Annotated[str, Field(max_length=128, min_length=1)]
    api_version: Annotated[str, Field(max_length=128, min_length=1)]
    query_semantics: Annotated[
        dict[str, Any],
        Field(
            description='Canonical JSON object containing every source option that can change the numbers, including attribution settings, action-report-time, filters, and mapping version.'
        ),
    ]


class Aggregation(StrEnum):
    sum = 'sum'
    count = 'count'  # type: ignore[assignment]
    min = 'min'
    max = 'max'
    average = 'average'
    ratio = 'ratio'
    last = 'last'
    custom = 'custom'


class Metric(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(max_length=128, min_length=1)]
    source_expression: Annotated[str, Field(max_length=2048, min_length=1)]
    aggregation: Aggregation
    unit: Annotated[str | None, Field(max_length=64, min_length=1)] = None


class Dimension(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class RestatementPolicy(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
        regex_engine="python-re",
    )
    source_requery_duration: Annotated[
        str,
        Field(
            pattern='^P(?=\\d|T)(?=.*\\d)(?:\\d+Y)?(?:\\d+M)?(?:\\d+D)?(?:T(?=\\d)(?:\\d+H)?(?:\\d+M)?(?:\\d+S)?)?$'
        ),
    ]
    emit_only_on_content_change: Literal[True]


class FinalityPolicies(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    finality_policy_id: Annotated[
        str, Field(max_length=255, min_length=1, pattern='^[A-Za-z0-9_.:-]{1,255}$')
    ]
    basis: Literal['source_final'] = 'source_final'
    source_signal: Annotated[str, Field(max_length=512, min_length=1)]


class FinalityPolicies1(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
        regex_engine="python-re",
    )
    finality_policy_id: Annotated[
        str, Field(max_length=255, min_length=1, pattern='^[A-Za-z0-9_.:-]{1,255}$')
    ]
    basis: Literal['contractual_cutoff'] = 'contractual_cutoff'
    duration_after_period_end: Annotated[
        str,
        Field(
            pattern='^P(?=\\d|T)(?=.*\\d)(?:\\d+Y)?(?:\\d+M)?(?:\\d+D)?(?:T(?=\\d)(?:\\d+H)?(?:\\d+M)?(?:\\d+S)?)?$'
        ),
    ]


class FinalityPolicies2(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
        regex_engine="python-re",
    )
    finality_policy_id: Annotated[
        str, Field(max_length=255, min_length=1, pattern='^[A-Za-z0-9_.:-]{1,255}$')
    ]
    basis: Literal['stabilized'] = 'stabilized'
    minimum_age: Annotated[
        str,
        Field(
            pattern='^P(?=\\d|T)(?=.*\\d)(?:\\d+Y)?(?:\\d+M)?(?:\\d+D)?(?:T(?=\\d)(?:\\d+H)?(?:\\d+M)?(?:\\d+S)?)?$'
        ),
    ]
    unchanged_for: Annotated[
        str,
        Field(
            pattern='^P(?=\\d|T)(?=.*\\d)(?:\\d+Y)?(?:\\d+M)?(?:\\d+D)?(?:T(?=\\d)(?:\\d+H)?(?:\\d+M)?(?:\\d+S)?)?$'
        ),
    ]


class ReportCalendarTimezoneBasis(StrEnum):
    utc = 'utc'
    account_timezone = 'account_timezone'
    configured_timezone = 'configured_timezone'


class Calendar(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    timezone_basis: ReportCalendarTimezoneBasis
    timezone: Annotated[str | None, Field(max_length=255, min_length=1)] = None


class ReportingReportDefinition(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract_version: Literal['1.0'] = '1.0'
    media_type: Literal['application/vnd.adcp.reporting-definition+json'] = 'application/vnd.adcp.reporting-definition+json'
    report_definition_id: Annotated[
        str, Field(max_length=255, min_length=1, pattern='^[A-Za-z0-9_.:-]{1,255}$')
    ]
    reporting_profile: Annotated[str, Field(max_length=128, min_length=1)]
    grain: Annotated[str, Field(max_length=128, min_length=1)]
    source: Source
    calendar: Calendar
    metrics: Annotated[list[Metric], Field(min_length=1)]
    dimensions: list[Dimension]
    restatement_policy: RestatementPolicy
    finality_policies: Annotated[
        list[FinalityPolicies | FinalityPolicies1 | FinalityPolicies2], Field(min_length=1)
    ]
