# generated by datamodel-codegen:
#   filename:  core/reporting_schedule.json
#   timestamp: 2026-09-05T11:09:57+00:00

from __future__ import annotations

from adcp.types._str_enum import StrEnum
from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import AwareDatetime, ConfigDict, Field


class ReportingScheduleAlignment(StrEnum):
    utc = 'utc'
    account_timezone = 'account_timezone'
    source_timezone = 'source_timezone'
    billing_cycle = 'billing_cycle'


class ReportingSchedule(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
        regex_engine="python-re",
    )
    period_duration: Annotated[
        str,
        Field(
            description='Strictly positive ISO 8601 duration of each reporting period, such as PT15M, P1D, or P1M.',
            pattern='^P(?=.*[1-9])(?=\\d|T)(?:\\d+Y)?(?:\\d+M)?(?:\\d+D)?(?:T(?=\\d)(?:\\d+H)?(?:\\d+M)?(?:\\d+S)?)?$',
        ),
    ]
    alignment: ReportingScheduleAlignment
    period_anchor: Annotated[
        AwareDatetime | None,
        Field(
            description='Required for billing_cycle alignment. This immutable instant anchors the recurring half-open billing periods so producer and consumer derive the same month, quarter, or other contractual cycle.'
        ),
    ] = None
    period_timezone: Annotated[
        str | None,
        Field(
            description='Required IANA timezone for source_timezone and billing_cycle calendar arithmetic. A numeric UTC offset is not sufficient because it does not define DST transitions.',
            max_length=255,
            min_length=1,
        ),
    ] = None
    delivery_sla: Annotated[
        str,
        Field(
            description='Non-negative maximum time after period end before the required revision is due. PT0S means due at period close; expected_at equals the resolved period end plus this duration.',
            pattern='^P(?=\\d|T)(?=.*\\d)(?:\\d+Y)?(?:\\d+M)?(?:\\d+D)?(?:T(?=\\d)(?:\\d+H)?(?:\\d+M)?(?:\\d+S)?)?$',
        ),
    ]
