# generated by datamodel-codegen:
#   filename:  core/signal_modeling_disclosure.json
#   timestamp: 2026-05-29T23:56:01+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import AnyUrl, ConfigDict, Field


class Audience(Enum):
    buyer = 'buyer'
    data_subject = 'data_subject'
    regulator = 'regulator'
    public = 'public'


class Jurisdiction(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    country: Annotated[
        str, Field(description='ISO 3166-1 alpha-2 country code.', pattern='^[A-Z]{2}$')
    ]
    region: Annotated[
        str | None,
        Field(
            description='Provider-defined sub-national region code or name when the obligation is regional. No global canonical format is implied.'
        ),
    ] = None
    regulation: Annotated[
        str,
        Field(description='Provider-supplied regulation identifier for the disclosure obligation.'),
    ]
    disclosure_text: Annotated[
        str | None,
        Field(
            description='Human-readable disclosure text or summary the provider expects buyers or reviewers to see.'
        ),
    ] = None
    disclosure_url: Annotated[
        AnyUrl | None,
        Field(
            description="Optional URL to the provider's canonical disclosure or methodology page for this jurisdiction."
        ),
    ] = None
    audience: Annotated[
        Audience | None, Field(description='Primary audience for this disclosure entry.')
    ] = None


class SignalModelingDisclosure(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    required: Annotated[
        bool,
        Field(
            description="The provider's claim that a modeling or AI-use disclosure is required for this signal in at least one applicable jurisdiction. This is a declared compliance signal, not a protocol-level legal determination."
        ),
    ]
    jurisdictions: Annotated[
        list[Jurisdiction] | None,
        Field(
            description='Jurisdictions where a modeling or AI-use disclosure applies.', min_length=1
        ),
    ] = None
    notes: Annotated[
        str | None,
        Field(
            description='Optional provider notes on how the disclosure should be interpreted. Informational only; buyers should not branch programmatically on this text.',
            max_length=2000,
        ),
    ] = None
