# generated by datamodel-codegen:
#   filename:  core/signal_definition_enrichment.json
#   timestamp: 2026-06-04T19:44:00+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import AnyUrl, AwareDatetime, ConfigDict, EmailStr, Field, RootModel

from ..enums import consent_basis as consent_basis_1
from ..enums import restricted_attribute
from . import signal_modeling_disclosure


class Value(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1)]
    path: str | None = None
    modifiers: list[str] | None = None


class ValueMapping(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: str
    taxonomy_value_id: str
    path: str | None = None
    modifiers: list[str] | None = None


class ParentMatchBehavior(Enum):
    exact_only = 'exact_only'
    descendants_supported = 'descendants_supported'
    unknown = 'unknown'


class Taxonomy(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ref: AnyUrl
    version: str | None = None
    segtax: Annotated[int | None, Field(ge=1)] = None
    etag: str | None = None
    values: Annotated[list[Value], Field(min_length=1)]
    value_mappings: Annotated[list[ValueMapping] | None, Field(min_length=1)] = None
    parent_match_behavior: ParentMatchBehavior | None = None


class DataSource(Enum):
    app_behavior = 'app_behavior'
    app_usage = 'app_usage'
    web_usage = 'web_usage'
    geo_location = 'geo_location'
    email = 'email'
    tv_ott_or_stb_device = 'tv_ott_or_stb_device'
    panel = 'panel'
    online_ecommerce = 'online_ecommerce'
    credit_data = 'credit_data'
    loyalty_card = 'loyalty_card'
    transaction = 'transaction'
    online_survey = 'online_survey'
    offline_survey = 'offline_survey'
    public_record_census = 'public_record_census'
    public_record_voter_file = 'public_record_voter_file'
    public_record_other = 'public_record_other'
    offline_transaction = 'offline_transaction'


class Methodology(Enum):
    observed = 'observed'
    declared = 'declared'
    derived = 'derived'
    inferred = 'inferred'
    modeled = 'modeled'


class RefreshCadence(Enum):
    intra_day = 'intra_day'
    daily = 'daily'
    weekly = 'weekly'
    monthly = 'monthly'
    bi_monthly = 'bi_monthly'
    quarterly = 'quarterly'
    bi_annually = 'bi_annually'
    annually = 'annually'


class MatchKey(Enum):
    name = 'name'
    address = 'address'
    email = 'email'
    postal = 'postal'
    lat_long = 'lat_long'
    mobile_id = 'mobile_id'
    cookie_id = 'cookie_id'
    ip = 'ip'
    customer_id = 'customer_id'
    phone = 'phone'


class PreOnboardingPrecisionLevel(Enum):
    individual = 'individual'
    household = 'household'
    business = 'business'
    geography = 'geography'


class Onboarder(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    match_keys: Annotated[list[MatchKey], Field(min_length=1)]
    pre_onboarding_audience_expansion: bool | None = None
    pre_onboarding_device_expansion: bool | None = None
    pre_onboarding_precision_level: PreOnboardingPrecisionLevel | None = None


class Country(RootModel[str]):
    root: Annotated[str, Field(pattern='^[A-Z]{2}$')]


class Art9Basis(Enum):
    explicit_consent = 'explicit_consent'
    manifestly_made_public = 'manifestly_made_public'
    substantial_public_interest = 'substantial_public_interest'
    vital_interests = 'vital_interests'


class Method(Enum):
    lookalike = 'lookalike'
    supervised = 'supervised'
    embedding = 'embedding'
    rules = 'rules'


class Type(Enum):
    first_party_crm = 'first_party_crm'
    panel = 'panel'
    declared_survey = 'declared_survey'
    transactional = 'transactional'
    behavioral = 'behavioral'


class SeedSource(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    provider_signed: Annotated[
        bool,
        Field(
            description='Provider assertion that the seed source carries a signed attestation. Consumers MUST NOT treat this boolean alone as cryptographic proof.'
        ),
    ]


class TrainingDataJurisdiction(Country):
    pass


class AiActRiskClass(Enum):
    minimal = 'minimal'
    limited = 'limited'
    high_risk = 'high_risk'


class Right(Enum):
    access = 'access'
    rectification = 'rectification'
    erasure = 'erasure'
    portability = 'portability'
    objection = 'objection'


class Channel(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rights: Annotated[list[Right], Field(min_length=1)]
    url: AnyUrl | None = None
    email: EmailStr | None = None
    languages: list[str] | None = None
    countries: list[Country] | None = None


class DataSubjectRights(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    upstream_source_domain: Annotated[
        str | None,
        Field(
            max_length=253,
            pattern='^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])\\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\\-]{0,61}[A-Za-z0-9])$',
        ),
    ] = None
    channels: Annotated[list[Channel], Field(min_length=1)]
    response_sla_days: Annotated[int | None, Field(ge=1, le=90)] = None
    ccpa_opt_out_url: AnyUrl | None = None


class Modeling(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    method: Method
    seed_source: SeedSource
    training_data_jurisdictions: Annotated[list[TrainingDataJurisdiction], Field(min_length=1)]
    ai_act_risk_class: AiActRiskClass
    disclosure: signal_modeling_disclosure.SignalModelingDisclosure | None = None


class SignalDefinitionEnrichment(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    restricted_attributes: Annotated[
        list[restricted_attribute.RestrictedAttribute] | None,
        Field(description='Restricted attribute categories this signal touches.', min_length=1),
    ] = None
    policy_categories: Annotated[
        list[str] | None,
        Field(description='Policy categories this signal is sensitive for.', min_length=1),
    ] = None
    taxonomy: Annotated[
        Taxonomy | None,
        Field(
            description='Optional taxonomy metadata describing what this signal means in an external audience, content, retail-media, or provider-owned taxonomy.'
        ),
    ] = None
    segmentation_criteria: Annotated[str | None, Field(max_length=500)] = None
    criteria_url: AnyUrl | None = None
    data_sources: Annotated[list[DataSource] | None, Field(min_length=1)] = None
    methodology: Methodology | None = None
    audience_expansion: bool | None = None
    device_expansion: bool | None = None
    refresh_cadence: RefreshCadence | None = None
    lookback_window: RefreshCadence | None = None
    onboarder: Onboarder | None = None
    countries: Annotated[list[Country] | None, Field(min_length=1)] = None
    consent_basis: Annotated[
        list[consent_basis_1.ConsentBasis] | None,
        Field(
            description="Data provider's declared GDPR Article 6 lawful basis or consent basis for the underlying signal definition, projected into this get_signals response row when requested. Sellers and federating agents that pass through another provider's signal MUST NOT substitute their own processing basis for the provider-declared basis.",
            min_length=1,
        ),
    ] = None
    art9_basis: Annotated[
        Art9Basis | None,
        Field(
            description="Data provider's declared GDPR Article 9 basis for the underlying signal definition when special-category data is involved and Article 9 applies, projected into this get_signals response row when requested. Sellers and federating agents that pass through another provider's signal MUST NOT substitute their own Article 9 basis for the provider-declared basis."
        ),
    ] = None
    modeling: Modeling | None = None
    data_subject_rights: Annotated[
        DataSubjectRights | None,
        Field(
            description='Per-signal data-subject-rights routing. This is a contact/routing reference, not a machine-callable AdCP API.'
        ),
    ] = None
    last_updated: Annotated[
        AwareDatetime | None,
        Field(
            description='When this definition record was last updated. This indicates freshness of the definition record, not an attestation that the underlying data or model was refreshed at that time.'
        ),
    ] = None
    dts_compliant_version: str | None = None
