# generated by datamodel-codegen:
#   filename:  core/tasks_get_request.json
#   timestamp: 2026-04-29T01:11:23+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field

from . import context as context_1
from . import ext as ext_1


class TasksGetRequest(AdCPBaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    adcp_major_version: Annotated[
        int | None,
        Field(
            description="The AdCP major version the buyer's payloads conform to. Sellers validate against their supported major_versions and return VERSION_UNSUPPORTED if unsupported. When omitted, the seller assumes its highest supported version.",
            ge=1,
            le=99,
        ),
    ] = None
    task_id: Annotated[str, Field(description="Unique identifier of the task to retrieve")]
    include_history: Annotated[
        bool | None,
        Field(
            description="Include full conversation history for this task (may increase response size)"
        ),
    ] = False
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None
