# generated by datamodel-codegen:
#   filename:  core/warning_resource.json
#   timestamp: 2026-08-17T23:02:13+00:00

from __future__ import annotations

from adcp.types._str_enum import StrEnum

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict


class ResourceType(StrEnum):
    media_buy = 'media_buy'
    package = 'package'
    creative = 'creative'
    creative_assignment = 'creative_assignment'


class WarningAffectedResource(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    resource_type: ResourceType
    media_buy_id: str | None = None
    package_id: str | None = None
    creative_id: str | None = None
