# generated by datamodel-codegen:
#   filename:  tmp/error.json
#   timestamp: 2026-04-03T18:37:00+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Literal

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field


class Code(Enum):
    invalid_request = 'invalid_request'
    unknown_package = 'unknown_package'
    rate_limited = 'rate_limited'
    timeout = 'timeout'
    internal_error = 'internal_error'
    provider_unavailable = 'provider_unavailable'


class TmpError(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    code: Annotated[Code, Field(description='Machine-readable error code')]
    message: Annotated[
        str | None, Field(description='Human-readable error description for debugging')
    ] = None
    request_id: Annotated[
        str, Field(description='Echoed request identifier from the original request')
    ]
    type: Annotated[
        Literal['error'], Field(description='Message type discriminator for deserialization.')
    ]
