# generated by datamodel-codegen:
#   filename:  account/sync_governance_response.json
#   timestamp: 2026-05-02T19:36:29+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import AnyUrl, ConfigDict, Field, RootModel

from ..core import account_ref
from ..core import context as context_1
from ..core import error
from ..core import ext as ext_1


class Status(Enum):
    synced = 'synced'
    failed = 'failed'


class Category(RootModel[str]):
    root: Annotated[str, Field(max_length=64, pattern='^[a-z][a-z0-9_]*$')]


class GovernanceAgent(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: Annotated[AnyUrl, Field(description='Governance agent endpoint URL.')]
    categories: Annotated[
        list[Category] | None,
        Field(description='Governance categories this agent handles.', max_length=20),
    ] = None


class SyncGovernanceResponse2(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    errors: Annotated[
        list[error.Error],
        Field(
            description='Operation-level errors (e.g., authentication failure, service unavailable)',
            min_length=1,
        ),
    ]
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None


class Account(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    account: Annotated[
        account_ref.AccountReference, Field(description='Account reference, echoed from request')
    ]
    status: Annotated[
        Status,
        Field(
            description='Sync result. synced: governance agents persisted. failed: could not complete (see errors).'
        ),
    ]
    governance_agents: Annotated[
        list[GovernanceAgent] | None,
        Field(
            description='Governance agents now synced on this account. Reflects the persisted state after sync.'
        ),
    ] = None
    errors: Annotated[
        list[error.Error] | None,
        Field(description="Per-account errors (only present when status is 'failed')"),
    ] = None


class SyncGovernanceResponse1(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    accounts: Annotated[list[Account], Field(description='Per-account sync results')]
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None


SyncGovernanceResponse = SyncGovernanceResponse1 | SyncGovernanceResponse2
