"""AdCP Type System.

All AdCP types exported from a single location.
Users should import from here or directly from adcp.

    from adcp.types import Product, CreativeFilters
    from adcp import Product, CreativeFilters

IMPORTANT: Never import directly from adcp.types.generated_poc or
adcp.types._generated. These are internal modules regenerated from
upstream schemas. Only import from adcp.types (this module) or adcp.

Type Coercion:
    Request types accept flexible input for developer ergonomics:

    - Enum fields accept string values:
        ListCreativeFormatsRequest(type="video")  # Works!

    - Context fields accept dicts:
        GetProductsRequest(context={"key": "value"})  # Works!

    - FieldModel lists accept strings:
        ListCreativesRequest(fields=["creative_id", "name"])  # Works!

    See adcp.types._ergonomic for implementation details.
"""

from __future__ import annotations

# Apply type coercion to generated types (must be imported before other types)
# Note: the deprecation shim for the removed ``format_category`` submodule
# lives as a real file at ``generated_poc/enums/format_category.py`` — no
# sys.modules dance needed; Python's import system picks it up natively.
# ``scripts/post_generate_fixes.py`` restores that file after codegen wipes
# ``generated_poc/``.
from adcp.types import (
    _ergonomic,  # noqa: F401
    aliases,  # noqa: F401
)

# Also make submodules available for advanced use
from adcp.types import _generated as generated  # noqa: F401

# Import all types from generated code
# V3 Protocol Discovery types
# V3 Content Standards types
# V3 Sponsored Intelligence types
# V3 Governance (Property Lists) types
# Re-export webhook payload type for webhook handling
from adcp.types._generated import (
    A2UiComponent,
    A2UiSurface,
    Account,
    AccountReference,
    AccountScope,
    AcquireRightsRequest,
    AcquireRightsResponse,
    ActivateSignalRequest,
    ActivateSignalResponse,
    AdcpProtocol,
    AdvertiserIndustry,
    AggregatedTotals,
    AiTool,
    Artifact,
    ArtifactWebhookPayload,
    Asset,
    AssetContentType,
    AssignedPackage,
    Assignments,
    AudienceSource,
    Authentication,
    AuthenticationScheme,
    AuthorizedAgents,
    AvailableMetric,
    AvailablePackage,
    BrandReference,
    BuildCreativeRequest,
    BuildCreativeResponse,
    BusinessEntity,
    BuyingMode,
    ByCatalogItemItem,
    ByPackageItem,
    CalibrateContentRequest,
    CalibrateContentResponse,
    Catalog,
    CatalogAction,
    CatalogFieldBinding,
    CatalogFieldBinding1,
    CatalogFieldMapping,
    CatalogItemStatus,
    CatalogRequirements,
    CatalogType,
    CheckGovernanceRequest,
    CheckGovernanceResponse,
    CoBrandingRequirement,
    CollectionList,
    CollectionListChangedWebhook,
    CollectionListFilters,
    Colors,
    ComplyTestControllerRequest,
    ComplyTestControllerResponse,
    Contact,
    ContentIdType,
    ContentStandards,
    ContextMatchRequest,
    ContextMatchResponse,
    ContextObject,
    Country,
    CpaPricingOption,
    CpcPricingOption,
    CpcvPricingOption,
    CpmPricingOption,
    CppPricingOption,
    CpvPricingOption,
    CreateCollectionListRequest,
    CreateCollectionListResponse,
    CreateContentStandardsRequest,
    CreateContentStandardsResponse,
    CreateMediaBuyRequest,
    CreateMediaBuyResponse,
    CreatePropertyListRequest,
    CreatePropertyListResponse,
    Creative,
    CreativeAction,
    CreativeAgent,
    CreativeAgentCapability,
    CreativeApproval,
    CreativeApprovalStatus,
    CreativeAsset,
    CreativeAssignment,
    CreativeFilters,
    CreativeManifest,
    CreativePolicy,
    CreativeStatus,
    CreativeVariant,
    CreditLimit,
    DaastTrackingEvent,
    DaastVersion,
    DailyBreakdownItem,
    DateRange,
    DatetimeRange,
    DayOfWeek,
    DaypartTarget,
    DeleteCollectionListRequest,
    DeleteCollectionListResponse,
    DeletePropertyListRequest,
    DeletePropertyListResponse,
    DeliveryForecast,
    DeliveryMeasurement,
    DeliveryMetrics,
    DeliveryStatus,
    DeliveryType,
    DemographicSystem,
    DevicePlatform,
    DeviceType,
    Dimensions,
    DimensionUnit,
    DoohMetrics,
    Duration,
    ErrorCode,
    EventType,
    ExtensionObject,
    FeedbackSource,
    FeedFormat,
    Field1,
    FieldModel,
    FlatRatePricingOption,
    Fonts,
    ForecastableMetric,
    ForecastMethod,
    ForecastPoint,
    ForecastRange,
    ForecastRangeUnit,
    Format,
    FormatCard,
    FormatCardDetailed,
    FormatIdParameter,
    FormatReferenceStructuredObject,
    FrequencyCap,
    FrequencyCapScope,
    GeoCountry,
    GeoMetro,
    GeoPostalArea,
    GeoRegion,
    GetAccountFinancialsRequest,
    GetAccountFinancialsResponse,
    GetAdcpCapabilitiesRequest,
    GetAdcpCapabilitiesResponse,
    GetBrandIdentityRequest,
    GetBrandIdentityResponse,
    GetCollectionListRequest,
    GetCollectionListResponse,
    GetContentStandardsRequest,
    GetContentStandardsResponse,
    GetCreativeDeliveryRequest,
    GetCreativeDeliveryResponse,
    GetCreativeFeaturesRequest,
    GetCreativeFeaturesResponse,
    GetMediaBuyArtifactsRequest,
    GetMediaBuyArtifactsResponse,
    GetMediaBuyDeliveryRequest,
    GetMediaBuyDeliveryResponse,
    GetMediaBuysRequest,
    GetMediaBuysResponse,
    GetPlanAuditLogsRequest,
    GetPlanAuditLogsResponse,
    GetProductsRequest,
    GetProductsResponse,
    GetPropertyListRequest,
    GetPropertyListResponse,
    GetRightsRequest,
    GetRightsResponse,
    GetSignalsRequest,
    GetSignalsResponse,
    GovernanceAgent,
    Gtin,
    HttpMethod,
    Identifier,
    IdentityMatchRequest,
    IdentityMatchResponse,
    Input,
    JavascriptModuleType,
    KellerType,
    LandingPageRequirement,
    ListAccountsRequest,
    ListAccountsResponse,
    ListCollectionListsRequest,
    ListCollectionListsResponse,
    ListContentStandardsRequest,
    ListContentStandardsResponse,
    ListCreativeFormatsRequest,
    ListCreativeFormatsResponse,
    ListCreativesRequest,
    ListCreativesResponse,
    ListPropertyListsRequest,
    ListPropertyListsResponse,
    LogEventRequest,
    LogEventResponse,
    Logo,
    MarkdownFlavor,
    McpWebhookPayload,
    MeasurementPeriod,
    MediaBuy,
    MediaBuyDelivery,
    MediaBuyFeatures,
    MediaBuyPackage,
    MediaBuyStatus,
    MediaChannel,
    Metadata,
    MetricType,
    NotificationType,
    Offering,
    OfferingAssetConstraint,
    OfferingAssetGroup,
    OfferPrice,
    OptimizationGoal,
    OutcomeMeasurement,
    Overlay,
    Pacing,
    PackageRequest,
    PackageUpdate,
    Pagination,
    PaginationRequest,
    PaginationResponse,
    Parameters,
    PaymentTerms,
    PerformanceFeedback,
    Placement,
    Preview,
    PreviewCreativeRequest,
    PreviewCreativeResponse,
    PreviewOutputFormat,
    PreviewRender,
    PriceGuidance,
    PricingModel,
    PrimaryCountry,
    Product,
    ProductCard,
    ProductCardDetailed,
    ProductFilters,
    Property,
    PropertyIdentifierTypes,
    PropertyList,
    PropertyListChangedWebhook,
    PropertyListFilters,
    PropertyListReference,
    PropertyType,
    Proposal,
    ProtocolEnvelope,
    ProtocolResponse,
    ProvidePerformanceFeedbackRequest,
    ProvidePerformanceFeedbackResponse,
    PublisherDomain,
    PublisherIdentifierTypes,
    PushNotificationConfig,
    QuartileData,
    QuerySummary,
    ReachUnit,
    Refine,
    RefinementApplied,
    RefinementApplied1,
    RefinementApplied2,
    RefinementApplied3,
    Renders,
    ReportingBucket,
    ReportingCapabilities,
    ReportingFrequency,
    ReportingPeriod,
    ReportingWebhook,
    ReportPlanOutcomeRequest,
    ReportPlanOutcomeResponse,
    ReportUsageRequest,
    ReportUsageResponse,
    Request,
    Response,
    Responsive,
    Results,
    RightsPricingOption,
    RightsTerms,
    Security,
    SellerAgentReference,
    Setup,
    SiCapabilities,
    SiGetOfferingRequest,
    SiGetOfferingResponse,
    Signal,
    SignalCatalogType,
    SignalFilters,
    SignalPricingOption,
    SiIdentity,
    SiInitiateSessionRequest,
    SiInitiateSessionResponse,
    SiSendMessageRequest,
    SiSendMessageResponse,
    SiTerminateSessionRequest,
    SiTerminateSessionResponse,
    SiUiElement,
    Snapshot,
    SnapshotUnavailableReason,
    Sort,
    SortApplied,
    SortDirection,
    StatusSummary,
    SyncAccountsRequest,
    SyncAccountsResponse,
    SyncAudiencesRequest,
    SyncAudiencesResponse,
    SyncCatalogsInputRequired,
    SyncCatalogsRequest,
    SyncCatalogsResponse,
    SyncCatalogsSubmitted,
    SyncCatalogsWorking,
    SyncCreativesRequest,
    SyncCreativesResponse,
    SyncEventSourcesRequest,
    SyncEventSourcesResponse,
    SyncGovernanceRequest,
    SyncGovernanceResponse,
    SyncPlansRequest,
    SyncPlansResponse,
    Tags,
    TargetingOverlay,
    TaskType,
    TimeBasedPricingOption,
    TimeUnit,
    TmpError,
    Totals,
    Transform,
    UpdateCollectionListRequest,
    UpdateCollectionListResponse,
    UpdateContentStandardsRequest,
    UpdateContentStandardsResponse,
    UpdateFrequency,
    UpdateMediaBuyRequest,
    UpdateMediaBuyResponse,
    UpdatePropertyListRequest,
    UpdatePropertyListResponse,
    UpdateRightsRequest,
    UpdateRightsResponse,
    UrlAssetType,
    ValidateContentDeliveryRequest,
    ValidateContentDeliveryResponse,
    ValidationMode,
    VastTrackingEvent,
    VastVersion,
    VcpmPricingOption,
    VenueBreakdownItem,
    ViewThreshold,
    WcagLevel,
    WebhookResponseType,
)
from adcp.types._generated import (
    AudioAsset as AudioContent,
)
from adcp.types._generated import (
    CssAsset as CssContent,
)
from adcp.types._generated import (
    HtmlAsset as HtmlContent,
)
from adcp.types._generated import (
    ImageAsset as ImageContent,
)
from adcp.types._generated import (
    JavascriptAsset as JavascriptContent,
)
from adcp.types._generated import (
    Offer as TmpOffer,
)
from adcp.types._generated import TaskStatus as GeneratedTaskStatus
from adcp.types._generated import (
    TextAsset as TextContent,
)
from adcp.types._generated import (
    UrlAsset as UrlContent,
)
from adcp.types._generated import (
    VideoAsset as VideoContent,
)
from adcp.types._generated import (
    WebhookAsset as WebhookContent,
)
from adcp.types._generated import _ErrorFromError as Error
from adcp.types._generated import _PackageFromPackage as Package

# Import semantic aliases for discriminated unions
from adcp.types.aliases import (
    AccountReferenceById,
    AccountReferenceByNaturalKey,
    AcquireRightsAcquiredResponse,
    AcquireRightsErrorResponse,
    AcquireRightsPendingResponse,
    AcquireRightsRejectedResponse,
    ActivateSignalErrorResponse,
    ActivateSignalSuccessResponse,
    AgentDeployment,
    AgentDestination,
    AudioFormatAsset,
    AudioFormatGroupAsset,
    AuthorizedAgent,
    AuthorizedAgentsByInlineProperties,
    AuthorizedAgentsByPropertyId,
    AuthorizedAgentsByPropertyTag,
    AuthorizedAgentsByPublisherProperties,
    AuthorizedAgentsBySignalId,
    AuthorizedAgentsBySignalTag,
    BothPreviewRender,
    BriefFormatAsset,
    BuildCreativeErrorResponse,
    BuildCreativeSuccessResponse,
    CalibrateContentErrorResponse,
    CalibrateContentSuccessResponse,
    CatalogFormatAsset,
    CatalogGroupBinding,
    ComplyErrorResponse,
    ComplyListScenariosResponse,
    ComplySimulationResponse,
    ComplyStateTransitionResponse,
    ConsentBasis,
    CreateContentStandardsErrorResponse,
    CreateContentStandardsSuccessResponse,
    CreateMediaBuyErrorResponse,
    CreateMediaBuySubmittedResponse,
    CreateMediaBuySuccessResponse,
    CssFormatAsset,
    CssFormatGroupAsset,
    DaastFormatAsset,
    DaastFormatGroupAsset,
    Deployment,
    Destination,
    FormatId,
    GetAccountFinancialsErrorResponse,
    GetAccountFinancialsSuccessResponse,
    GetBrandIdentityErrorResponse,
    GetBrandIdentityField,
    GetBrandIdentitySuccessResponse,
    GetContentStandardsErrorResponse,
    GetContentStandardsSuccessResponse,
    GetCreativeDeliveryByBuyerRefRequest,
    GetCreativeDeliveryByCreativeRequest,
    GetCreativeDeliveryByMediaBuyRequest,
    GetCreativeFeaturesErrorResponse,
    GetCreativeFeaturesSuccessResponse,
    GetMediaBuyArtifactsErrorResponse,
    GetMediaBuyArtifactsSuccessResponse,
    GetProductsBriefRequest,
    GetProductsField,
    GetProductsRefineRequest,
    GetProductsWholesaleRequest,
    GetRightsErrorResponse,
    GetRightsSuccessResponse,
    GetSignalsDiscoveryRequest,
    GetSignalsLookupRequest,
    HtmlFormatAsset,
    HtmlFormatGroupAsset,
    HtmlPreviewRender,
    ImageFormatAsset,
    ImageFormatGroupAsset,
    InlineDaastAsset,
    InlineVastAsset,
    JavascriptFormatAsset,
    JavascriptFormatGroupAsset,
    KeyValueActivationKey,
    ListContentStandardsErrorResponse,
    ListContentStandardsSuccessResponse,
    LogEventErrorResponse,
    LogEventSuccessResponse,
    MarkdownFormatAsset,
    MarkdownFormatGroupAsset,
    MediaBuyDeliveryStatus,
    PlatformDeployment,
    PlatformDestination,
    PreviewCreativeBatchResponse,
    PreviewCreativeSingleResponse,
    PreviewCreativeVariantResponse,
    PricingOption,
    PropertyId,
    PropertyTag,
    ProvidePerformanceFeedbackByBuyerRefRequest,
    ProvidePerformanceFeedbackByMediaBuyRequest,
    ProvidePerformanceFeedbackErrorResponse,
    ProvidePerformanceFeedbackSuccessResponse,
    PublisherProperties,
    PublisherPropertiesAll,
    PublisherPropertiesById,
    PublisherPropertiesByTag,
    RepeatableAssetGroup,
    SegmentIdActivationKey,
    SiSendActionResponseRequest,
    SiSendTextMessageRequest,
    SyncAccountsErrorResponse,
    SyncAccountsSuccessResponse,
    SyncAudiencesAudience,
    SyncAudiencesErrorResponse,
    SyncAudiencesSuccessResponse,
    SyncCatalogResult,
    SyncCatalogsErrorResponse,
    SyncCatalogsSuccessResponse,
    SyncCreativeResult,
    SyncCreativesErrorResponse,
    SyncCreativesSuccessResponse,
    SyncEventSourcesErrorResponse,
    SyncEventSourcesSuccessResponse,
    TextFormatAsset,
    TextFormatGroupAsset,
    UpdateContentStandardsErrorResponse,
    UpdateContentStandardsSuccessResponse,
    UpdateMediaBuyErrorResponse,
    UpdateMediaBuyPackagesRequest,
    UpdateMediaBuyPropertiesRequest,
    UpdateMediaBuySuccessResponse,
    UrlDaastAsset,
    UrlFormatAsset,
    UrlFormatGroupAsset,
    UrlPreviewRender,
    UrlVastAsset,
    ValidateContentDeliveryErrorResponse,
    ValidateContentDeliverySuccessResponse,
    VastFormatAsset,
    VastFormatGroupAsset,
    VideoFormatAsset,
    VideoFormatGroupAsset,
    WebhookFormatAsset,
    WebhookFormatGroupAsset,
)

# Re-export core types (not in generated, but part of public API)
# Note: We don't import TaskStatus here to avoid shadowing GeneratedTaskStatus
# Users should import TaskStatus from adcp.types.core directly if they need the core enum
from adcp.types.core import (
    AgentConfig,
    Member,
    Policy,
    PolicyExemplar,
    PolicyExemplars,
    PolicyHistory,
    PolicyRevision,
    PolicySummary,
    Protocol,
    ResolvedBrand,
    ResolvedProperty,
    TaskResult,
    WebhookMetadata,
)

# Deprecated: types removed from _generated.py but classes still exist in generated_poc
from adcp.types.generated_poc.brand import Disclaimer, ProductCatalog

# Status: _generated picks invoice status (get_account_financials_response) due to
# alphabetical module sort. Import the delivery status variant directly for backward compat.
from adcp.types.generated_poc.media_buy.get_media_buy_delivery_response import (  # noqa: E501
    Status,
)

# Re-export type guards for discriminated union response handling
from adcp.types.guards import (  # noqa: F401
    is_activate_signal_error,
    is_activate_signal_success,
    is_adcp_error,
    is_adcp_success,
    is_build_creative_error,
    is_build_creative_success,
    is_calibrate_content_success,
    is_create_media_buy_error,
    is_create_media_buy_success,
    is_get_account_financials_error,
    is_get_account_financials_success,
    is_get_creative_features_success,
    is_log_event_error,
    is_log_event_success,
    is_performance_feedback_error,
    is_performance_feedback_success,
    is_sync_accounts_error,
    is_sync_accounts_success,
    is_sync_catalogs_error,
    is_sync_catalogs_success,
    is_sync_creatives_error,
    is_sync_creatives_success,
    is_update_media_buy_error,
    is_update_media_buy_success,
    is_validate_content_delivery_success,
)
from adcp.types.projections import (
    AccountResponse,
    BusinessEntityResponse,
    to_account_response,
)
from adcp.types.registry import BrandSource

# Schema-variant marker for cross-class entity overrides (#710). Adopters
# annotate Pydantic field overrides with ``SchemaVariant[T]`` instead of
# ``# type: ignore[assignment]`` when substituting a sibling class for the
# parent's declared type. Activate the mypy plugin via
# ``[tool.mypy] plugins = ["adcp.types.mypy_plugin"]`` to suppress the
# override-compat check on those fields.
from adcp.types.variants import SchemaVariant

# Semantic aliases for auto-generated field enum names
ListCreativesField = Field1

# FieldModel: _generated picks brand.get_brand_identity_request.FieldModel due to
# alphabetical module sort. Override to preserve backward compat with the original
# get_products_request variant (which the generator renamed to Field1 in that module).
FieldModel = GetProductsField  # type: ignore[misc,assignment]  # noqa: F811

# Backward compatibility aliases
AssetType = AssetContentType  # Use AssetContentType instead
Measurement = OutcomeMeasurement  # Renamed upstream to OutcomeMeasurement

# Pricing type renames: upstream merged auction/fixed variants into single types
CpmAuctionPricingOption = CpmPricingOption
CpmFixedRatePricingOption = CpmPricingOption
VcpmAuctionPricingOption = VcpmPricingOption
VcpmFixedRatePricingOption = VcpmPricingOption

# Activation key schema change: property_id/property_tag → segment_id/key_value
PropertyIdActivationKey = SegmentIdActivationKey
PropertyTagActivationKey = KeyValueActivationKey

# Deprecated: types removed from upstream schemas entirely
# Performance was removed; PerformanceFeedback is the replacement
Performance = PerformanceFeedback

# MediaSubAsset (SubAsset1) and TextSubAsset (SubAsset2) were removed from the
# upstream schema with no replacement. These stubs exist only to provide a clear
# error message for code that still references them.


class MediaSubAsset:
    """Removed from ADCP schema. Previously SubAsset with asset_kind='media'."""

    def __init__(self, *args: object, **kwargs: object) -> None:
        raise TypeError(
            "MediaSubAsset was removed from the ADCP schema. " "There is no direct replacement."
        )


class TextSubAsset:
    """Removed from ADCP schema. Previously SubAsset with asset_kind='text'."""

    def __init__(self, *args: object, **kwargs: object) -> None:
        raise TypeError(
            "TextSubAsset was removed from the ADCP schema. " "There is no direct replacement."
        )


# Preview response rename aliases (per-mode Request variants were removed when
# PreviewCreativeRequest collapsed to a single class with a request_type enum).
PreviewCreativeStaticResponse = PreviewCreativeSingleResponse
PreviewCreativeInteractiveResponse = PreviewCreativeBatchResponse

# Schema renames from filter ref split (v1.0.0)
Action = CreativeAction
Capability = CreativeAgentCapability
CoBranding = CoBrandingRequirement
LandingPage = LandingPageRequirement
Method = HttpMethod
ModuleType = JavascriptModuleType
TrackingEvent = VastTrackingEvent  # Split into DaastTrackingEvent and VastTrackingEvent
Unit = DimensionUnit
OutputFormat = PreviewOutputFormat
ResponseType = WebhookResponseType
Scheme = AuthenticationScheme
SignalType = SignalCatalogType
UrlType = UrlAssetType
AvailableReportingFrequency = ReportingFrequency

__all__ = [
    # A2UI types
    "A2UiComponent",
    "A2UiSurface",
    # Account types
    "Account",
    "AccountReference",
    "AccountReferenceById",
    "AccountReferenceByNaturalKey",
    "AccountResponse",
    "AccountScope",
    "CreditLimit",
    "GetAccountFinancialsRequest",
    "GetAccountFinancialsResponse",
    "GovernanceAgent",
    "ListAccountsRequest",
    "ListAccountsResponse",
    "PaymentTerms",
    "ReportUsageRequest",
    "ReportUsageResponse",
    "ReportingBucket",
    "Setup",
    "SyncAccountsRequest",
    "SyncAccountsResponse",
    # Request/Response types
    "ActivateSignalRequest",
    "ActivateSignalResponse",
    "AdcpProtocol",
    "CreativeAction",
    "AggregatedTotals",
    "BuildCreativeRequest",
    "BuildCreativeResponse",
    "ByCatalogItemItem",
    "ByPackageItem",
    "CreateMediaBuyRequest",
    "CreateMediaBuyResponse",
    "DailyBreakdownItem",
    "GetMediaBuyDeliveryRequest",
    "GetMediaBuyDeliveryResponse",
    "GetMediaBuysRequest",
    "GetMediaBuysResponse",
    "GetProductsRequest",
    "GetProductsResponse",
    "GetSignalsRequest",
    "GetSignalsResponse",
    "ListCreativeFormatsRequest",
    "ListCreativeFormatsResponse",
    "ListCreativesRequest",
    "ListCreativesResponse",
    "MediaBuyDelivery",
    "PreviewCreativeRequest",
    "PreviewCreativeResponse",
    "ProtocolEnvelope",
    "ProtocolResponse",
    "ProvidePerformanceFeedbackRequest",
    "ProvidePerformanceFeedbackResponse",
    "QuerySummary",
    "Refine",
    "RefinementApplied",
    "RefinementApplied1",
    "RefinementApplied2",
    "RefinementApplied3",
    "SortApplied",
    "StatusSummary",
    "SyncCatalogsInputRequired",
    "SyncCatalogsRequest",
    "SyncCatalogsResponse",
    "SyncCatalogsSubmitted",
    "SyncCatalogsWorking",
    "SyncAudiencesAudience",
    "SyncAudiencesRequest",
    "SyncAudiencesResponse",
    "ConsentBasis",
    "SyncCreativesRequest",
    "SyncCreativesResponse",
    # Event & Source Operations
    "LogEventRequest",
    "LogEventResponse",
    "SyncEventSourcesRequest",
    "SyncEventSourcesResponse",
    "Totals",
    "UpdateMediaBuyRequest",
    "UpdateMediaBuyResponse",
    # V3 Protocol Discovery
    "GetAdcpCapabilitiesRequest",
    "GetAdcpCapabilitiesResponse",
    # TMP (Temporal Matching Protocol)
    "AvailablePackage",
    "ContextMatchRequest",
    "ContextMatchResponse",
    "IdentityMatchRequest",
    "IdentityMatchResponse",
    "TmpOffer",
    "OfferPrice",
    "TmpError",
    # Brand Rights
    "AcquireRightsRequest",
    "AcquireRightsResponse",
    "GetBrandIdentityRequest",
    "GetBrandIdentityResponse",
    "GetRightsRequest",
    "GetRightsResponse",
    "RightsPricingOption",
    "RightsTerms",
    # Compliance Test Controller
    "ComplyTestControllerRequest",
    "ComplyTestControllerResponse",
    # Creative Delivery
    "GetCreativeDeliveryRequest",
    "GetCreativeDeliveryResponse",
    # Creative Features
    "GetCreativeFeaturesRequest",
    "GetCreativeFeaturesResponse",
    # V3 Governance
    "CheckGovernanceRequest",
    "CheckGovernanceResponse",
    "GetPlanAuditLogsRequest",
    "GetPlanAuditLogsResponse",
    "ReportPlanOutcomeRequest",
    "ReportPlanOutcomeResponse",
    "SyncGovernanceRequest",
    "SyncGovernanceResponse",
    "SyncPlansRequest",
    "SyncPlansResponse",
    # Forecasting types
    "DayOfWeek",
    "DaypartTarget",
    "DeliveryForecast",
    "DemographicSystem",
    "ForecastMethod",
    "ForecastPoint",
    "ForecastRange",
    "ForecastRangeUnit",
    "ForecastableMetric",
    "ReachUnit",
    # V3 Content Standards
    "Artifact",
    "ArtifactWebhookPayload",
    "CalibrateContentRequest",
    "CalibrateContentResponse",
    "ContentStandards",
    "CreateContentStandardsRequest",
    "CreateContentStandardsResponse",
    "GetContentStandardsRequest",
    "GetContentStandardsResponse",
    "GetMediaBuyArtifactsRequest",
    "GetMediaBuyArtifactsResponse",
    "ListContentStandardsRequest",
    "ListContentStandardsResponse",
    "UpdateContentStandardsRequest",
    "UpdateContentStandardsResponse",
    "ValidateContentDeliveryRequest",
    "ValidateContentDeliveryResponse",
    # V3 Sponsored Intelligence
    "SiCapabilities",
    "SiGetOfferingRequest",
    "SiGetOfferingResponse",
    "SiIdentity",
    "SiInitiateSessionRequest",
    "SiInitiateSessionResponse",
    "SiSendMessageRequest",
    "SiSendMessageResponse",
    "SiTerminateSessionRequest",
    "SiTerminateSessionResponse",
    "SiUiElement",
    # V3 Governance (Collection Lists)
    "CollectionList",
    "CollectionListChangedWebhook",
    "CollectionListFilters",
    "CreateCollectionListRequest",
    "CreateCollectionListResponse",
    "DeleteCollectionListRequest",
    "DeleteCollectionListResponse",
    "GetCollectionListRequest",
    "GetCollectionListResponse",
    "ListCollectionListsRequest",
    "ListCollectionListsResponse",
    "UpdateCollectionListRequest",
    "UpdateCollectionListResponse",
    # V3 Governance (Property Lists)
    "CreatePropertyListRequest",
    "CreatePropertyListResponse",
    "DeletePropertyListRequest",
    "DeletePropertyListResponse",
    "GetPropertyListRequest",
    "GetPropertyListResponse",
    "ListPropertyListsRequest",
    "ListPropertyListsResponse",
    "PropertyList",
    "PropertyListChangedWebhook",
    "PropertyListFilters",
    "PropertyListReference",
    "UpdatePropertyListRequest",
    "UpdatePropertyListResponse",
    "UpdateRightsRequest",
    "UpdateRightsResponse",
    # Catalog types
    "Catalog",
    "CatalogAction",
    "CatalogFieldBinding",
    "CatalogFieldBinding1",
    "CatalogGroupBinding",
    "CatalogFieldMapping",
    "CatalogItemStatus",
    "CatalogRequirements",
    "CatalogType",
    "ContentIdType",
    "Gtin",
    "OfferingAssetConstraint",
    "OfferingAssetGroup",
    # Domain types
    "Asset",
    "AssetContentType",
    "AssetType",  # Deprecated
    "AdvertiserIndustry",
    "AudienceSource",
    "BrandReference",
    "BrandSource",
    "BusinessEntity",
    "BusinessEntityResponse",
    "BuyingMode",
    "ContextObject",
    "DateRange",
    "DatetimeRange",
    "Duration",
    "AssignedPackage",
    "Assignments",
    "CreativeAgentCapability",
    "CoBrandingRequirement",
    "Colors",
    "Contact",
    "Creative",
    "CreativeAgent",
    "CreativeApproval",
    "CreativeApprovalStatus",
    "CreativeAsset",
    "CreativeAssignment",
    "CreativeFilters",
    "CreativeManifest",
    "CreativePolicy",
    "CreativeVariant",
    "DevicePlatform",
    "DeviceType",
    "DeliveryMeasurement",
    "DeliveryMetrics",
    "DeliveryStatus",
    "DoohMetrics",
    "Error",
    "ErrorCode",
    "EventType",
    "ExtensionObject",
    "FeedFormat",
    "Fonts",
    "Format",
    "FormatCard",
    "FormatCardDetailed",
    "FormatId",
    "FormatIdParameter",
    "FormatReferenceStructuredObject",
    "Identifier",
    "Input",
    "KellerType",
    "LandingPageRequirement",
    "Logo",
    "ListCreativesField",
    "GetProductsField",
    "GetBrandIdentityField",
    "MediaBuy",
    "MediaBuyPackage",
    "MediaChannel",
    "Metadata",
    "Offering",
    "OptimizationGoal",
    "OutcomeMeasurement",
    "Overlay",
    "Package",
    "PackageRequest",
    "PackageUpdate",
    "Parameters",
    "PerformanceFeedback",
    "Placement",
    "Preview",
    "PreviewRender",
    "Product",
    "ProductCard",
    "Proposal",
    "ProductCardDetailed",
    "ProductFilters",
    "Property",
    "QuartileData",
    "Request",
    "Response",
    "Results",
    "SchemaVariant",
    "Signal",
    "SignalFilters",
    "SignalPricingOption",
    "Snapshot",
    "SnapshotUnavailableReason",
    "Tags",
    "TargetingOverlay",
    "Transform",
    "VenueBreakdownItem",
    # Pricing types
    "CpaPricingOption",
    "CpcPricingOption",
    "CpcvPricingOption",
    "CpmPricingOption",
    "CppPricingOption",
    "CpvPricingOption",
    "FlatRatePricingOption",
    "PriceGuidance",
    "TimeBasedPricingOption",
    "TimeUnit",
    "VcpmPricingOption",
    # Status enums & simple types
    "SignalCatalogType",
    "Country",
    "CreativeStatus",
    "DaastVersion",
    "DeliveryType",
    "SortDirection",
    "FeedbackSource",
    "FieldModel",
    "FrequencyCap",
    "FrequencyCapScope",
    "GeoCountry",
    "GeoMetro",
    "GeoPostalArea",
    "GeoRegion",
    "MarkdownFlavor",
    "MeasurementPeriod",
    "MediaBuyStatus",
    "HttpMethod",
    "MetricType",
    "JavascriptModuleType",
    "NotificationType",
    "PreviewOutputFormat",
    "Pacing",
    "Pagination",
    "PaginationRequest",
    "PaginationResponse",
    "PricingModel",
    "PrimaryCountry",
    "PropertyIdentifierTypes",
    "PropertyType",
    "PublisherDomain",
    "PublisherIdentifierTypes",
    "WebhookResponseType",
    "AiTool",
    "Dimensions",
    "MediaBuyFeatures",
    "Renders",
    "Responsive",
    "Sort",
    "Status",
    "TaskType",
    "DaastTrackingEvent",
    "VastTrackingEvent",
    "DimensionUnit",
    "UpdateFrequency",
    "UrlAssetType",
    "ValidationMode",
    "VastVersion",
    "ViewThreshold",
    "WcagLevel",
    # Configuration & infrastructure types
    "Authentication",
    "AuthorizedAgents",
    "AvailableMetric",
    "PushNotificationConfig",
    "ReportingCapabilities",
    "ReportingFrequency",
    "ReportingPeriod",
    "ReportingWebhook",
    "AuthenticationScheme",
    "Security",
    "SellerAgentReference",
    # Asset-content types (payload describing types — distinct from
    # the `<Type>FormatAsset` slot types in aliases.py)
    "AudioContent",
    "CssContent",
    "HtmlContent",
    "ImageContent",
    "JavascriptContent",
    "TextContent",
    "UrlContent",
    "VideoContent",
    "WebhookContent",
    # Core types
    "AgentConfig",
    "Member",
    "Policy",
    "PolicyExemplar",
    "PolicyExemplars",
    "PolicyHistory",
    "PolicyRevision",
    "PolicySummary",
    "Protocol",
    "ResolvedBrand",
    "ResolvedProperty",
    "TaskResult",
    "WebhookMetadata",
    # Webhook types
    "McpWebhookPayload",
    # Semantic aliases for discriminated unions
    "ActivateSignalErrorResponse",
    "ActivateSignalSuccessResponse",
    "AgentDeployment",
    "AgentDestination",
    "AuthorizedAgent",
    "AuthorizedAgentsByInlineProperties",
    "AuthorizedAgentsByPropertyId",
    "AuthorizedAgentsByPropertyTag",
    "AuthorizedAgentsByPublisherProperties",
    "AuthorizedAgentsBySignalId",
    "AuthorizedAgentsBySignalTag",
    "BothPreviewRender",
    "BuildCreativeErrorResponse",
    "BuildCreativeSuccessResponse",
    "CalibrateContentErrorResponse",
    "CalibrateContentSuccessResponse",
    "CreateContentStandardsErrorResponse",
    "CreateContentStandardsSuccessResponse",
    "CreateMediaBuyErrorResponse",
    "CreateMediaBuySubmittedResponse",
    "CreateMediaBuySuccessResponse",
    "Deployment",
    "Destination",
    "GetContentStandardsErrorResponse",
    "GetContentStandardsSuccessResponse",
    "GetCreativeDeliveryByBuyerRefRequest",
    "GetCreativeDeliveryByCreativeRequest",
    "GetCreativeDeliveryByMediaBuyRequest",
    "GetMediaBuyArtifactsErrorResponse",
    "GetMediaBuyArtifactsSuccessResponse",
    "GetProductsBriefRequest",
    "GetProductsRefineRequest",
    "GetProductsWholesaleRequest",
    "GetSignalsDiscoveryRequest",
    "GetSignalsLookupRequest",
    "HtmlPreviewRender",
    "InlineDaastAsset",
    "InlineVastAsset",
    "ListContentStandardsErrorResponse",
    "ListContentStandardsSuccessResponse",
    "LogEventErrorResponse",
    "LogEventSuccessResponse",
    "PlatformDeployment",
    "PlatformDestination",
    "PreviewCreativeBatchResponse",
    "PreviewCreativeSingleResponse",
    "PreviewCreativeVariantResponse",
    "PricingOption",
    "PropertyId",
    "PropertyTag",
    "ProvidePerformanceFeedbackByBuyerRefRequest",
    "ProvidePerformanceFeedbackByMediaBuyRequest",
    "ProvidePerformanceFeedbackErrorResponse",
    "ProvidePerformanceFeedbackSuccessResponse",
    "PublisherProperties",
    "PublisherPropertiesAll",
    "PublisherPropertiesById",
    "PublisherPropertiesByTag",
    "SegmentIdActivationKey",
    "KeyValueActivationKey",
    "SiSendTextMessageRequest",
    "SiSendActionResponseRequest",
    "SyncAccountsErrorResponse",
    "SyncAccountsSuccessResponse",
    "SyncCatalogResult",
    "SyncCatalogsErrorResponse",
    "SyncCatalogsSuccessResponse",
    "SyncCreativesErrorResponse",
    "SyncCreativesSuccessResponse",
    "SyncCreativeResult",
    "SyncEventSourcesErrorResponse",
    "SyncEventSourcesSuccessResponse",
    "UpdateContentStandardsErrorResponse",
    "UpdateContentStandardsSuccessResponse",
    "UpdateMediaBuyErrorResponse",
    "UpdateMediaBuyPackagesRequest",
    "UpdateMediaBuyPropertiesRequest",
    "UpdateMediaBuySuccessResponse",
    "UrlDaastAsset",
    "UrlPreviewRender",
    "UrlVastAsset",
    "ValidateContentDeliveryErrorResponse",
    "ValidateContentDeliverySuccessResponse",
    # Account financials responses
    "GetAccountFinancialsErrorResponse",
    "GetAccountFinancialsSuccessResponse",
    # Brand Rights response aliases
    "AcquireRightsAcquiredResponse",
    "AcquireRightsPendingResponse",
    "AcquireRightsRejectedResponse",
    "AcquireRightsErrorResponse",
    "GetBrandIdentitySuccessResponse",
    "GetBrandIdentityErrorResponse",
    "GetRightsSuccessResponse",
    "GetRightsErrorResponse",
    # Compliance Test Controller response aliases
    "ComplyListScenariosResponse",
    "ComplyStateTransitionResponse",
    "ComplySimulationResponse",
    "ComplyErrorResponse",
    # Creative format asset slot aliases (item_type='individual')
    "ImageFormatAsset",
    "VideoFormatAsset",
    "AudioFormatAsset",
    "TextFormatAsset",
    "MarkdownFormatAsset",
    "HtmlFormatAsset",
    "CssFormatAsset",
    "JavascriptFormatAsset",
    "VastFormatAsset",
    "DaastFormatAsset",
    "UrlFormatAsset",
    "WebhookFormatAsset",
    "BriefFormatAsset",
    "CatalogFormatAsset",
    # Creative format asset slot aliases (repeatable groups)
    "RepeatableAssetGroup",
    "ImageFormatGroupAsset",
    "VideoFormatGroupAsset",
    "AudioFormatGroupAsset",
    "TextFormatGroupAsset",
    "MarkdownFormatGroupAsset",
    "HtmlFormatGroupAsset",
    "CssFormatGroupAsset",
    "JavascriptFormatGroupAsset",
    "VastFormatGroupAsset",
    "DaastFormatGroupAsset",
    "UrlFormatGroupAsset",
    "WebhookFormatGroupAsset",
    # Audiences responses
    "MediaBuyDeliveryStatus",
    "SyncAudiencesErrorResponse",
    "SyncAudiencesSuccessResponse",
    # Creative features responses
    "GetCreativeFeaturesErrorResponse",
    "GetCreativeFeaturesSuccessResponse",
    # Internal/special exports
    "GeneratedTaskStatus",
    # Backward compatibility aliases (deprecated)
    "Action",
    "Capability",
    "CoBranding",
    "LandingPage",
    "Method",
    "ModuleType",
    "TrackingEvent",
    "Unit",
    "OutputFormat",
    "ResponseType",
    "Scheme",
    "SignalType",
    "UrlType",
    "AvailableReportingFrequency",
    # Backward compat: pricing type renames (auction/fixed merged into single types)
    "CpmAuctionPricingOption",
    "CpmFixedRatePricingOption",
    "VcpmAuctionPricingOption",
    "VcpmFixedRatePricingOption",
    # Backward compat: activation key schema change
    "PropertyIdActivationKey",
    "PropertyTagActivationKey",
    # Backward compat: preview alias renames
    "PreviewCreativeFormatRequest",
    "PreviewCreativeManifestRequest",
    "PreviewCreativeStaticResponse",
    "PreviewCreativeInteractiveResponse",
    # Backward compat: types removed from upstream schemas
    # Backward compat: types removed from exports (deprecated)
    "Disclaimer",
    "MediaSubAsset",
    "Performance",
    "ProductCatalog",
    "TextSubAsset",
    # Response-shape projection helpers
    "to_account_response",
    # Submodules for advanced use:
    "generated",
    "aliases",
]
