"""AdCP Type System.

All AdCP types exported from a single location.
Users should import from here or directly from adcp.

    from adcp.types import Product, CreativeFilters
    from adcp import Product, CreativeFilters

This package is lazy: ``import adcp.types`` is cheap and does not build the
generated Pydantic schema graph. The graph (and its import-time coercion /
forward-compat patching) is realized on first access to any type symbol,
via :mod:`adcp.types._eager`. So ``from adcp.types import Product`` works as
a stable compatibility path, resolved through ``__getattr__`` (PEP 562).

For a narrower, curated surface, import a partial module instead:

    from adcp.types.media_buy import CreateMediaBuyRequest
    from adcp.types.creative import Format
    from adcp.types.signals import GetSignalsRequest
    from adcp.types.protocol import Error, Pagination
    from adcp.types.buyer import GetProductsRequest
    from adcp.types.seller import Offering, PropertyList

IMPORTANT: Never import directly from adcp.types.generated_poc or
adcp.types._generated. These are internal modules regenerated from
upstream schemas. Only import from adcp.types (this module), one of the
partial modules above, or adcp.

Type Coercion:
    Request types accept flexible input for developer ergonomics:

    - Enum fields accept string values:
        ListCreativeFormatsRequest(type="video")  # Works!

    - Context fields accept dicts:
        GetProductsRequest(context={"key": "value"})  # Works!

    - FieldModel lists accept strings:
        ListCreativesRequest(fields=["creative_id", "name"])  # Works!

    See adcp.types._ergonomic for implementation details.
"""

from __future__ import annotations

import importlib
import importlib.util
from typing import TYPE_CHECKING

__pdoc__ = {
    "generated_poc": False,
    "mypy_plugin": False,
    "_eager": False,
}

__all__ = [
    # A2UI types
    "A2UiComponent",
    "A2UiSurface",
    # Account types
    "Account",
    "AccountAuthorization",
    "AccountReference",
    "AccountReferenceById",
    "AccountReferenceByNaturalKey",
    "AccountResponse",
    "AccountScope",
    "AccountWithAuthorization",
    "CreditLimit",
    "GetAccountFinancialsRequest",
    "GetAccountFinancialsResponse",
    "GovernanceAgent",
    "ListAccountsRequest",
    "ListAccountsResponse",
    "PaymentTerms",
    "ReportUsageRequest",
    "ReportUsageResponse",
    "ReportingBucket",
    "Setup",
    "SyncAccountsRequest",
    "SyncAccountsResponse",
    # Request/Response types
    "ActivateSignalRequest",
    "ActivateSignalResponse",
    "ActivateSignalResponse1",
    "AdcpProtocol",
    "AuthorizationRequiredDetails",
    "CreativeAction",
    "AggregatedTotals",
    "BuildCreativeRequest",
    "BuildCreativeResponse",
    "ByCatalogItemItem",
    "ByPackageItem",
    "CreateMediaBuyRequest",
    "CreateMediaBuyResponse",
    "DailyBreakdownItem",
    "GetMediaBuyDeliveryRequest",
    "GetMediaBuyDeliveryResponse",
    "GetMediaBuysRequest",
    "GetMediaBuysResponse",
    "GetProductsRequest",
    "GetProductsResponse",
    "GetSignalsRequest",
    "GetSignalsResponse",
    "DownstreamConnectionRequirement",
    "ListCreativeFormatsRequest",
    "ListCreativeFormatsResponse",
    "ListCreativesRequest",
    "ListCreativesResponse",
    "MediaBuyDelivery",
    "PreviewCreativeRequest",
    "PreviewCreativeResponse",
    "ProtocolEnvelope",
    "ProtocolResponse",
    "ProvidePerformanceFeedbackRequest",
    "ProvidePerformanceFeedbackResponse",
    "QuerySummary",
    "Refine",
    "RefinementApplied",
    "RefinementApplied1",
    "RefinementApplied2",
    "RefinementApplied3",
    "SortApplied",
    "StatusSummary",
    "SyncCatalogsInputRequired",
    "SyncCatalogsRequest",
    "SyncCatalogsResponse",
    "SyncCatalogsSubmitted",
    "SyncCatalogsWorking",
    "SyncAudiencesAudience",
    "SyncAudiencesRequest",
    "SyncAudiencesResponse",
    "ConsentBasis",
    "SyncCreativesRequest",
    "SyncCreativesResponse",
    # Event & Source Operations
    "LogEventRequest",
    "LogEventResponse",
    "SyncEventSourcesRequest",
    "SyncEventSourcesResponse",
    "Totals",
    "UpdateMediaBuyRequest",
    "UpdateMediaBuyResponse",
    # V3 Protocol Discovery
    "GetAdcpCapabilitiesRequest",
    "GetAdcpCapabilitiesResponse",
    "GetTaskStatusRequest",
    "GetTaskStatusResponse",
    "ListTasksRequest",
    "ListTasksResponse",
    "ListTransformersRequest",
    "ListTransformersResponse",
    # TMP (Temporal Matching Protocol)
    "AvailablePackage",
    "ContextMatchRequest",
    "ContextMatchResponse",
    "IdentityMatchRequest",
    "IdentityMatchResponse",
    "TmpOffer",
    "OfferPrice",
    "TmpError",
    # Brand Rights
    "AcquireRightsRequest",
    "AcquireRightsResponse",
    "GetBrandIdentityRequest",
    "GetBrandIdentityResponse",
    "GetRightsRequest",
    "GetRightsResponse",
    "VerifyBrandClaimPayload",
    "VerifyBrandClaimRequest",
    "VerifyBrandClaimResponse",
    "VerifyBrandClaimSignedResponse",
    "VerifyBrandClaimSignedSuccessPayload",
    "VerifyBrandClaimsErrorResponse",
    "VerifyBrandClaimsPayload",
    "VerifyBrandClaimsRequest",
    "VerifyBrandClaimsRequestBulk",
    "VerifyBrandClaimsResponse",
    "VerifyBrandClaimsResponseBulk",
    "VerifyBrandClaimsSignedResponse",
    "VerifyBrandClaimsSignedSuccessPayload",
    "RightsPricingOption",
    "RightsTerms",
    # Compliance Test Controller
    "ComplyTestControllerRequest",
    "ComplyTestControllerResponse",
    "ComplyTestControllerResponse1",
    # Creative Delivery
    "GetCreativeDeliveryRequest",
    "GetCreativeDeliveryResponse",
    "ValidateInputRequest",
    "ValidateInputResponse",
    # Creative Features
    "GetCreativeFeaturesRequest",
    "GetCreativeFeaturesResponse",
    "GetCreativeFeaturesResponse1",
    # V3 Governance
    "CheckGovernanceRequest",
    "CheckGovernanceResponse",
    "GetPlanAuditLogsRequest",
    "GetPlanAuditLogsResponse",
    "ReportPlanOutcomeRequest",
    "ReportPlanOutcomeResponse",
    "SyncGovernanceRequest",
    "SyncGovernanceResponse",
    "SyncPlansRequest",
    "SyncPlansResponse",
    # Forecasting types
    "DayOfWeek",
    "DaypartTarget",
    "DeliveryForecast",
    "DemographicSystem",
    "ForecastMethod",
    "ForecastPoint",
    "ForecastRange",
    "ForecastRangeUnit",
    "ForecastableMetric",
    "ReachUnit",
    # V3 Content Standards
    "Artifact",
    "ArtifactWebhookPayload",
    "CalibrateContentRequest",
    "CalibrateContentResponse",
    "ContentStandards",
    "CreateContentStandardsRequest",
    "CreateContentStandardsResponse",
    "GetContentStandardsRequest",
    "GetContentStandardsResponse",
    "GetMediaBuyArtifactsRequest",
    "GetMediaBuyArtifactsResponse",
    "ListContentStandardsRequest",
    "ListContentStandardsResponse",
    "UpdateContentStandardsRequest",
    "UpdateContentStandardsResponse",
    "ValidateContentDeliveryRequest",
    "ValidateContentDeliveryResponse",
    # V3 Sponsored Intelligence
    "SiCapabilities",
    "SiGetOfferingRequest",
    "SiGetOfferingResponse",
    "SiIdentity",
    "SiInitiateSessionRequest",
    "SiInitiateSessionResponse",
    "SiSendMessageRequest",
    "SiSendMessageResponse",
    "SiTerminateSessionRequest",
    "SiTerminateSessionResponse",
    "SiUiElement",
    # V3 Governance (Collection Lists)
    "CollectionList",
    "CollectionListChangedWebhook",
    "CollectionListFilters",
    "CreateCollectionListRequest",
    "CreateCollectionListResponse",
    "DeleteCollectionListRequest",
    "DeleteCollectionListResponse",
    "GetCollectionListRequest",
    "GetCollectionListResponse",
    "ListCollectionListsRequest",
    "ListCollectionListsResponse",
    "UpdateCollectionListRequest",
    "UpdateCollectionListResponse",
    # V3 Governance (Property Lists)
    "CreatePropertyListRequest",
    "CreatePropertyListResponse",
    "DeletePropertyListRequest",
    "DeletePropertyListResponse",
    "GetPropertyListRequest",
    "GetPropertyListResponse",
    "ListPropertyListsRequest",
    "ListPropertyListsResponse",
    "PropertyList",
    "PropertyListChangedWebhook",
    "PropertyListFilters",
    "PropertyListReference",
    "UpdatePropertyListRequest",
    "UpdatePropertyListResponse",
    "UpdateRightsRequest",
    "UpdateRightsResponse",
    # Catalog types
    "Catalog",
    "CatalogAction",
    "CatalogFieldBinding",
    "CatalogFieldBinding1",
    "CatalogGroupBinding",
    "CatalogFieldMapping",
    "CatalogItemStatus",
    "CatalogRequirements",
    "CatalogType",
    "ContentIdType",
    "Gtin",
    "OfferingAssetConstraint",
    "OfferingAssetGroup",
    # Domain types
    "Asset",
    "AssetContentType",
    "AssetType",  # Deprecated
    "AdvertiserIndustry",
    "AudienceSource",
    "BrandReference",
    "BrandSource",
    "BusinessEntity",
    "BusinessEntityResponse",
    "BuyingMode",
    "ContextObject",
    "DateRange",
    "DatetimeRange",
    "Duration",
    "AssignedPackage",
    "Assignments",
    "CreativeAgentCapability",
    "CoBrandingRequirement",
    "Colors",
    "Contact",
    "Creative",
    "CreativeAgent",
    "CreativeApproval",
    "CreativeApprovalStatus",
    "CreativeAsset",
    "CreativeAssignment",
    "CreativeFilters",
    "CreativeManifest",
    "CreativePolicy",
    "CreativeVariant",
    "DevicePlatform",
    "DeviceType",
    "DeliveryMeasurement",
    "DeliveryMetrics",
    "DeliveryStatus",
    "DoohMetrics",
    "Error",
    "ErrorCode",
    "EventType",
    "ExtensionObject",
    "FeedFormat",
    "Fonts",
    "Format",
    "FormatCard",
    "FormatCardDetailed",
    # Canonical-formats v2 surface (AdCP 3.1)
    "CanonicalAssetSource",
    "CanonicalCompositionModel",
    "CanonicalFormatAgentPlacement",
    "CanonicalFormatBase",
    "CanonicalFormatDaastAudio",
    "CanonicalFormatDisplayTag",
    "CanonicalFormatHostedAudio",
    "CanonicalFormatHostedVideo",
    "CanonicalFormatHtml5Banner",
    "CanonicalFormatImage",
    "CanonicalFormatImageCarousel",
    "CanonicalFormatKind",
    "CanonicalFormatNativeInFeed",
    "CanonicalFormatResponsiveCreative",
    "CanonicalFormatSponsoredPlacement",
    "CanonicalFormatVastVideo",
    "CanonicalProjectionReference",
    "CanonicalSlotOverride",
    "FormatId",
    "FormatIdParameter",
    "FormatOptionReference",
    "PixelTrackerAsset",
    "PixelTrackerEvent",
    "PixelTrackerMethod",
    "Recovery",
    "Source",
    "ProductFormatDeclaration",
    "ProductFormatSellerPreference",
    "V1CanonicalDimensions",
    "V1CanonicalGlobPattern",
    "V1CanonicalMapping",
    "V1CanonicalStructural",
    "V1CanonicalStructuralPattern",
    "V1CanonicalV2Projection",
    "V1V2CanonicalFormatMappingRegistry",
    "FormatReferenceStructuredObject",
    "Identifier",
    "Input",
    "KellerType",
    "LandingPageRequirement",
    "Logo",
    "ListCreativesField",
    "GetProductsField",
    "GetBrandIdentityField",
    "MediaBuy",
    "MediaBuyPackage",
    "MediaChannel",
    "Metadata",
    "Offering",
    "OptimizationGoal",
    "OutcomeMeasurement",
    "Overlay",
    "Package",
    "PackageRequest",
    "PackageSignalTargeting",
    "PackageSignalTargetingGroup",
    "PackageSignalTargetingGroups",
    "PackageUpdate",
    "Parameters",
    "PerformanceFeedback",
    "Placement",
    "PlacementReference",
    "PostalArea",
    "Preview",
    "PreviewRender",
    "Product",
    "ProductCard",
    "Proposal",
    "ProductCardDetailed",
    "ProductFilters",
    "ProductSignalTargetingOption",
    "Property",
    "QuartileData",
    "Request",
    "Response",
    "ResponsePayloadJwsEnvelope",
    "Results",
    "SchemaVariant",
    "Signal",
    "SignalDefinitionEnrichment",
    "SignalFilters",
    "SignalListing",
    "SignalPricingOption",
    "SignalRef",
    "SignalTargeting",
    "SignalTargetingExpression",
    "SignalTargetingRules",
    "Snapshot",
    "SnapshotUnavailableReason",
    "Tags",
    "TargetingOverlay",
    "Transform",
    "VenueBreakdownItem",
    # Pricing types
    "CpaPricingOption",
    "CpcPricingOption",
    "CpcvPricingOption",
    "CpmPricingOption",
    "CppPricingOption",
    "CpvPricingOption",
    "FlatRatePricingOption",
    "PriceGuidance",
    "PricingCurrency",
    "TimeBasedPricingOption",
    "TimeUnit",
    "VcpmPricingOption",
    "WebhookChallenge",
    "WebhookChallengeResponse",
    # Status enums & simple types
    "SignalAvailabilityType",
    "SignalCatalogType",
    "Country",
    "CreativeStatus",
    "DaastVersion",
    "DeliveryType",
    "SortDirection",
    "FeedbackSource",
    "FieldModel",
    "FrequencyCap",
    "FrequencyCapScope",
    "GeoCountry",
    "GeoMetro",
    "GeoRegion",
    "MarkdownFlavor",
    "MeasurementPeriod",
    "MediaBuyDeliveryWebhookResult",
    "MediaBuyStatus",
    "HttpMethod",
    "MetricType",
    "JavascriptModuleType",
    "NotificationType",
    "PreviewOutputFormat",
    "Pacing",
    "Pagination",
    "PaginationRequest",
    "PaginationResponse",
    "PricingModel",
    "PrimaryCountry",
    "PropertyIdentifierTypes",
    "PropertyType",
    "PublisherDomain",
    "PublisherIdentifierTypes",
    "WebhookResponseType",
    "AiTool",
    "Dimensions",
    "MediaBuyFeatures",
    "Renders",
    "Responsive",
    "Sort",
    "Status",
    "TaskType",
    "DaastTrackingEvent",
    "VastTrackingEvent",
    "DimensionUnit",
    "UpdateFrequency",
    "UrlAssetType",
    "ValidationMode",
    "VastVersion",
    "ViewThreshold",
    "WcagLevel",
    # Configuration & infrastructure types
    "Authentication",
    "AuthorizedAgents",
    "AvailableMetric",
    "NotificationConfig",
    "PushNotificationConfig",
    "ReportingCapabilities",
    "WholesaleFeedEvent",
    "WholesaleFeedWebhook",
    "ReportingFrequency",
    "ReportingPeriod",
    "ReportingWebhook",
    "AuthenticationScheme",
    "Security",
    "SellerAgentReference",
    # Asset-content types (payload describing types — distinct from
    # the `<Type>FormatAsset` slot types in aliases.py)
    "AudioContent",
    "CssContent",
    "HtmlContent",
    "ImageContent",
    "JavascriptContent",
    "TextContent",
    "UrlContent",
    "VideoContent",
    "WebhookContent",
    # Core types
    "AgentConfig",
    "Member",
    "Policy",
    "PolicyExemplar",
    "PolicyExemplars",
    "PolicyHistory",
    "PolicyRevision",
    "PolicySummary",
    "Protocol",
    "ResolvedBrand",
    "ResolvedProperty",
    "TaskResult",
    "WebhookMetadata",
    # Webhook types
    "McpWebhookPayload",
    "WholesaleFeedEvent",
    "WholesaleFeedWebhook",
    # Semantic aliases for discriminated unions
    "ActivateSignalErrorResponse",
    "ActivateSignalSuccessResponse",
    "AgentDeployment",
    "AgentDestination",
    "AuthorizedAgent",
    "AuthorizedAgentsByInlineProperties",
    "AuthorizedAgentsByPropertyId",
    "AuthorizedAgentsByPropertyTag",
    "AuthorizedAgentsByPublisherProperties",
    "AuthorizedAgentsBySignalId",
    "AuthorizedAgentsBySignalTag",
    "BothPreviewRender",
    "BuildCreativeErrorResponse",
    "BuildCreativeResponse1",
    "BuildCreativeSubmittedResponse",
    "BuildCreativeSuccessResponse",
    "CalibrateContentErrorResponse",
    "CalibrateContentResponse1",
    "CalibrateContentSuccessResponse",
    "CreateContentStandardsErrorResponse",
    "CreateContentStandardsResponse1",
    "CreateContentStandardsSuccessResponse",
    "CreateMediaBuyErrorResponse",
    "CreateMediaBuyResponse1",
    "CreateMediaBuySubmittedResponse",
    "CreateMediaBuySuccessResponse",
    "Deployment",
    "Destination",
    "GetContentStandardsErrorResponse",
    "GetContentStandardsResponse1",
    "GetContentStandardsSuccessResponse",
    "GetCreativeDeliveryByBuyerRefRequest",
    "GetCreativeDeliveryByCreativeRequest",
    "GetCreativeDeliveryByMediaBuyRequest",
    "GetMediaBuyArtifactsErrorResponse",
    "GetMediaBuyArtifactsResponse1",
    "GetMediaBuyArtifactsSuccessResponse",
    "GetProductsBriefRequest",
    "GetProductsInputRequiredResponse",
    "GetProductsRefineRequest",
    "GetProductsResponseUnion",
    "GetProductsSubmittedResponse",
    "GetProductsSuccessResponse",
    "GetProductsWholesaleRequest",
    "GetProductsWorkingResponse",
    "GetSignalsDiscoveryRequest",
    "GetSignalsLookupRequest",
    "GetSignalsResponseUnion",
    "GetSignalsSubmittedResponse",
    "GetSignalsSuccessResponse",
    "GetSignalsWorkingResponse",
    "HtmlPreviewRender",
    "InlineDaastAsset",
    "InlineVastAsset",
    "ListContentStandardsErrorResponse",
    "ListContentStandardsResponse1",
    "ListContentStandardsSuccessResponse",
    "LogEventErrorResponse",
    "LogEventResponse1",
    "LogEventSuccessResponse",
    "PlatformDeployment",
    "PlatformDestination",
    "PreviewCreativeBatchResponse",
    "PreviewCreativeResponse1",
    "PreviewCreativeSingleResponse",
    "PreviewCreativeVariantResponse",
    "PricingOption",
    "PropertyId",
    "PropertyTag",
    "ProvidePerformanceFeedbackByBuyerRefRequest",
    "ProvidePerformanceFeedbackByMediaBuyRequest",
    "ProvidePerformanceFeedbackErrorResponse",
    "ProvidePerformanceFeedbackResponse1",
    "ProvidePerformanceFeedbackSuccessResponse",
    "PublisherProperties",
    "PublisherPropertiesAll",
    "PublisherPropertiesById",
    "PublisherPropertiesByTag",
    "SegmentIdActivationKey",
    "KeyValueActivationKey",
    "SiSendTextMessageRequest",
    "SiSendActionResponseRequest",
    "SyncAccountsErrorResponse",
    "SyncAccountsResponse1",
    "SyncAccountsSuccessResponse",
    "SyncAudiencesResponse1",
    "SyncCatalogResult",
    "SyncCatalogsErrorResponse",
    "SyncCatalogsResponse1",
    "SyncCatalogsSubmittedResponse",
    "SyncCatalogsSuccessResponse",
    "SyncCreativesErrorResponse",
    "SyncCreativesResponse1",
    "SyncCreativesResponse3",
    "SyncCreativesSubmittedResponse",
    "SyncCreativesSuccessResponse",
    "SyncCreativeResult",
    "SyncEventSourcesErrorResponse",
    "SyncEventSourcesResponse1",
    "SyncEventSourcesSuccessResponse",
    "UpdateContentStandardsErrorResponse",
    "UpdateContentStandardsResponse1",
    "UpdateContentStandardsSuccessResponse",
    "UpdateMediaBuyErrorResponse",
    "UpdateMediaBuyResponse1",
    "UpdateMediaBuyResponse3",
    "UpdateMediaBuyPackagesRequest",
    "UpdateMediaBuyPropertiesRequest",
    "UpdateMediaBuySubmittedResponse",
    "UpdateMediaBuySuccessResponse",
    "UrlDaastAsset",
    "UrlPreviewRender",
    "UrlVastAsset",
    "ValidateContentDeliveryErrorResponse",
    "ValidateContentDeliveryResponse1",
    "ValidateContentDeliverySuccessResponse",
    # Account financials responses
    "GetAccountFinancialsErrorResponse",
    "GetAccountFinancialsResponse1",
    "GetAccountFinancialsSuccessResponse",
    # Brand Rights response aliases
    "AcquireRightsAcquiredResponse",
    "AcquireRightsPendingResponse",
    "AcquireRightsRejectedResponse",
    "AcquireRightsErrorResponse",
    "AcquireRightsResponse1",
    "GetBrandIdentitySuccessResponse",
    "GetBrandIdentityErrorResponse",
    "GetBrandIdentityResponse1",
    "GetRightsSuccessResponse",
    "GetRightsErrorResponse",
    "GetRightsResponse1",
    # Compliance Test Controller response aliases
    "ComplyListScenariosResponse",
    "ComplyStateTransitionResponse",
    "ComplySimulationResponse",
    "ComplyErrorResponse",
    # Creative format asset slot aliases (item_type='individual')
    # Forward-compat fallback arms (novel asset_type values parse as these)
    "UnknownFormatAsset",
    "UnknownGroupAsset",
    # Open union types for Format.assets / RepeatableAssetGroup.assets
    "FormatAssetUnion",
    "GroupFormatAssetUnion",
    "ImageFormatAsset",
    "VideoFormatAsset",
    "AudioFormatAsset",
    "TextFormatAsset",
    "MarkdownFormatAsset",
    "HtmlFormatAsset",
    "CssFormatAsset",
    "JavascriptFormatAsset",
    "VastFormatAsset",
    "DaastFormatAsset",
    "UrlFormatAsset",
    "WebhookFormatAsset",
    "BriefFormatAsset",
    "CatalogFormatAsset",
    # Creative format asset slot aliases (repeatable groups)
    "RepeatableAssetGroup",
    "ImageFormatGroupAsset",
    "VideoFormatGroupAsset",
    "AudioFormatGroupAsset",
    "TextFormatGroupAsset",
    "MarkdownFormatGroupAsset",
    "HtmlFormatGroupAsset",
    "CssFormatGroupAsset",
    "JavascriptFormatGroupAsset",
    "VastFormatGroupAsset",
    "DaastFormatGroupAsset",
    "UrlFormatGroupAsset",
    "WebhookFormatGroupAsset",
    # Audiences responses
    "MediaBuyDeliveryStatus",
    "SyncAudiencesErrorResponse",
    "SyncAudiencesSubmittedResponse",
    "SyncAudiencesSuccessResponse",
    # Creative features responses
    "GetCreativeFeaturesErrorResponse",
    "GetCreativeFeaturesSuccessResponse",
    # Internal/special exports
    "GeneratedTaskStatus",
    # Backward compatibility aliases (deprecated)
    "Action",
    "Capability",
    "CoBranding",
    "LandingPage",
    "Method",
    "ModuleType",
    "TrackingEvent",
    "Unit",
    "OutputFormat",
    "ResponseType",
    "Scheme",
    "SignalType",
    "UrlType",
    "AvailableReportingFrequency",
    # Backward compat: pricing type renames (auction/fixed merged into single types)
    "CpmAuctionPricingOption",
    "CpmFixedRatePricingOption",
    "VcpmAuctionPricingOption",
    "VcpmFixedRatePricingOption",
    # Backward compat: activation key schema change
    "PropertyIdActivationKey",
    "PropertyTagActivationKey",
    # Backward compat: preview alias renames. The per-mode *Request variants
    # (PreviewCreativeFormatRequest / PreviewCreativeManifestRequest) were
    # removed upstream when PreviewCreativeRequest collapsed to a single class
    # with a request_type discriminator — use PreviewCreativeRequest directly.
    "PreviewCreativeStaticResponse",
    "PreviewCreativeInteractiveResponse",
    # Backward compat: types removed from upstream schemas
    # Backward compat: types removed from exports (deprecated)
    "Disclaimer",
    "MediaSubAsset",
    "Performance",
    "ProductCatalog",
    "TextSubAsset",
    # Response-shape projection helpers
    "project_geo_postal_areas",
    "to_account_response",
    # Cross-module name collision aliases (#911, Step 2)
    # Creative
    "DeliveryCreative",
    "ListCreativesCreative",
    "ListCreativesLegacyCreative",
    "ListCreativesCanonicalCreative",
    "ListCreativesCreativeItem",
    "SyncCreativesCreative",
    "BuildCreativeCreative",
    "CapabilitiesCreative",
    # Account
    "CoreAccount",
    "SyncAccountsAccount",
    "SyncGovernanceAccount",
    "CapabilitiesAccount",
    # Authentication
    "PushNotificationAuthentication",
    "NotificationAuthentication",
    "ReportingWebhookAuthentication",
    "GovernanceAuthentication",
    "CreateMediaBuyAuthentication",
    # MediaBuy
    "CoreMediaBuy",
    "GetMediaBuysMediaBuy",
    "CapabilitiesMediaBuy",
    # GovernanceAgent
    "CoreGovernanceAgent",
    "SyncGovernanceGovernanceAgent",
    # CreditLimit
    "CoreCreditLimit",
    "SyncAccountsCreditLimit",
    # Setup
    "CoreSetup",
    "SyncAccountsSetup",
    "SyncEventSourcesSetup",
    # Sort
    "ListCreativesSort",
    "TasksListSort",
    "ListTasksSort",
    # Signal
    "GetSignalsSignal",
    "WholesaleFeedSignal",
    # DeclaredBy
    "ProvenanceDeclaredBy",
    "SiSponsoredContextDeclaredBy",
    # TmpxMacro
    "IdentityMatchTmpxMacro",
    "ProviderRegistrationTmpxMacro",
    # Unit
    "DurationUnit",
    "OverlayUnit",
    "RealEstateUnit",
    "VehicleUnit",
    # Curated partial surfaces (lazy submodules):
    "media_buy",
    "creative",
    "signals",
    "protocol",
    "buyer",
    "seller",
    # Submodules for advanced use:
    "generated",
    "aliases",
]

# Curated partial-surface submodules, advertised in ``__all__`` (resolved as
# real submodules by ``__getattr__`` below — see the submodule passthrough).
_PARTIAL_MODULES = frozenset({"media_buy", "creative", "signals", "protocol", "buyer", "seller"})

# Names importable from ``adcp.types`` but intentionally NOT in ``__all__``:
# internal re-export helpers (response type guards + a few normalization
# helpers) kept on this surface for backwards compatibility. ``__getattr__``
# treats these as resolvable; the documented public list stays ``__all__``.
# ``tests/test_lazy_types.py`` fails if this drifts from what ``_eager`` binds.
_EAGER_ONLY_EXTRAS = frozenset(
    {
        "Field1",
        "MEDIA_BUY_LEGACY_STATUS_VALUES",
        "Measurement",
        "unwrap_enum_value",
        "is_activate_signal_error",
        "is_activate_signal_success",
        "is_adcp_error",
        "is_adcp_success",
        "is_build_creative_error",
        "is_build_creative_submitted",
        "is_build_creative_success",
        "is_calibrate_content_success",
        "is_create_media_buy_error",
        "is_create_media_buy_success",
        "is_get_account_financials_error",
        "is_get_account_financials_success",
        "is_get_creative_features_success",
        "is_log_event_error",
        "is_log_event_success",
        "is_performance_feedback_error",
        "is_performance_feedback_success",
        "is_sync_accounts_error",
        "is_sync_accounts_success",
        "is_sync_catalogs_error",
        "is_sync_catalogs_submitted",
        "is_sync_catalogs_success",
        "is_sync_creatives_error",
        "is_sync_creatives_submitted",
        "is_sync_creatives_success",
        "is_update_media_buy_error",
        "is_update_media_buy_success",
        "is_validate_content_delivery_success",
    }
)

# Names ``__getattr__`` resolves from the eager graph. Anything else fails fast
# (``AttributeError``) without paying to build the schema graph — so typos and
# ``hasattr`` probes for unknown names stay cheap.
_RESOLVABLE = frozenset(__all__) | _EAGER_ONLY_EXTRAS


# Deprecated backward-compat alias (kept out of ``__all__``).
#
# AdCP 3.1.0-rc.10 restructured postal-area targeting: the inline
# ``{system, values}`` ``GeoPostalArea`` shape became the ``PostalArea``
# union (``core/postal-area.json``) of a native per-country arm
# (``{country, system, values}``) and a legacy arm (``{system, values}``
# with country-fused tokens like ``us_zip``). The legacy arm
# (``PostalArea5``) has the same shape and accepts the same fused tokens as
# the removed ``GeoPostalArea``, so old construction code keeps working when
# ``GeoPostalArea`` resolves to it. The constructed value still validates
# against the ``PostalArea`` union via the legacy arm.
_DEPRECATION_MESSAGE = (
    "GeoPostalArea is deprecated; use PostalArea (the native per-country arm "
    "with country + postal system) instead. The legacy alias maps to the "
    "PostalArea legacy arm ({system, values} with country-fused tokens like "
    "'us_zip') and is retained for backward compatibility and removed in a "
    "future major."
)


if not TYPE_CHECKING:
    # Defined under ``not TYPE_CHECKING`` so type checkers do not see a module-
    # level ``__getattr__`` (which would silence missing-attribute errors and
    # type every unknown name as ``object``). Type checkers get the surface from
    # the explicit ``TYPE_CHECKING`` block below, so a typo'd import is flagged;
    # at runtime these provide the lazy PEP 562 resolution.

    def __getattr__(name: str) -> object:
        """Lazily resolve the AdCP type surface (PEP 562).

        ``import adcp.types`` stays cheap; the generated Pydantic graph — and its
        import-time coercion / forward-compat patching — is built on first access
        to any type *symbol*, by importing :mod:`adcp.types._eager`. Resolved names
        are cached into this module's namespace, so ``__getattr__`` fires at most
        once per name.

        Real submodules (the curated partial surfaces, ``aliases``, the internal
        generated layer) resolve through the import system rather than ``_eager``.
        That matters for correctness, not just speed: ``aliases`` imports
        ``_generated`` from this package, and routing that through ``_eager`` would
        re-enter the eager body (``_forward_compat`` → ``aliases``) and deadlock on
        a circular import. Passing submodules straight to the import system avoids it.

        Also keeps the removed ``GeoPostalArea`` name importable while emitting a
        :class:`DeprecationWarning` that names the migration target.
        """
        if name == "GeoPostalArea":
            import warnings

            warnings.warn(_DEPRECATION_MESSAGE, DeprecationWarning, stacklevel=2)
            from adcp.types._generated import PostalArea5

            # Cache so the warning fires once: subsequent ``adcp.types.GeoPostalArea``
            # accesses hit the module dict directly and skip ``__getattr__``.
            globals()["GeoPostalArea"] = PostalArea5
            return PostalArea5

        # Submodule passthrough — the curated partial surfaces, ``aliases``, and
        # the internal generated layer are real submodules; import them directly
        # so they never round-trip through the eager body (which would re-enter
        # on the ``_forward_compat`` → ``aliases`` cycle). ``_PARTIAL_MODULES`` is
        # the fast path for the curated set; ``find_spec`` covers the rest.
        if name in _PARTIAL_MODULES or (
            not name.startswith("__") and importlib.util.find_spec(f"adcp.types.{name}") is not None
        ):
            module = importlib.import_module(f"adcp.types.{name}")
            globals()[name] = module
            return module

        # Fail fast for unknown names: don't build the (expensive) schema graph just
        # to discover an attribute doesn't exist. Keeps typos and ``hasattr`` probes
        # for unknown names cheap.
        if name not in _RESOLVABLE:
            raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

        value = getattr(importlib.import_module("adcp.types._eager"), name)
        globals()[name] = value  # cache: __getattr__ fires once per name
        return value

    def __dir__() -> list[str]:
        return sorted(set(__all__) | set(globals()))


if TYPE_CHECKING:
    # Eager re-export so type checkers and IDEs see the full importable
    # surface; resolved lazily through ``__getattr__`` at runtime. ``_eager``
    # defines ``__all__`` so names listed in ``adcp.types.__all__`` re-export
    # cleanly under mypy --strict; the internal helpers not in ``__all__`` use
    # the explicit ``X as X`` re-export form (matching the original module).
    # ``generated`` / ``aliases`` are submodule re-exports; the six partial
    # submodules resolve as real submodules; the two dead back-compat
    # ``__all__`` entries are intentionally unbound.
    from adcp.types import _generated as generated  # noqa: F401
    from adcp.types import aliases  # noqa: F401
    from adcp.types._eager import (
        MEDIA_BUY_LEGACY_STATUS_VALUES as MEDIA_BUY_LEGACY_STATUS_VALUES,
    )
    from adcp.types._eager import (  # noqa: F401
        A2UiComponent,
        A2UiSurface,
        Account,
        AccountAuthorization,
        AccountReference,
        AccountReferenceById,
        AccountReferenceByNaturalKey,
        AccountResponse,
        AccountScope,
        AccountWithAuthorization,
        AcquireRightsAcquiredResponse,
        AcquireRightsErrorResponse,
        AcquireRightsPendingResponse,
        AcquireRightsRejectedResponse,
        AcquireRightsRequest,
        AcquireRightsResponse,
        AcquireRightsResponse1,
        Action,
        ActivateSignalErrorResponse,
        ActivateSignalRequest,
        ActivateSignalResponse,
        ActivateSignalResponse1,
        ActivateSignalSuccessResponse,
        AdcpProtocol,
        AdvertiserIndustry,
        AgentConfig,
        AgentDeployment,
        AgentDestination,
        AggregatedTotals,
        AiTool,
        Artifact,
        ArtifactWebhookPayload,
        Asset,
        AssetContentType,
        AssetType,
        AssignedPackage,
        Assignments,
        AudienceSource,
        AudioContent,
        AudioFormatAsset,
        AudioFormatGroupAsset,
        Authentication,
        AuthenticationScheme,
        AuthorizationRequiredDetails,
        AuthorizedAgent,
        AuthorizedAgents,
        AuthorizedAgentsByInlineProperties,
        AuthorizedAgentsByPropertyId,
        AuthorizedAgentsByPropertyTag,
        AuthorizedAgentsByPublisherProperties,
        AuthorizedAgentsBySignalId,
        AuthorizedAgentsBySignalTag,
        AvailableMetric,
        AvailablePackage,
        AvailableReportingFrequency,
        BothPreviewRender,
        BrandReference,
        BrandSource,
        BriefFormatAsset,
        BuildCreativeCreative,
        BuildCreativeErrorResponse,
        BuildCreativeRequest,
        BuildCreativeResponse,
        BuildCreativeResponse1,
        BuildCreativeSubmittedResponse,
        BuildCreativeSuccessResponse,
        BusinessEntity,
        BusinessEntityResponse,
        BuyingMode,
        ByCatalogItemItem,
        ByPackageItem,
        CalibrateContentErrorResponse,
        CalibrateContentRequest,
        CalibrateContentResponse,
        CalibrateContentResponse1,
        CalibrateContentSuccessResponse,
        CanonicalAssetSource,
        CanonicalCompositionModel,
        CanonicalFormatAgentPlacement,
        CanonicalFormatBase,
        CanonicalFormatDaastAudio,
        CanonicalFormatDisplayTag,
        CanonicalFormatHostedAudio,
        CanonicalFormatHostedVideo,
        CanonicalFormatHtml5Banner,
        CanonicalFormatImage,
        CanonicalFormatImageCarousel,
        CanonicalFormatKind,
        CanonicalFormatNativeInFeed,
        CanonicalFormatResponsiveCreative,
        CanonicalFormatSponsoredPlacement,
        CanonicalFormatVastVideo,
        CanonicalProjectionReference,
        CanonicalSlotOverride,
        CapabilitiesAccount,
        CapabilitiesCreative,
        CapabilitiesMediaBuy,
        Capability,
        Catalog,
        CatalogAction,
        CatalogFieldBinding,
        CatalogFieldBinding1,
        CatalogFieldMapping,
        CatalogFormatAsset,
        CatalogGroupBinding,
        CatalogItemStatus,
        CatalogRequirements,
        CatalogType,
        CheckGovernanceRequest,
        CheckGovernanceResponse,
        CoBranding,
        CoBrandingRequirement,
        CollectionList,
        CollectionListChangedWebhook,
        CollectionListFilters,
        Colors,
        ComplyErrorResponse,
        ComplyListScenariosResponse,
        ComplySimulationResponse,
        ComplyStateTransitionResponse,
        ComplyTestControllerRequest,
        ComplyTestControllerResponse,
        ComplyTestControllerResponse1,
        ConsentBasis,
        Contact,
        ContentIdType,
        ContentStandards,
        ContextMatchRequest,
        ContextMatchResponse,
        ContextObject,
        CoreAccount,
        CoreCreditLimit,
        CoreGovernanceAgent,
        CoreMediaBuy,
        CoreSetup,
        Country,
        CpaPricingOption,
        CpcPricingOption,
        CpcvPricingOption,
        CpmAuctionPricingOption,
        CpmFixedRatePricingOption,
        CpmPricingOption,
        CppPricingOption,
        CpvPricingOption,
        CreateCollectionListRequest,
        CreateCollectionListResponse,
        CreateContentStandardsErrorResponse,
        CreateContentStandardsRequest,
        CreateContentStandardsResponse,
        CreateContentStandardsResponse1,
        CreateContentStandardsSuccessResponse,
        CreateMediaBuyAuthentication,
        CreateMediaBuyErrorResponse,
        CreateMediaBuyRequest,
        CreateMediaBuyResponse,
        CreateMediaBuyResponse1,
        CreateMediaBuySubmittedResponse,
        CreateMediaBuySuccessResponse,
        CreatePropertyListRequest,
        CreatePropertyListResponse,
        Creative,
        CreativeAction,
        CreativeAgent,
        CreativeAgentCapability,
        CreativeApproval,
        CreativeApprovalStatus,
        CreativeAsset,
        CreativeAssignment,
        CreativeFilters,
        CreativeManifest,
        CreativePolicy,
        CreativeStatus,
        CreativeVariant,
        CreditLimit,
        CssContent,
        CssFormatAsset,
        CssFormatGroupAsset,
        DaastFormatAsset,
        DaastFormatGroupAsset,
        DaastTrackingEvent,
        DaastVersion,
        DailyBreakdownItem,
        DateRange,
        DatetimeRange,
        DayOfWeek,
        DaypartTarget,
        DeleteCollectionListRequest,
        DeleteCollectionListResponse,
        DeletePropertyListRequest,
        DeletePropertyListResponse,
        DeliveryCreative,
        DeliveryForecast,
        DeliveryMeasurement,
        DeliveryMetrics,
        DeliveryStatus,
        DeliveryType,
        DemographicSystem,
        Deployment,
        Destination,
        DevicePlatform,
        DeviceType,
        Dimensions,
        DimensionUnit,
        Disclaimer,
        DoohMetrics,
        DownstreamConnectionRequirement,
        Duration,
        DurationUnit,
        Error,
        ErrorCode,
        EventType,
        ExtensionObject,
        FeedbackSource,
        FeedFormat,
        FieldModel,
        FlatRatePricingOption,
        Fonts,
        ForecastableMetric,
        ForecastMethod,
        ForecastPoint,
        ForecastRange,
        ForecastRangeUnit,
        Format,
        FormatAssetUnion,
        FormatCard,
        FormatCardDetailed,
        FormatId,
        FormatIdParameter,
        FormatOptionReference,
        FormatReferenceStructuredObject,
        FrequencyCap,
        FrequencyCapScope,
        GeneratedTaskStatus,
        GeoCountry,
        GeoMetro,
        GeoRegion,
        GetAccountFinancialsErrorResponse,
        GetAccountFinancialsRequest,
        GetAccountFinancialsResponse,
        GetAccountFinancialsResponse1,
        GetAccountFinancialsSuccessResponse,
        GetAdcpCapabilitiesRequest,
        GetAdcpCapabilitiesResponse,
        GetBrandIdentityErrorResponse,
        GetBrandIdentityField,
        GetBrandIdentityRequest,
        GetBrandIdentityResponse,
        GetBrandIdentityResponse1,
        GetBrandIdentitySuccessResponse,
        GetCollectionListRequest,
        GetCollectionListResponse,
        GetContentStandardsErrorResponse,
        GetContentStandardsRequest,
        GetContentStandardsResponse,
        GetContentStandardsResponse1,
        GetContentStandardsSuccessResponse,
        GetCreativeDeliveryByBuyerRefRequest,
        GetCreativeDeliveryByCreativeRequest,
        GetCreativeDeliveryByMediaBuyRequest,
        GetCreativeDeliveryRequest,
        GetCreativeDeliveryResponse,
        GetCreativeFeaturesErrorResponse,
        GetCreativeFeaturesRequest,
        GetCreativeFeaturesResponse,
        GetCreativeFeaturesResponse1,
        GetCreativeFeaturesSuccessResponse,
        GetMediaBuyArtifactsErrorResponse,
        GetMediaBuyArtifactsRequest,
        GetMediaBuyArtifactsResponse,
        GetMediaBuyArtifactsResponse1,
        GetMediaBuyArtifactsSuccessResponse,
        GetMediaBuyDeliveryRequest,
        GetMediaBuyDeliveryResponse,
        GetMediaBuysMediaBuy,
        GetMediaBuysRequest,
        GetMediaBuysResponse,
        GetPlanAuditLogsRequest,
        GetPlanAuditLogsResponse,
        GetProductsBriefRequest,
        GetProductsField,
        GetProductsInputRequiredResponse,
        GetProductsRefineRequest,
        GetProductsRequest,
        GetProductsResponse,
        GetProductsResponseUnion,
        GetProductsSubmittedResponse,
        GetProductsSuccessResponse,
        GetProductsWholesaleRequest,
        GetProductsWorkingResponse,
        GetPropertyListRequest,
        GetPropertyListResponse,
        GetRightsErrorResponse,
        GetRightsRequest,
        GetRightsResponse,
        GetRightsResponse1,
        GetRightsSuccessResponse,
        GetSignalsDiscoveryRequest,
        GetSignalsLookupRequest,
        GetSignalsRequest,
        GetSignalsResponse,
        GetSignalsResponseUnion,
        GetSignalsSignal,
        GetSignalsSubmittedResponse,
        GetSignalsSuccessResponse,
        GetSignalsWorkingResponse,
        GetTaskStatusRequest,
        GetTaskStatusResponse,
        GovernanceAgent,
        GovernanceAuthentication,
        GroupFormatAssetUnion,
        Gtin,
        HtmlContent,
        HtmlFormatAsset,
        HtmlFormatGroupAsset,
        HtmlPreviewRender,
        HttpMethod,
        Identifier,
        IdentityMatchRequest,
        IdentityMatchResponse,
        IdentityMatchTmpxMacro,
        ImageContent,
        ImageFormatAsset,
        ImageFormatGroupAsset,
        InlineDaastAsset,
        InlineVastAsset,
        Input,
        JavascriptContent,
        JavascriptFormatAsset,
        JavascriptFormatGroupAsset,
        JavascriptModuleType,
        KellerType,
        KeyValueActivationKey,
        LandingPage,
        LandingPageRequirement,
        ListAccountsRequest,
        ListAccountsResponse,
        ListCollectionListsRequest,
        ListCollectionListsResponse,
        ListContentStandardsErrorResponse,
        ListContentStandardsRequest,
        ListContentStandardsResponse,
        ListContentStandardsResponse1,
        ListContentStandardsSuccessResponse,
        ListCreativeFormatsRequest,
        ListCreativeFormatsResponse,
        ListCreativesCanonicalCreative,
        ListCreativesCreative,
        ListCreativesCreativeItem,
        ListCreativesField,
        ListCreativesLegacyCreative,
        ListCreativesRequest,
        ListCreativesResponse,
        ListCreativesSort,
        ListPropertyListsRequest,
        ListPropertyListsResponse,
        ListTasksRequest,
        ListTasksResponse,
        ListTasksSort,
        ListTransformersRequest,
        ListTransformersResponse,
        LogEventErrorResponse,
        LogEventRequest,
        LogEventResponse,
        LogEventResponse1,
        LogEventSuccessResponse,
        Logo,
        MarkdownFlavor,
        MarkdownFormatAsset,
        MarkdownFormatGroupAsset,
        McpWebhookPayload,
        MeasurementPeriod,
        MediaBuy,
        MediaBuyDelivery,
        MediaBuyDeliveryStatus,
        MediaBuyDeliveryWebhookResult,
        MediaBuyFeatures,
        MediaBuyPackage,
        MediaBuyStatus,
        MediaChannel,
        MediaSubAsset,
        Member,
        Metadata,
        Method,
        MetricType,
        ModuleType,
        NotificationAuthentication,
        NotificationConfig,
        NotificationType,
        Offering,
        OfferingAssetConstraint,
        OfferingAssetGroup,
        OfferPrice,
        OptimizationGoal,
        OutcomeMeasurement,
        OutputFormat,
        Overlay,
        OverlayUnit,
        Pacing,
        Package,
        PackageRequest,
        PackageSignalTargeting,
        PackageSignalTargetingGroup,
        PackageSignalTargetingGroups,
        PackageUpdate,
        Pagination,
        PaginationRequest,
        PaginationResponse,
        Parameters,
        PaymentTerms,
        Performance,
        PerformanceFeedback,
        PixelTrackerAsset,
        PixelTrackerEvent,
        PixelTrackerMethod,
        Placement,
        PlacementReference,
        PlatformDeployment,
        PlatformDestination,
        Policy,
        PolicyExemplar,
        PolicyExemplars,
        PolicyHistory,
        PolicyRevision,
        PolicySummary,
        PostalArea,
        Preview,
        PreviewCreativeBatchResponse,
        PreviewCreativeInteractiveResponse,
        PreviewCreativeRequest,
        PreviewCreativeResponse,
        PreviewCreativeResponse1,
        PreviewCreativeSingleResponse,
        PreviewCreativeStaticResponse,
        PreviewCreativeVariantResponse,
        PreviewOutputFormat,
        PreviewRender,
        PriceGuidance,
        PricingCurrency,
        PricingModel,
        PricingOption,
        PrimaryCountry,
        Product,
        ProductCard,
        ProductCardDetailed,
        ProductCatalog,
        ProductFilters,
        ProductFormatDeclaration,
        ProductFormatSellerPreference,
        ProductSignalTargetingOption,
        Property,
        PropertyId,
        PropertyIdActivationKey,
        PropertyIdentifierTypes,
        PropertyList,
        PropertyListChangedWebhook,
        PropertyListFilters,
        PropertyListReference,
        PropertyTag,
        PropertyTagActivationKey,
        PropertyType,
        Proposal,
        Protocol,
        ProtocolEnvelope,
        ProtocolResponse,
        ProvenanceDeclaredBy,
        ProvidePerformanceFeedbackByBuyerRefRequest,
        ProvidePerformanceFeedbackByMediaBuyRequest,
        ProvidePerformanceFeedbackErrorResponse,
        ProvidePerformanceFeedbackRequest,
        ProvidePerformanceFeedbackResponse,
        ProvidePerformanceFeedbackResponse1,
        ProvidePerformanceFeedbackSuccessResponse,
        ProviderRegistrationTmpxMacro,
        PublisherDomain,
        PublisherIdentifierTypes,
        PublisherProperties,
        PublisherPropertiesAll,
        PublisherPropertiesById,
        PublisherPropertiesByTag,
        PushNotificationAuthentication,
        PushNotificationConfig,
        QuartileData,
        QuerySummary,
        ReachUnit,
        RealEstateUnit,
        Recovery,
        Refine,
        RefinementApplied,
        RefinementApplied1,
        RefinementApplied2,
        RefinementApplied3,
        Renders,
        RepeatableAssetGroup,
        ReportingBucket,
        ReportingCapabilities,
        ReportingFrequency,
        ReportingPeriod,
        ReportingWebhook,
        ReportingWebhookAuthentication,
        ReportPlanOutcomeRequest,
        ReportPlanOutcomeResponse,
        ReportUsageRequest,
        ReportUsageResponse,
        Request,
        ResolvedBrand,
        ResolvedProperty,
        Response,
        ResponsePayloadJwsEnvelope,
        ResponseType,
        Responsive,
        Results,
        RightsPricingOption,
        RightsTerms,
        SchemaVariant,
        Scheme,
        Security,
        SegmentIdActivationKey,
        SellerAgentReference,
        Setup,
        SiCapabilities,
        SiGetOfferingRequest,
        SiGetOfferingResponse,
        Signal,
        SignalAvailabilityType,
        SignalCatalogType,
        SignalDefinitionEnrichment,
        SignalFilters,
        SignalListing,
        SignalPricingOption,
        SignalRef,
        SignalTargeting,
        SignalTargetingExpression,
        SignalTargetingRules,
        SignalType,
        SiIdentity,
        SiInitiateSessionRequest,
        SiInitiateSessionResponse,
        SiSendActionResponseRequest,
        SiSendMessageRequest,
        SiSendMessageResponse,
        SiSendTextMessageRequest,
        SiSponsoredContextDeclaredBy,
        SiTerminateSessionRequest,
        SiTerminateSessionResponse,
        SiUiElement,
        Snapshot,
        SnapshotUnavailableReason,
        Sort,
        SortApplied,
        SortDirection,
        Source,
        Status,
        StatusSummary,
        SyncAccountsAccount,
        SyncAccountsCreditLimit,
        SyncAccountsErrorResponse,
        SyncAccountsRequest,
        SyncAccountsResponse,
        SyncAccountsResponse1,
        SyncAccountsSetup,
        SyncAccountsSuccessResponse,
        SyncAudiencesAudience,
        SyncAudiencesErrorResponse,
        SyncAudiencesRequest,
        SyncAudiencesResponse,
        SyncAudiencesResponse1,
        SyncAudiencesSubmittedResponse,
        SyncAudiencesSuccessResponse,
        SyncCatalogResult,
        SyncCatalogsErrorResponse,
        SyncCatalogsInputRequired,
        SyncCatalogsRequest,
        SyncCatalogsResponse,
        SyncCatalogsResponse1,
        SyncCatalogsSubmitted,
        SyncCatalogsSubmittedResponse,
        SyncCatalogsSuccessResponse,
        SyncCatalogsWorking,
        SyncCreativeResult,
        SyncCreativesCreative,
        SyncCreativesErrorResponse,
        SyncCreativesRequest,
        SyncCreativesResponse,
        SyncCreativesResponse1,
        SyncCreativesResponse3,
        SyncCreativesSubmittedResponse,
        SyncCreativesSuccessResponse,
        SyncEventSourcesErrorResponse,
        SyncEventSourcesRequest,
        SyncEventSourcesResponse,
        SyncEventSourcesResponse1,
        SyncEventSourcesSetup,
        SyncEventSourcesSuccessResponse,
        SyncGovernanceAccount,
        SyncGovernanceGovernanceAgent,
        SyncGovernanceRequest,
        SyncGovernanceResponse,
        SyncPlansRequest,
        SyncPlansResponse,
        Tags,
        TargetingOverlay,
        TaskResult,
        TasksListSort,
        TaskType,
        TextContent,
        TextFormatAsset,
        TextFormatGroupAsset,
        TextSubAsset,
        TimeBasedPricingOption,
        TimeUnit,
        TmpError,
        TmpOffer,
        Totals,
        TrackingEvent,
        Transform,
        Unit,
        UnknownFormatAsset,
        UnknownGroupAsset,
        UpdateCollectionListRequest,
        UpdateCollectionListResponse,
        UpdateContentStandardsErrorResponse,
        UpdateContentStandardsRequest,
        UpdateContentStandardsResponse,
        UpdateContentStandardsResponse1,
        UpdateContentStandardsSuccessResponse,
        UpdateFrequency,
        UpdateMediaBuyErrorResponse,
        UpdateMediaBuyPackagesRequest,
        UpdateMediaBuyPropertiesRequest,
        UpdateMediaBuyRequest,
        UpdateMediaBuyResponse,
        UpdateMediaBuyResponse1,
        UpdateMediaBuyResponse3,
        UpdateMediaBuySubmittedResponse,
        UpdateMediaBuySuccessResponse,
        UpdatePropertyListRequest,
        UpdatePropertyListResponse,
        UpdateRightsRequest,
        UpdateRightsResponse,
        UrlAssetType,
        UrlContent,
        UrlDaastAsset,
        UrlFormatAsset,
        UrlFormatGroupAsset,
        UrlPreviewRender,
        UrlType,
        UrlVastAsset,
        V1CanonicalDimensions,
        V1CanonicalGlobPattern,
        V1CanonicalMapping,
        V1CanonicalStructural,
        V1CanonicalStructuralPattern,
        V1CanonicalV2Projection,
        V1V2CanonicalFormatMappingRegistry,
        ValidateContentDeliveryErrorResponse,
        ValidateContentDeliveryRequest,
        ValidateContentDeliveryResponse,
        ValidateContentDeliveryResponse1,
        ValidateContentDeliverySuccessResponse,
        ValidateInputRequest,
        ValidateInputResponse,
        ValidationMode,
        VastFormatAsset,
        VastFormatGroupAsset,
        VastTrackingEvent,
        VastVersion,
        VcpmAuctionPricingOption,
        VcpmFixedRatePricingOption,
        VcpmPricingOption,
        VehicleUnit,
        VenueBreakdownItem,
        VerifyBrandClaimPayload,
        VerifyBrandClaimRequest,
        VerifyBrandClaimResponse,
        VerifyBrandClaimsErrorResponse,
        VerifyBrandClaimSignedResponse,
        VerifyBrandClaimSignedSuccessPayload,
        VerifyBrandClaimsPayload,
        VerifyBrandClaimsRequest,
        VerifyBrandClaimsRequestBulk,
        VerifyBrandClaimsResponse,
        VerifyBrandClaimsResponseBulk,
        VerifyBrandClaimsSignedResponse,
        VerifyBrandClaimsSignedSuccessPayload,
        VideoContent,
        VideoFormatAsset,
        VideoFormatGroupAsset,
        ViewThreshold,
        WcagLevel,
        WebhookChallenge,
        WebhookChallengeResponse,
        WebhookContent,
        WebhookFormatAsset,
        WebhookFormatGroupAsset,
        WebhookMetadata,
        WebhookResponseType,
        WholesaleFeedEvent,
        WholesaleFeedSignal,
        WholesaleFeedWebhook,
        project_geo_postal_areas,
        to_account_response,
    )
    from adcp.types._eager import (
        Field1 as Field1,
    )
    from adcp.types._eager import (
        Measurement as Measurement,
    )
    from adcp.types._eager import (
        is_activate_signal_error as is_activate_signal_error,
    )
    from adcp.types._eager import (
        is_activate_signal_success as is_activate_signal_success,
    )
    from adcp.types._eager import (
        is_adcp_error as is_adcp_error,
    )
    from adcp.types._eager import (
        is_adcp_success as is_adcp_success,
    )
    from adcp.types._eager import (
        is_build_creative_error as is_build_creative_error,
    )
    from adcp.types._eager import (
        is_build_creative_submitted as is_build_creative_submitted,
    )
    from adcp.types._eager import (
        is_build_creative_success as is_build_creative_success,
    )
    from adcp.types._eager import (
        is_calibrate_content_success as is_calibrate_content_success,
    )
    from adcp.types._eager import (
        is_create_media_buy_error as is_create_media_buy_error,
    )
    from adcp.types._eager import (
        is_create_media_buy_success as is_create_media_buy_success,
    )
    from adcp.types._eager import (
        is_get_account_financials_error as is_get_account_financials_error,
    )
    from adcp.types._eager import (
        is_get_account_financials_success as is_get_account_financials_success,
    )
    from adcp.types._eager import (
        is_get_creative_features_success as is_get_creative_features_success,
    )
    from adcp.types._eager import (
        is_log_event_error as is_log_event_error,
    )
    from adcp.types._eager import (
        is_log_event_success as is_log_event_success,
    )
    from adcp.types._eager import (
        is_performance_feedback_error as is_performance_feedback_error,
    )
    from adcp.types._eager import (
        is_performance_feedback_success as is_performance_feedback_success,
    )
    from adcp.types._eager import (
        is_sync_accounts_error as is_sync_accounts_error,
    )
    from adcp.types._eager import (
        is_sync_accounts_success as is_sync_accounts_success,
    )
    from adcp.types._eager import (
        is_sync_catalogs_error as is_sync_catalogs_error,
    )
    from adcp.types._eager import (
        is_sync_catalogs_submitted as is_sync_catalogs_submitted,
    )
    from adcp.types._eager import (
        is_sync_catalogs_success as is_sync_catalogs_success,
    )
    from adcp.types._eager import (
        is_sync_creatives_error as is_sync_creatives_error,
    )
    from adcp.types._eager import (
        is_sync_creatives_submitted as is_sync_creatives_submitted,
    )
    from adcp.types._eager import (
        is_sync_creatives_success as is_sync_creatives_success,
    )
    from adcp.types._eager import (
        is_update_media_buy_error as is_update_media_buy_error,
    )
    from adcp.types._eager import (
        is_update_media_buy_success as is_update_media_buy_success,
    )
    from adcp.types._eager import (
        is_validate_content_delivery_success as is_validate_content_delivery_success,
    )
    from adcp.types._eager import (
        unwrap_enum_value as unwrap_enum_value,
    )
