"""Eager realization of the AdCP type surface.

This module binds every public name exported by :mod:`adcp.types` and runs
the import-time Pydantic patching (``_ergonomic`` coercion +
``_forward_compat`` open-union ``Format.assets``). It is imported on demand
by :mod:`adcp.types`'s lazy ``__getattr__`` the first time any type symbol is
accessed, so ``import adcp.types`` itself stays cheap.

Do not import this module directly — import from :mod:`adcp.types` (or
:mod:`adcp`). The name set here is mirrored by ``adcp.types.__all__``; the
``tests/test_lazy_types.py`` guard fails if the two drift.
"""

from __future__ import annotations

import importlib

# Run the import-time patchers as a side effect, before binding the generated
# types below (must come first — see the original "must be imported before
# other types" note): ``_ergonomic`` applies BeforeValidator coercion and
# ``_forward_compat`` opens ``Format.assets`` / ``RepeatableAssetGroup.assets``.
# Imported via ``import_module`` — a call, not a name binding — so they read as
# the intentional side-effect imports they are rather than tripping
# unused-import analysers. (The removed ``format_category`` submodule has a real
# shim at ``generated_poc/enums/format_category.py``, restored after codegen by
# ``scripts/post_generate_fixes.py``.)
importlib.import_module("adcp.types._ergonomic")
importlib.import_module("adcp.types._forward_compat")

# Re-exported submodules (part of the public surface via ``__all__`` below).
from adcp.types import _generated as generated  # noqa: F401
from adcp.types import aliases  # noqa: F401

# Python SDK 7 primary creative boundary.  The generated classes above remain
# available under explicit Legacy* names; these imports intentionally override
# their unqualified bindings for application code.
from adcp.types import canonical_creative as _canonical_creative

# Import all types from generated code
# V3 Protocol Discovery types
# V3 Content Standards types
# V3 Sponsored Intelligence types
# V3 Governance (Property Lists) types
# Re-export webhook payload type for webhook handling
from adcp.types._generated import (
    A2UiComponent,
    A2UiSurface,
    AcceptanceContext,
    AcceptancePolicyCatalog,
    AcceptancePolicyDiscovery,
    AcceptancePolicyProfile,
    AcceptancePolicyProfileId,
    AcceptancePolicyProfileIds,
    AcceptancePolicyRequirement,
    AcceptancePolicyRule,
    AcceptedLoss,
    AcceptProposalRequest,
    AcceptProposalResponse,
    AccessibilityViolationDetails,
    Account,
    AccountAuthorization,
    AccountMovedDetails,
    AccountScope,
    AccountSetupRequiredDetails,
    AccountWithAuthorization,
    AcquireRightsRequest,
    AcquireRightsResponse,
    ActionNotAllowedDetails,
    ActionNotAllowedReason,
    ActivateSignalRequest,
    ActivateSignalResponse,
    AdcpProtocol,
    AdvertiserIndustry,
    AgentDeclarations,
    AgentNotificationConfig,
    AgentNotificationConfigState,
    AgentPermissionDeniedDetails,
    AgentReportingDestination,
    AgentReportingDestinationState,
    AggregatedTotals,
    AiTool,
    Artifact,
    ArtifactWebhookPayload,
    AssetContentType,
    AssignedPackage,
    Assignments,
    AudienceSource,
    AudienceTooSmallDetails,
    Authentication,
    AuthenticationScheme,
    AuthorizationRequiredDetails,
    AuthorizedAgents,
    AvailableMetric,
    AvailablePackage,
    BillingNotPermittedForAgentDetails,
    BillingNotSupportedDetails,
    BrandReference,
    BudgetTooLowDetails,
    BusinessEntity,
    BuyingMode,
    BuyProductsRequest,
    BuyProductsResponse,
    ByPackageItem,
    CalibrateContentRequest,
    CalibrateContentResponse,
    CanonicalMediaBuyAction,
    CanonicalMediaBuyActionMode,
    CanonicalMediaBuyActionName,
    CanonicalProductAction,
    Catalog,
    CatalogAction,
    CatalogFieldBinding,
    CatalogFieldBinding1,
    CatalogFieldMapping,
    CatalogItemStatus,
    CatalogRequirements,
    CatalogType,
    CheckGovernanceRequest,
    CheckGovernanceResponse,
    CoBrandingRequirement,
    CollectionList,
    CollectionListChangedWebhook,
    CollectionListFilters,
    Colors,
    CommercialTerms,
    CompatibilityPurchaseCoordinatorInput,
    ComplyTestControllerRequest,
    ComplyTestControllerResponse,
    ConflictDetails,
    Contact,
    ContentIdType,
    ContentStandards,
    ContextMatchRequest,
    ContextObject,
    ControlMediaBuyRequest,
    ControlMediaBuyResponse,
    Country,
    CpaPricingOption,
    CpcPricingOption,
    CpcvPricingOption,
    CpmPricingOption,
    CppPricingOption,
    CpvPricingOption,
    CreateCollectionListRequest,
    CreateCollectionListResponse,
    CreateContentStandardsRequest,
    CreateContentStandardsResponse,
    CreatePropertyListRequest,
    CreatePropertyListResponse,
    CreativeAction,
    CreativeAgent,
    CreativeAgentCapability,
    CreativeApproval,
    CreativeApprovalStatus,
    CreativeAssignment,
    CreativePolicy,
    CreativeRejectedDetails,
    CreativeStatus,
    CreditLimit,
    DaastTrackingEvent,
    DaastVersion,
    DailyBreakdownItem,
    DateRange,
    DatetimeRange,
    DayOfWeek,
    DaypartTarget,
    DeclineProposalsRequest,
    DeclineProposalsResponse,
    DeleteCollectionListRequest,
    DeleteCollectionListResponse,
    DeletePropertyListRequest,
    DeletePropertyListResponse,
    DeliveryForecast,
    DeliveryMeasurement,
    DeliveryMetrics,
    DeliveryStatus,
    DeliveryType,
    DemographicSystem,
    DevicePlatform,
    DeviceType,
    Dimensions,
    DimensionUnit,
    DoohMetrics,
    DownstreamConnectionRequirement,
    Duration,
    ErrorCode,
    EventType,
    ExtensionObject,
    FeedbackSource,
    FeedFormat,
    Field1,
    FlatRatePricingOption,
    ForecastableMetric,
    ForecastMethod,
    ForecastPoint,
    ForecastRange,
    ForecastRangeUnit,
    FormatCard,
    FormatCardDetailed,
    FormatIdParameter,
    FormatOptionReference,
    FrequencyCap,
    FrequencyCapScope,
    GeoCountry,
    GeoMetro,
    GeoRegion,
    GetAccountFinancialsRequest,
    GetAccountFinancialsResponse,
    GetAdcpCapabilitiesRequest,
    GetAdcpCapabilitiesResponse,
    GetBrandIdentityRequest,
    GetBrandIdentityResponse,
    GetCollectionListRequest,
    GetCollectionListResponse,
    GetContentStandardsRequest,
    GetContentStandardsResponse,
    GetCreativeDeliveryRequest,
    GetCreativeFeaturesRequest,
    GetCreativeFeaturesResponse,
    GetMediaBuyArtifactsRequest,
    GetMediaBuyArtifactsResponse,
    GetMediaBuyDeliveryRequest,
    GetMediaBuysRequest,
    GetPlanAuditLogsRequest,
    GetPlanAuditLogsResponse,
    GetPrincipalRequest,
    GetPrincipalResponse,
    GetPropertyListRequest,
    GetPropertyListResponse,
    GetReportingStatusRequest,
    GetReportingStatusResponse,
    GetRightsRequest,
    GetRightsResponse,
    GetSignalsRequest,
    GetSignalsResponse,
    GetTaskStatusRequest,
    GetTaskStatusResponse,
    GovernanceAgent,
    Gtin,
    HttpMethod,
    Identifier,
    IdentityMatchRequest,
    IdentityMatchResponse,
    Input,
    JavascriptModuleType,
    KellerType,
    LandingPageRequirement,
    ListAccountChangesRequest,
    ListAccountChangesResponse,
    ListAccountsRequest,
    ListAccountsResponse,
    ListCollectionListsRequest,
    ListCollectionListsResponse,
    ListContentStandardsRequest,
    ListContentStandardsResponse,
    ListProductsRequest,
    ListProductsResponse,
    ListPropertyListsRequest,
    ListPropertyListsResponse,
    ListTasksRequest,
    ListTasksResponse,
    LogEventRequest,
    LogEventResponse,
    Logo,
    MarkdownFlavor,
    McpWebhookPayload,
    MeasurementPeriod,
    MediaBuy,
    MediaBuyActionMode,
    MediaBuyAvailableAction,
    MediaBuyChangeTerm,
    MediaBuyChangeTermConstraints,
    MediaBuyChangeTermId,
    MediaBuyDelivery,
    MediaBuyDeliveryWebhookResult,
    MediaBuyFeatures,
    MediaBuyPackage,
    MediaBuyStatus,
    MediaBuyValidAction,
    MediaChannel,
    Metadata,
    NotificationConfig,
    NotificationType,
    Offering,
    OfferingAssetConstraint,
    OfferingAssetGroup,
    OfferPrice,
    OptimizationGoal,
    Overlay,
    Pacing,
    PackageSignalTargeting,
    PackageSignalTargetingGroup,
    PackageSignalTargetingGroups,
    Pagination,
    PaginationRequest,
    PaginationResponse,
    Parameters,
    PaymentTerms,
    PerformanceFeedback,
    PlacementPresentationDocument,
    PlacementPresentationReference,
    PlacementReference,
    PolicyViolationDetails,
    PreviewOutputFormat,
    PreviewRender,
    PreviewRendererMetadata,
    PriceGuidance,
    PricingCurrency,
    PricingModel,
    PrimaryCountry,
    PrincipalChangedWebhook,
    PrincipalDeclarationsState,
    PrincipalKind,
    PrincipalState,
    ProductAllowedAction,
    ProductCard,
    ProductCardDetailed,
    ProductSignalTargetingOption,
    Property,
    PropertyIdentifierTypes,
    PropertyList,
    PropertyListChangedWebhook,
    PropertyListFilters,
    PropertyListReference,
    PropertyType,
    Proposal,
    ProtocolEnvelope,
    ProtocolResponse,
    ProvidePerformanceFeedbackRequest,
    ProvidePerformanceFeedbackResponse,
    PublisherDesignatedPreviewProvider,
    PublisherDomain,
    PublisherIdentifierTypes,
    PushNotificationConfig,
    QuartileData,
    QuerySummary,
    RateLimitedDetails,
    ReachUnit,
    ReferenceRenderer,
    Refine,
    RefinementApplied,
    RefinementApplied1,
    RefinementApplied2,
    RefinementApplied3,
    RefineProposalsRequest,
    RefineProposalsResponse,
    RegistryAcceptancePolicyProfileReference,
    Renders,
    ReportingBucket,
    ReportingCanonicalContentDigest,
    ReportingCanonicalizationContract,
    ReportingCapabilities,
    ReportingControlTotal,
    ReportingDatasetShareDestination,
    ReportingDeliveryCapabilities,
    ReportingDeliveryConfiguration,
    ReportingDeliveryConfigurationState,
    ReportingDeliveryMethod,
    ReportingDeliveryOffering,
    ReportingDeliveryReadyWebhook,
    ReportingFileCompression,
    ReportingFileEntry,
    ReportingFileManifest,
    ReportingFrequency,
    ReportingMaterialization,
    ReportingObligation,
    ReportingPeriod,
    ReportingReceipt,
    ReportingReconciliationMode,
    ReportingReportDefinition,
    ReportingResource,
    ReportingRevision,
    ReportingSchedule,
    ReportingScheduleOffering,
    ReportingStatusIssue,
    ReportingVerification,
    ReportingVerificationProfile,
    ReportingWebhook,
    ReportingWriteDestination,
    ReportPlanAdjustmentRequest,
    ReportPlanAdjustmentResponse,
    ReportPlanOutcomeRequest,
    ReportPlanOutcomeResponse,
    ReportUsageRequest,
    ReportUsageResponse,
    Request,
    RequestProposalsRequest,
    RequestProposalsResponse,
    Response,
    ResponsePayloadJwsEnvelope,
    Responsive,
    RightsPricingOption,
    RightsTerms,
    Security,
    SellerAgentReference,
    Setup,
    SiCapabilities,
    SiGetOfferingRequest,
    SiGetOfferingResponse,
    Signal,
    SignalAvailabilityType,
    SignalCatalogType,
    SignalDefinitionEnrichment,
    SignalFilters,
    SignalListing,
    SignalPricingOption,
    SignalTargeting,
    SignalTargetingExpression,
    SignalTargetingRules,
    SiIdentity,
    SiInitiateSessionRequest,
    SiInitiateSessionResponse,
    SiSendMessageRequest,
    SiSendMessageResponse,
    SiTerminateSessionRequest,
    SiTerminateSessionResponse,
    SiUiElement,
    Snapshot,
    SnapshotUnavailableReason,
    Sort,
    SortApplied,
    SortDirection,
    StaleResponseDetails,
    StatusSummary,
    SyncAccountsRequest,
    SyncAccountsResponse,
    SyncAgentNotificationConfigsRequest,
    SyncAgentNotificationConfigsResponse,
    SyncAudiencesRequest,
    SyncAudiencesResponse,
    SyncCatalogsInputRequired,
    SyncCatalogsRequest,
    SyncCatalogsResponse,
    SyncCatalogsSubmitted,
    SyncCatalogsWorking,
    SyncCreativesResponse,
    SyncEventSourcesRequest,
    SyncEventSourcesResponse,
    SyncGovernanceRequest,
    SyncGovernanceResponse,
    SyncPlansRequest,
    SyncPlansResponse,
    SyncPrincipalRequest,
    SyncPrincipalResponse,
    SyncReportingReceiptsRequest,
    SyncReportingReceiptsResponse,
    Tags,
    TargetingOverlay,
    TaskType,
    TimeBasedPricingOption,
    TimeUnit,
    TmpError,
    Totals,
    Transform,
    UnsupportedRefinementDimensionDetails,
    UpdateCollectionListRequest,
    UpdateCollectionListResponse,
    UpdateContentStandardsRequest,
    UpdateContentStandardsResponse,
    UpdateFrequency,
    UpdatePropertyListRequest,
    UpdatePropertyListResponse,
    UpdateRightsRequest,
    UpdateRightsResponse,
    UrlAssetType,
    ValidateContentDeliveryRequest,
    ValidateContentDeliveryResponse,
    ValidateInputRequest,
    ValidateInputResponse,
    ValidationMode,
    VastTrackingEvent,
    VastVersion,
    VcpmPricingOption,
    VendorErrorCodeRegistry,
    VenueBreakdownItem,
    VerifyBrandClaimPayload,
    VerifyBrandClaimRequest,
    VerifyBrandClaimResponse,
    VerifyBrandClaimsErrorResponse,
    VerifyBrandClaimSignedResponse,
    VerifyBrandClaimSignedSuccessPayload,
    VerifyBrandClaimsPayload,
    VerifyBrandClaimsRequest,
    VerifyBrandClaimsRequestBulk,
    VerifyBrandClaimsResponse,
    VerifyBrandClaimsResponseBulk,
    VerifyBrandClaimsSignedResponse,
    VerifyBrandClaimsSignedSuccessPayload,
    VersionUnsupportedDetails,
    ViewThreshold,
    WcagLevel,
    WebhookChallenge,
    WebhookChallengeResponse,
    WebhookResponseType,
    WholesaleFeedEvent,
    WholesaleFeedWebhook,
)
from adcp.types._generated import (
    AudioAsset as AudioContent,
)
from adcp.types._generated import (
    ContextMatchResponseRouterPublisher as ContextMatchResponse,
)
from adcp.types._generated import (
    CssAsset as CssContent,
)
from adcp.types._generated import (
    HtmlAsset as HtmlContent,
)
from adcp.types._generated import (
    ImageAsset as ImageContent,
)
from adcp.types._generated import (
    JavascriptAsset as JavascriptContent,
)
from adcp.types._generated import (
    ListTransformersRequestCreativeAgent as ListTransformersRequest,
)
from adcp.types._generated import (
    ListTransformersResponseCreativeAgent as ListTransformersResponse,
)
from adcp.types._generated import (
    Offer as TmpOffer,
)
from adcp.types._generated import TaskStatus as GeneratedTaskStatus
from adcp.types._generated import (
    TextAsset as TextContent,
)
from adcp.types._generated import (
    UrlAsset as UrlContent,
)
from adcp.types._generated import (
    VideoAsset as VideoContent,
)
from adcp.types._generated import (
    WebhookAsset as WebhookContent,
)
from adcp.types._generated import _ErrorFromError as Error

# Import semantic aliases for discriminated unions
from adcp.types.aliases import (
    AccountIdReference,
    AccountReference,
    AccountReferenceById,
    AccountReferenceByNaturalKey,
    AcquireRightsAcquiredResponse,
    AcquireRightsErrorResponse,
    AcquireRightsPendingResponse,
    AcquireRightsRejectedResponse,
    AcquireRightsResponse1,
    ActivateSignalErrorResponse,
    ActivateSignalResponse1,
    ActivateSignalSuccessResponse,
    AgentDeployment,
    AgentDestination,
    AssetInstance,
    AssetInstanceType,
    AssetVariant,
    AudioFormatAsset,
    AudioFormatGroupAsset,
    AuthorizedAgent,
    AuthorizedAgentsByInlineProperties,
    AuthorizedAgentsByPropertyId,
    AuthorizedAgentsByPropertyTag,
    AuthorizedAgentsByPublisherProperties,
    AuthorizedAgentsBySignalId,
    AuthorizedAgentsBySignalTag,
    BothPreviewRender,
    BrandIdentity,
    BriefAsset,
    BriefFormatAsset,
    BudgetChangeConstraints,
    # Cross-module name collision aliases (#911, Step 2)
    BuildCreativeCreative,
    CalibrateContentErrorResponse,
    CalibrateContentResponse1,
    CalibrateContentSuccessResponse,
    CanonicalAssetSource,
    CanonicalCompositionModel,
    CanonicalFormatAgentPlacement,
    CanonicalFormatBase,
    CanonicalFormatDaastAudio,
    CanonicalFormatDisplayTag,
    CanonicalFormatHostedAudio,
    CanonicalFormatHostedVideo,
    CanonicalFormatHtml5Banner,
    CanonicalFormatImage,
    CanonicalFormatImageCarousel,
    CanonicalFormatKind,
    CanonicalFormatNativeInFeed,
    CanonicalFormatResponsiveCreative,
    CanonicalFormatSponsoredPlacement,
    CanonicalFormatVastVideo,
    CanonicalProjectionReference,
    CanonicalProposalTotalBudgetGuidance,
    CanonicalSlotOverride,
    CapabilitiesAccount,
    CapabilitiesCreative,
    CapabilitiesMediaBuy,
    CapabilitiesPreviewRenderingOrigin,
    CapabilitiesPreviewRoute,
    CardAsset,
    CatalogAsset,
    CatalogFormatAsset,
    CatalogGroupBinding,
    ComplyErrorResponse,
    ComplyListScenariosResponse,
    ComplySimulationResponse,
    ComplyStateTransitionResponse,
    ComplyTestControllerResponse1,
    ConsentBasis,
    CoreAccount,
    CoreCreditLimit,
    CoreGovernanceAgent,
    CoreMediaBuy,
    CoreSetup,
    CpmVendorPricingOption,
    CreateContentStandardsErrorResponse,
    CreateContentStandardsResponse1,
    CreateContentStandardsSuccessResponse,
    CreateMediaBuyAuthentication,
    CssFormatAsset,
    CssFormatGroupAsset,
    CustomVendorPricingOption,
    DaastAsset,
    DaastFormatAsset,
    DaastFormatGroupAsset,
    DaastTrackerAsset,
    DeliveryCreative,
    Deployment,
    Destination,
    DownstreamConnectionRequiredForItem,
    DurationUnit,
    EffectiveTimingChangeConstraints,
    FlatFeeVendorPricingOption,
    FlightChangeConstraints,
    FormatAssetUnion,
    GetAccountFinancialsErrorResponse,
    GetAccountFinancialsResponse1,
    GetAccountFinancialsSuccessResponse,
    GetBrandIdentityErrorResponse,
    GetBrandIdentityField,
    GetBrandIdentityResponse1,
    GetBrandIdentitySuccessResponse,
    GetContentStandardsErrorResponse,
    GetContentStandardsResponse1,
    GetContentStandardsSuccessResponse,
    GetCreativeDeliveryByBuyerRefRequest,
    GetCreativeDeliveryByCreativeRequest,
    GetCreativeDeliveryByMediaBuyRequest,
    GetCreativeFeaturesErrorResponse,
    GetCreativeFeaturesResponse1,
    GetCreativeFeaturesSuccessResponse,
    GetMediaBuyArtifactsErrorResponse,
    GetMediaBuyArtifactsResponse1,
    GetMediaBuyArtifactsSuccessResponse,
    GetMediaBuysMediaBuy,
    GetProductsBriefRequest,
    GetProductsField,
    GetProductsInputRequiredResponse,
    GetProductsRefineRequest,
    GetProductsSubmittedResponse,
    GetProductsWholesaleRequest,
    GetProductsWorkingResponse,
    GetRightsErrorResponse,
    GetRightsResponse1,
    GetRightsSuccessResponse,
    GetSignalsDiscoveryRequest,
    GetSignalsLookupRequest,
    GetSignalsResponseUnion,
    GetSignalsSignal,
    GetSignalsSubmittedResponse,
    GetSignalsSuccessResponse,
    GetSignalsWorkingResponse,
    GovernanceAuthentication,
    GroupFormatAssetUnion,
    HtmlFormatAsset,
    HtmlFormatGroupAsset,
    HtmlPreviewRender,
    IdentityMatchTmpxMacro,
    ImageFormatAsset,
    ImageFormatGroupAsset,
    InlineAccountReference,
    InlineDaastAsset,
    InlineVastAsset,
    JavascriptFormatAsset,
    JavascriptFormatGroupAsset,
    KeyValueActivationKey,
    LegacyProposalTotalBudgetGuidance,
    LegacyUpdateMediaBuyErrorResponse,
    LegacyUpdateMediaBuySuccessResponse,
    ListContentStandardsErrorResponse,
    ListContentStandardsResponse1,
    ListContentStandardsSuccessResponse,
    ListCreativesCanonicalCreative,
    ListCreativesCreative,
    ListCreativesCreativeItem,
    ListCreativesLegacyCreative,
    ListCreativesSort,
    ListTasksSort,
    LogEventErrorResponse,
    LogEventResponse1,
    LogEventSuccessResponse,
    MarkdownAsset,
    MarkdownFormatAsset,
    MarkdownFormatGroupAsset,
    MediaBuyDeliveryStatus,
    MissingMetric,
    NotificationAuthentication,
    OverlayUnit,
    PackageCountChangeConstraints,
    PercentOfMediaVendorPricingOption,
    PerUnitVendorPricingOption,
    PixelTrackerAsset,
    PixelTrackerEvent,
    PixelTrackerMethod,
    PlatformDeployment,
    PlatformDestination,
    PostalArea,
    PreviewRenderingOrigin,
    PricingOption,
    PrincipalAppliedResult,
    PrincipalConfiguration,
    PrincipalCurrentResult,
    PrincipalReadFailedResult,
    PrincipalReadResult,
    PrincipalRecognizedResult,
    PrincipalSyncFailedResult,
    PrincipalSyncResult,
    PrincipalUnconfiguredResult,
    PrincipalValidatedResult,
    ProductAllocation,
    ProductDiscoveryProductId,
    ProductFilterCountry,
    ProductFormatSellerPreference,
    PropertyId,
    PropertyIdentifier,
    PropertyTag,
    Provenance,
    ProvenanceDeclaredBy,
    ProvidePerformanceFeedbackByBuyerRefRequest,
    ProvidePerformanceFeedbackByMediaBuyRequest,
    ProvidePerformanceFeedbackErrorResponse,
    ProvidePerformanceFeedbackResponse1,
    ProvidePerformanceFeedbackSuccessResponse,
    ProviderRegistrationTmpxMacro,
    PublishedPostAsset,
    PublisherPreviewRoute,
    PublisherProperties,
    PublisherPropertiesAll,
    PublisherPropertiesById,
    PublisherPropertiesByTag,
    PushNotificationAuthentication,
    RealEstateUnit,
    Recovery,
    ReferenceRendererProvenance,
    RefineProposalsTotalBudgetGuidance,
    RepeatableAssetGroup,
    ReportingWebhookAuthentication,
    RequestProposalsProductId,
    RequestSigningRequiredForItem,
    SegmentIdActivationKey,
    SignalCoverageForecast,
    SignalCoverageRange,
    SignalRef,
    SiSendActionResponseRequest,
    SiSendTextMessageRequest,
    SiSponsoredContextDeclaredBy,
    Source,
    SyncAccountsAccount,
    SyncAccountsCreditLimit,
    SyncAccountsErrorResponse,
    SyncAccountsResponse1,
    SyncAccountsSetup,
    SyncAccountsSuccessResponse,
    SyncAudiencesAudience,
    SyncAudiencesErrorResponse,
    SyncAudiencesResponse1,
    SyncAudiencesSubmittedResponse,
    SyncAudiencesSuccessResponse,
    SyncCatalogResult,
    SyncCatalogsErrorResponse,
    SyncCatalogsResponse1,
    SyncCatalogsSubmittedResponse,
    SyncCatalogsSuccessResponse,
    SyncCreativeResult,
    SyncCreativesCreative,
    SyncCreativesErrorResponse,
    SyncCreativesResponse1,
    SyncCreativesResponse3,
    SyncCreativesSubmittedResponse,
    SyncCreativesSuccessResponse,
    SyncEventSourcesErrorResponse,
    SyncEventSourcesResponse1,
    SyncEventSourcesSetup,
    SyncEventSourcesSuccessResponse,
    SyncGovernanceAccount,
    SyncGovernanceGovernanceAgent,
    TasksListSort,
    TextFormatAsset,
    TextFormatGroupAsset,
    TrustedMatch,
    UnknownFormatAsset,
    UnknownGroupAsset,
    UpdateContentStandardsErrorResponse,
    UpdateContentStandardsResponse1,
    UpdateContentStandardsSuccessResponse,
    UpdateMediaBuyPackagesRequest,
    UpdateMediaBuyPropertiesRequest,
    UrlDaastAsset,
    UrlFormatAsset,
    UrlFormatGroupAsset,
    UrlPreviewRender,
    UrlVastAsset,
    V1CanonicalDimensions,
    V1CanonicalGlobPattern,
    V1CanonicalMapping,
    V1CanonicalStructural,
    V1CanonicalStructuralPattern,
    V1CanonicalV2Projection,
    V1V2CanonicalFormatMappingRegistry,
    ValidateContentDeliveryErrorResponse,
    ValidateContentDeliveryResponse1,
    ValidateContentDeliverySuccessResponse,
    VastAsset,
    VastFormatAsset,
    VastFormatGroupAsset,
    VastTrackerAsset,
    VehicleUnit,
    VendorPricingOptionUnion,
    VideoFormatAsset,
    VideoFormatGroupAsset,
    WebhookFormatAsset,
    WebhookFormatGroupAsset,
    WholesaleFeedSignal,
    ZipAsset,
)
from adcp.types.legacy import (
    LegacyBuildCreativeErrorResponse,
    LegacyBuildCreativeRequest,
    LegacyBuildCreativeResponse,
    LegacyBuildCreativeResponse1,
    LegacyBuildCreativeResponse2,
    LegacyBuildCreativeResponse3,
    LegacyBuildCreativeResponse4,
    LegacyBuildCreativeResponse5,
    LegacyBuildCreativeResponse6,
    LegacyBuildCreativeSubmittedResponse,
    LegacyBuildCreativeSuccessResponse,
    LegacyCreateMediaBuyRequest,
    LegacyCreativeAsset,
    LegacyCreativeFilters,
    LegacyFormat,
    LegacyFormatId,
    LegacyFormatReferenceStructuredObject,
    LegacyGetCreativeDeliveryResponse,
    LegacyGetMediaBuyDeliveryResponse,
    LegacyGetMediaBuysResponse,
    LegacyGetProductsRequest,
    LegacyGetProductsResponse,
    LegacyListCreativeFormatsRequest,
    LegacyListCreativeFormatsResponse,
    LegacyListCreativesRequest,
    LegacyListCreativesResponse,
    LegacyPackage,
    LegacyPackageRequest,
    LegacyPackageUpdate,
    LegacyPlacement,
    LegacyPreviewCreativeBatchResponse,
    LegacyPreviewCreativeRequest,
    LegacyPreviewCreativeResponse,
    LegacyPreviewCreativeResponse1,
    LegacyPreviewCreativeResponse2,
    LegacyPreviewCreativeResponse3,
    LegacyPreviewCreativeSingleResponse,
    LegacyPreviewCreativeVariantResponse,
    LegacyProduct,
    LegacyProductFilters,
    LegacyProductFormatDeclaration,
    LegacySyncCreativesRequest,
    LegacyUpdateMediaBuyRequest,
)

CreateMediaBuyRequest = _canonical_creative.CreateMediaBuyRequest
CreateMediaBuyResponse = _canonical_creative.CreateMediaBuyResponse
CreateMediaBuyResponse1 = _canonical_creative.CreateMediaBuyResponse1
CreateMediaBuySuccessResponse = _canonical_creative.CreateMediaBuyResponse1
CreateMediaBuyErrorResponse = _canonical_creative.CreateMediaBuyResponse2
CreateMediaBuySubmittedResponse = _canonical_creative.CreateMediaBuyResponse3
Creative = _canonical_creative.Creative
CreativeAsset = _canonical_creative.CreativeAsset
CreativeFilters = _canonical_creative.CreativeFilters
CreativeManifest = _canonical_creative.CreativeManifest
CreativeVariant = _canonical_creative.CreativeVariant
Format = _canonical_creative.Format
GetCreativeDeliveryResponse = _canonical_creative.GetCreativeDeliveryResponse
GetMediaBuyDeliveryResponse = _canonical_creative.GetMediaBuyDeliveryResponse
GetMediaBuysResponse = _canonical_creative.GetMediaBuysResponse
GetProductsRequest = _canonical_creative.GetProductsRequest
GetProductsResponse = _canonical_creative.GetProductsResponse
GetProductsSuccessResponse = GetProductsResponse
GetProductsResponseUnion = (
    GetProductsResponse
    | GetProductsSubmittedResponse
    | GetProductsWorkingResponse
    | GetProductsInputRequiredResponse
)
ListCreativesRequest = _canonical_creative.ListCreativesRequest
ListCreativesResponse = _canonical_creative.ListCreativesResponse
Package = _canonical_creative.Package
PackageRequest = _canonical_creative.PackageRequest
PackageUpdate = _canonical_creative.PackageUpdate
Placement = _canonical_creative.Placement
Product = _canonical_creative.Product
ProductFormatDeclaration = _canonical_creative.ProductFormatDeclaration
ProductFilters = _canonical_creative.ProductFilters
SyncCreativesRequest = _canonical_creative.SyncCreativesRequest
UpdateMediaBuyRequest = _canonical_creative.UpdateMediaBuyRequest
UpdateMediaBuyResponse = _canonical_creative.UpdateMediaBuyResponse
UpdateMediaBuyResponse1 = _canonical_creative.UpdateMediaBuyResponse1
UpdateMediaBuyResponse3 = _canonical_creative.UpdateMediaBuyResponse3
UpdateMediaBuySuccessResponse = _canonical_creative.UpdateMediaBuyResponse1
UpdateMediaBuyErrorResponse = _canonical_creative.UpdateMediaBuyResponse2
UpdateMediaBuySubmittedResponse = _canonical_creative.UpdateMediaBuyResponse3

# Re-export core types (not in generated, but part of public API)
# Note: We don't import TaskStatus here to avoid shadowing GeneratedTaskStatus
# Users should import TaskStatus from adcp.types.core directly if they need the core enum
from adcp.types.core import (
    AgentConfig,
    Member,
    Policy,
    PolicyExemplar,
    PolicyExemplars,
    PolicyHistory,
    PolicyRevision,
    PolicySummary,
    Protocol,
    ResolvedBrand,
    ResolvedProperty,
    TaskResult,
    WebhookMetadata,
)

# Deprecated compatibility types from the root brand discovery document. The
# document collides with the ``brand/`` task-schema package, so codegen emits
# it into a dedicated module.
from adcp.types.generated_poc.brand_discovery import Asset, Disclaimer, Fonts, ProductCatalog
from adcp.types.generated_poc.core.catalog_item_delivery_metrics import (
    CatalogItemDeliveryMetrics as ByCatalogItemItem,
)
from adcp.types.generated_poc.core.outcome_measurement import OutcomeMeasurement
from adcp.types.generated_poc.enums.metric_type import MetricType

# Status: _generated picks invoice status (get_account_financials_response) due to
# alphabetical module sort. Import the delivery status variant directly for backward compat.
from adcp.types.generated_poc.media_buy.get_media_buy_delivery_response import (  # noqa: E501
    Status,
)

# Re-export type guards for discriminated union response handling
from adcp.types.guards import (  # noqa: F401
    is_activate_signal_error,
    is_activate_signal_success,
    is_adcp_error,
    is_adcp_success,
    is_build_creative_error,
    is_build_creative_submitted,
    is_build_creative_success,
    is_calibrate_content_success,
    is_create_media_buy_error,
    is_create_media_buy_success,
    is_get_account_financials_error,
    is_get_account_financials_success,
    is_get_creative_features_success,
    is_log_event_error,
    is_log_event_success,
    is_performance_feedback_error,
    is_performance_feedback_success,
    is_sync_accounts_error,
    is_sync_accounts_success,
    is_sync_catalogs_error,
    is_sync_catalogs_submitted,
    is_sync_catalogs_success,
    is_sync_creatives_error,
    is_sync_creatives_submitted,
    is_sync_creatives_success,
    is_update_media_buy_error,
    is_update_media_buy_success,
    is_validate_content_delivery_success,
)
from adcp.types.projections import (
    AccountResponse,
    BusinessEntityResponse,
    project_geo_postal_areas,
    to_account_response,
)
from adcp.types.registry import BrandSource

# Schema-variant marker for cross-class entity overrides (#710). Adopters
# annotate Pydantic field overrides with ``SchemaVariant[T]`` instead of
# ``# type: ignore[assignment]`` when substituting a sibling class for the
# parent's declared type. Activate the mypy plugin via
# ``[tool.mypy] plugins = ["adcp.types.mypy_plugin"]`` to suppress the
# override-compat check on those fields.
from adcp.types.variants import SchemaVariant

# Semantic aliases for auto-generated field enum names
ListCreativesField = Field1

# FieldModel: _generated picks brand.get_brand_identity_request.FieldModel due to
# alphabetical module sort. Override to preserve backward compat with the original
# get_products_request variant (which the generator renamed to Field1 in that module).
FieldModel = GetProductsField  # noqa: F811

# Backward compatibility aliases
AssetType = AssetContentType  # Use AssetContentType instead
Measurement = OutcomeMeasurement  # Renamed upstream to OutcomeMeasurement
Results = GetMediaBuyDeliveryResponse

# Pricing type renames: upstream merged auction/fixed variants into single types
CpmAuctionPricingOption = CpmPricingOption
CpmFixedRatePricingOption = CpmPricingOption
VcpmAuctionPricingOption = VcpmPricingOption
VcpmFixedRatePricingOption = VcpmPricingOption

# Activation key schema change: property_id/property_tag → segment_id/key_value
PropertyIdActivationKey = SegmentIdActivationKey
PropertyTagActivationKey = KeyValueActivationKey

# Deprecated: types removed from upstream schemas entirely
# Performance was removed; PerformanceFeedback is the replacement
Performance = PerformanceFeedback

# MediaSubAsset (SubAsset1) and TextSubAsset (SubAsset2) were removed from the
# upstream schema with no replacement. These stubs exist only to provide a clear
# error message for code that still references them.


class MediaSubAsset:
    """Removed from ADCP schema. Previously SubAsset with asset_kind='media'."""

    def __init__(self, *args: object, **kwargs: object) -> None:
        raise TypeError(
            "MediaSubAsset was removed from the ADCP schema. There is no direct replacement."
        )


class TextSubAsset:
    """Removed from ADCP schema. Previously SubAsset with asset_kind='text'."""

    def __init__(self, *args: object, **kwargs: object) -> None:
        raise TypeError(
            "TextSubAsset was removed from the ADCP schema. There is no direct replacement."
        )


# Preview response rename aliases (per-mode Request variants were removed when
# PreviewCreativeRequest collapsed to a single class with a request_type enum).

# Schema renames from filter ref split (v1.0.0)
Action = CreativeAction
Capability = CreativeAgentCapability
CoBranding = CoBrandingRequirement
LandingPage = LandingPageRequirement
Method = HttpMethod
ModuleType = JavascriptModuleType
TrackingEvent = VastTrackingEvent  # Split into DaastTrackingEvent and VastTrackingEvent
Unit = DimensionUnit
OutputFormat = PreviewOutputFormat
ResponseType = WebhookResponseType
Scheme = AuthenticationScheme
SignalType = SignalCatalogType
UrlType = UrlAssetType
AvailableReportingFrequency = ReportingFrequency

# Internal normalization helpers used by generated response models and server
# envelope handling. Keep these importable through ``adcp.types`` for the
# repo's generated-type layering rule, but leave them out of ``__all__`` so they
# do not become part of the documented public API.
from adcp.types.media_buy_status_helpers import (  # noqa: E402
    MEDIA_BUY_LEGACY_STATUS_VALUES as MEDIA_BUY_LEGACY_STATUS_VALUES,
)
from adcp.types.media_buy_status_helpers import (
    unwrap_enum_value as unwrap_enum_value,
)

# Public surface re-exported by :mod:`adcp.types`. Defining ``__all__`` here
# lets the type-checking ``from adcp.types._eager import (...)`` block in
# ``__init__`` re-export these names under mypy --strict (--no-implicit-reexport).
# This is the full importable surface (documented types + internal re-export
# helpers like the guard functions); the documented public list is
# ``adcp.types.__all__``.
__all__ = [
    # AdCP 3.2 compact media-buy lifecycle
    "AcceptProposalRequest",
    "AcceptProposalResponse",
    "AcceptedLoss",
    "AcceptanceContext",
    "AcceptancePolicyCatalog",
    "AcceptancePolicyDiscovery",
    "AcceptancePolicyProfile",
    "AcceptancePolicyProfileId",
    "AcceptancePolicyProfileIds",
    "AcceptancePolicyRequirement",
    "AcceptancePolicyRule",
    "CanonicalMediaBuyAction",
    "CanonicalMediaBuyActionMode",
    "CanonicalMediaBuyActionName",
    "CanonicalProductAction",
    "CommercialTerms",
    "MediaBuyAvailableAction",
    "MediaBuyActionMode",
    "MediaBuyChangeTerm",
    "MediaBuyChangeTermConstraints",
    "MediaBuyChangeTermId",
    "MediaBuyValidAction",
    "BudgetChangeConstraints",
    "EffectiveTimingChangeConstraints",
    "FlightChangeConstraints",
    "PackageCountChangeConstraints",
    "ProductAllowedAction",
    "RegistryAcceptancePolicyProfileReference",
    "BuyProductsRequest",
    "BuyProductsResponse",
    "ControlMediaBuyRequest",
    "ControlMediaBuyResponse",
    "CompatibilityPurchaseCoordinatorInput",
    "DeclineProposalsRequest",
    "DeclineProposalsResponse",
    "ListProductsRequest",
    "ListProductsResponse",
    "RefineProposalsRequest",
    "RefineProposalsResponse",
    "RequestProposalsRequest",
    "RequestProposalsResponse",
    "UnsupportedRefinementDimensionDetails",
    # Structured protocol error details
    "AccessibilityViolationDetails",
    "AccountMovedDetails",
    "AccountSetupRequiredDetails",
    "ActionNotAllowedDetails",
    "ActionNotAllowedReason",
    "AgentPermissionDeniedDetails",
    "AgentDeclarations",
    "AgentNotificationConfig",
    "AgentNotificationConfigState",
    "AgentReportingDestination",
    "AgentReportingDestinationState",
    "AudienceTooSmallDetails",
    "BillingNotPermittedForAgentDetails",
    "BillingNotSupportedDetails",
    "BudgetTooLowDetails",
    "ConflictDetails",
    "CreativeRejectedDetails",
    "PolicyViolationDetails",
    "RateLimitedDetails",
    "StaleResponseDetails",
    "VendorErrorCodeRegistry",
    "VersionUnsupportedDetails",
    "A2UiComponent",
    "A2UiSurface",
    "Account",
    "AccountAuthorization",
    "AccountIdReference",
    "AccountReference",
    "AccountReferenceById",
    "AccountReferenceByNaturalKey",
    "InlineAccountReference",
    "AccountResponse",
    "AccountScope",
    "AccountWithAuthorization",
    "AcquireRightsAcquiredResponse",
    "AcquireRightsErrorResponse",
    "AcquireRightsPendingResponse",
    "AcquireRightsRejectedResponse",
    "AcquireRightsRequest",
    "AcquireRightsResponse",
    "AcquireRightsResponse1",
    "Action",
    "ActivateSignalErrorResponse",
    "ActivateSignalRequest",
    "ActivateSignalResponse",
    "ActivateSignalResponse1",
    "ActivateSignalSuccessResponse",
    "AdcpProtocol",
    "AdvertiserIndustry",
    "AgentConfig",
    "AgentDeployment",
    "AgentDestination",
    "AggregatedTotals",
    "AiTool",
    "Artifact",
    "ArtifactWebhookPayload",
    "Asset",
    "AssetContentType",
    "AssetInstance",
    "AssetInstanceType",
    "AssetVariant",
    "AssetType",
    "AssignedPackage",
    "Assignments",
    "AudienceSource",
    "AudioContent",
    "AudioFormatAsset",
    "AudioFormatGroupAsset",
    "Authentication",
    "AuthenticationScheme",
    "AuthorizationRequiredDetails",
    "AuthorizedAgent",
    "AuthorizedAgents",
    "AuthorizedAgentsByInlineProperties",
    "AuthorizedAgentsByPropertyId",
    "AuthorizedAgentsByPropertyTag",
    "AuthorizedAgentsByPublisherProperties",
    "AuthorizedAgentsBySignalId",
    "AuthorizedAgentsBySignalTag",
    "AvailableMetric",
    "AvailablePackage",
    "AvailableReportingFrequency",
    "BothPreviewRender",
    "BrandReference",
    "BrandSource",
    "BriefAsset",
    "BriefFormatAsset",
    "BuildCreativeCreative",
    "ProductDiscoveryProductId",
    "RequestProposalsProductId",
    "BusinessEntity",
    "BusinessEntityResponse",
    "BuyingMode",
    "ByCatalogItemItem",
    "ByPackageItem",
    "CalibrateContentErrorResponse",
    "CalibrateContentRequest",
    "CalibrateContentResponse",
    "CalibrateContentResponse1",
    "CalibrateContentSuccessResponse",
    "CanonicalAssetSource",
    "CanonicalCompositionModel",
    "CanonicalFormatAgentPlacement",
    "CanonicalFormatBase",
    "CanonicalFormatDaastAudio",
    "CanonicalFormatDisplayTag",
    "CanonicalFormatHostedAudio",
    "CanonicalFormatHostedVideo",
    "CanonicalFormatHtml5Banner",
    "CanonicalFormatImage",
    "CanonicalFormatImageCarousel",
    "CanonicalFormatKind",
    "CanonicalFormatNativeInFeed",
    "CanonicalFormatResponsiveCreative",
    "CanonicalFormatSponsoredPlacement",
    "CanonicalFormatVastVideo",
    "CanonicalProjectionReference",
    "CanonicalSlotOverride",
    "CardAsset",
    "CapabilitiesAccount",
    "CapabilitiesCreative",
    "CapabilitiesMediaBuy",
    "CapabilitiesPreviewRenderingOrigin",
    "CapabilitiesPreviewRoute",
    "Capability",
    "Catalog",
    "CatalogAction",
    "CatalogAsset",
    "CatalogFieldBinding",
    "CatalogFieldBinding1",
    "CatalogFieldMapping",
    "CatalogFormatAsset",
    "CatalogGroupBinding",
    "CanonicalProposalTotalBudgetGuidance",
    "DownstreamConnectionRequiredForItem",
    "LegacyProposalTotalBudgetGuidance",
    "RefineProposalsTotalBudgetGuidance",
    "BrandIdentity",
    "CatalogItemStatus",
    "CatalogRequirements",
    "CatalogType",
    "CheckGovernanceRequest",
    "CheckGovernanceResponse",
    "CoBranding",
    "CoBrandingRequirement",
    "CollectionList",
    "CollectionListChangedWebhook",
    "CollectionListFilters",
    "Colors",
    "ComplyErrorResponse",
    "ComplyListScenariosResponse",
    "ComplySimulationResponse",
    "ComplyStateTransitionResponse",
    "ComplyTestControllerRequest",
    "ComplyTestControllerResponse",
    "ComplyTestControllerResponse1",
    "ConsentBasis",
    "Contact",
    "ContentIdType",
    "ContentStandards",
    "ContextMatchRequest",
    "ContextMatchResponse",
    "ContextObject",
    "CoreAccount",
    "CoreCreditLimit",
    "CoreGovernanceAgent",
    "CoreMediaBuy",
    "CoreSetup",
    "Country",
    "CpaPricingOption",
    "CpcPricingOption",
    "CpcvPricingOption",
    "CpmAuctionPricingOption",
    "CpmFixedRatePricingOption",
    "CpmPricingOption",
    "CppPricingOption",
    "CpvPricingOption",
    "CreateCollectionListRequest",
    "CreateCollectionListResponse",
    "CreateContentStandardsErrorResponse",
    "CreateContentStandardsRequest",
    "CreateContentStandardsResponse",
    "CreateContentStandardsResponse1",
    "CreateContentStandardsSuccessResponse",
    "CreateMediaBuyAuthentication",
    "CreateMediaBuyErrorResponse",
    "CreateMediaBuyRequest",
    "CreateMediaBuyResponse",
    "CreateMediaBuyResponse1",
    "CreateMediaBuySubmittedResponse",
    "CreateMediaBuySuccessResponse",
    "CreatePropertyListRequest",
    "CreatePropertyListResponse",
    "Creative",
    "CreativeAction",
    "CreativeAgent",
    "CreativeAgentCapability",
    "CreativeApproval",
    "CreativeApprovalStatus",
    "CreativeAsset",
    "CreativeAssignment",
    "CreativeFilters",
    "CreativeManifest",
    "CreativePolicy",
    "CreativeStatus",
    "CreativeVariant",
    "CreditLimit",
    "CssContent",
    "CssFormatAsset",
    "CssFormatGroupAsset",
    "DaastAsset",
    "DaastFormatAsset",
    "DaastFormatGroupAsset",
    "DaastTrackerAsset",
    "DaastTrackingEvent",
    "DaastVersion",
    "DailyBreakdownItem",
    "DateRange",
    "DatetimeRange",
    "DayOfWeek",
    "DaypartTarget",
    "DeleteCollectionListRequest",
    "DeleteCollectionListResponse",
    "DeletePropertyListRequest",
    "DeletePropertyListResponse",
    "DeliveryCreative",
    "DeliveryForecast",
    "DeliveryMeasurement",
    "DeliveryMetrics",
    "DeliveryStatus",
    "DeliveryType",
    "DemographicSystem",
    "Deployment",
    "Destination",
    "DevicePlatform",
    "DeviceType",
    "DimensionUnit",
    "Dimensions",
    "Disclaimer",
    "DoohMetrics",
    "DownstreamConnectionRequirement",
    "Duration",
    "DurationUnit",
    "Error",
    "ErrorCode",
    "EventType",
    "ExtensionObject",
    "FeedFormat",
    "FeedbackSource",
    "Field1",
    "FieldModel",
    "FlatRatePricingOption",
    "Fonts",
    "ForecastMethod",
    "ForecastPoint",
    "ForecastRange",
    "ForecastRangeUnit",
    "ForecastableMetric",
    "Format",
    "FormatAssetUnion",
    "FormatCard",
    "FormatCardDetailed",
    "FormatIdParameter",
    "FormatOptionReference",
    "FrequencyCap",
    "FrequencyCapScope",
    "GeneratedTaskStatus",
    "GeoCountry",
    "GeoMetro",
    "GeoRegion",
    "GetAccountFinancialsErrorResponse",
    "GetAccountFinancialsRequest",
    "GetAccountFinancialsResponse",
    "GetAccountFinancialsResponse1",
    "GetAccountFinancialsSuccessResponse",
    "GetAdcpCapabilitiesRequest",
    "GetAdcpCapabilitiesResponse",
    "GetPrincipalRequest",
    "GetPrincipalResponse",
    "GetReportingStatusRequest",
    "GetReportingStatusResponse",
    "GetBrandIdentityErrorResponse",
    "GetBrandIdentityField",
    "GetBrandIdentityRequest",
    "GetBrandIdentityResponse",
    "GetBrandIdentityResponse1",
    "GetBrandIdentitySuccessResponse",
    "GetCollectionListRequest",
    "GetCollectionListResponse",
    "GetContentStandardsErrorResponse",
    "GetContentStandardsRequest",
    "GetContentStandardsResponse",
    "GetContentStandardsResponse1",
    "GetContentStandardsSuccessResponse",
    "GetCreativeDeliveryByBuyerRefRequest",
    "GetCreativeDeliveryByCreativeRequest",
    "GetCreativeDeliveryByMediaBuyRequest",
    "GetCreativeDeliveryRequest",
    "GetCreativeDeliveryResponse",
    "GetCreativeFeaturesErrorResponse",
    "GetCreativeFeaturesRequest",
    "GetCreativeFeaturesResponse",
    "GetCreativeFeaturesResponse1",
    "GetCreativeFeaturesSuccessResponse",
    "GetMediaBuyArtifactsErrorResponse",
    "GetMediaBuyArtifactsRequest",
    "GetMediaBuyArtifactsResponse",
    "GetMediaBuyArtifactsResponse1",
    "GetMediaBuyArtifactsSuccessResponse",
    "GetMediaBuyDeliveryRequest",
    "GetMediaBuyDeliveryResponse",
    "GetMediaBuysMediaBuy",
    "GetMediaBuysRequest",
    "GetMediaBuysResponse",
    "GetPlanAuditLogsRequest",
    "GetPlanAuditLogsResponse",
    "GetProductsBriefRequest",
    "GetProductsField",
    "GetProductsInputRequiredResponse",
    "GetProductsRefineRequest",
    "GetProductsRequest",
    "GetProductsResponse",
    "GetProductsResponseUnion",
    "GetProductsSubmittedResponse",
    "GetProductsSuccessResponse",
    "GetProductsWholesaleRequest",
    "GetProductsWorkingResponse",
    "GetPropertyListRequest",
    "GetPropertyListResponse",
    "GetRightsErrorResponse",
    "GetRightsRequest",
    "GetRightsResponse",
    "GetRightsResponse1",
    "GetRightsSuccessResponse",
    "GetSignalsDiscoveryRequest",
    "GetSignalsLookupRequest",
    "GetSignalsRequest",
    "GetSignalsResponse",
    "GetSignalsResponseUnion",
    "GetSignalsSignal",
    "GetSignalsSubmittedResponse",
    "GetSignalsSuccessResponse",
    "GetSignalsWorkingResponse",
    "GetTaskStatusRequest",
    "GetTaskStatusResponse",
    "GovernanceAgent",
    "GovernanceAuthentication",
    "GroupFormatAssetUnion",
    "Gtin",
    "HtmlContent",
    "HtmlFormatAsset",
    "HtmlFormatGroupAsset",
    "HtmlPreviewRender",
    "HttpMethod",
    "Identifier",
    "IdentityMatchRequest",
    "IdentityMatchResponse",
    "IdentityMatchTmpxMacro",
    "ImageContent",
    "ImageFormatAsset",
    "ImageFormatGroupAsset",
    "InlineDaastAsset",
    "InlineVastAsset",
    "Input",
    "JavascriptContent",
    "JavascriptFormatAsset",
    "JavascriptFormatGroupAsset",
    "JavascriptModuleType",
    "KellerType",
    "KeyValueActivationKey",
    "LandingPage",
    "LandingPageRequirement",
    "LegacyBuildCreativeRequest",
    "LegacyBuildCreativeErrorResponse",
    "LegacyBuildCreativeResponse",
    "LegacyBuildCreativeResponse1",
    "LegacyBuildCreativeResponse2",
    "LegacyBuildCreativeResponse3",
    "LegacyBuildCreativeResponse4",
    "LegacyBuildCreativeResponse5",
    "LegacyBuildCreativeResponse6",
    "LegacyBuildCreativeSubmittedResponse",
    "LegacyBuildCreativeSuccessResponse",
    "LegacyCreateMediaBuyRequest",
    "LegacyCreativeAsset",
    "LegacyCreativeFilters",
    "LegacyFormat",
    "LegacyFormatId",
    "LegacyFormatReferenceStructuredObject",
    "LegacyGetCreativeDeliveryResponse",
    "LegacyGetMediaBuyDeliveryResponse",
    "LegacyGetMediaBuysResponse",
    "LegacyGetProductsRequest",
    "LegacyGetProductsResponse",
    "LegacyListCreativeFormatsRequest",
    "LegacyListCreativeFormatsResponse",
    "LegacyListCreativesRequest",
    "LegacyListCreativesResponse",
    "LegacyPackage",
    "LegacyPackageRequest",
    "LegacyPackageUpdate",
    "LegacyPlacement",
    "LegacyPreviewCreativeRequest",
    "LegacyPreviewCreativeBatchResponse",
    "LegacyPreviewCreativeResponse",
    "LegacyPreviewCreativeResponse1",
    "LegacyPreviewCreativeResponse2",
    "LegacyPreviewCreativeResponse3",
    "LegacyPreviewCreativeSingleResponse",
    "LegacyPreviewCreativeVariantResponse",
    "LegacyProduct",
    "LegacyProductFormatDeclaration",
    "LegacyProductFilters",
    "LegacySyncCreativesRequest",
    "LegacyUpdateMediaBuyRequest",
    "ListAccountsRequest",
    "ListAccountsResponse",
    "ListAccountChangesRequest",
    "ListAccountChangesResponse",
    "ListCollectionListsRequest",
    "ListCollectionListsResponse",
    "ListContentStandardsErrorResponse",
    "ListContentStandardsRequest",
    "ListContentStandardsResponse",
    "ListContentStandardsResponse1",
    "ListContentStandardsSuccessResponse",
    "ListCreativesCanonicalCreative",
    "ListCreativesCreative",
    "ListCreativesCreativeItem",
    "ListCreativesField",
    "ListCreativesLegacyCreative",
    "ListCreativesRequest",
    "ListCreativesResponse",
    "ListCreativesSort",
    "ListPropertyListsRequest",
    "ListPropertyListsResponse",
    "ListTasksRequest",
    "ListTasksResponse",
    "ListTasksSort",
    "ListTransformersRequest",
    "ListTransformersResponse",
    "LogEventErrorResponse",
    "LogEventRequest",
    "LogEventResponse",
    "LogEventResponse1",
    "LogEventSuccessResponse",
    "Logo",
    "MEDIA_BUY_LEGACY_STATUS_VALUES",
    "MarkdownAsset",
    "MarkdownFlavor",
    "MarkdownFormatAsset",
    "MarkdownFormatGroupAsset",
    "McpWebhookPayload",
    "Measurement",
    "MeasurementPeriod",
    "MediaBuy",
    "MediaBuyDelivery",
    "MediaBuyDeliveryStatus",
    "MediaBuyDeliveryWebhookResult",
    "MediaBuyFeatures",
    "MediaBuyPackage",
    "MediaBuyStatus",
    "MediaChannel",
    "MediaSubAsset",
    "Member",
    "Metadata",
    "Method",
    "MetricType",
    "ModuleType",
    "NotificationAuthentication",
    "NotificationConfig",
    "NotificationType",
    "OfferPrice",
    "Offering",
    "OfferingAssetConstraint",
    "OfferingAssetGroup",
    "OptimizationGoal",
    "OutcomeMeasurement",
    "OutputFormat",
    "Overlay",
    "OverlayUnit",
    "Pacing",
    "Package",
    "PackageRequest",
    "PackageSignalTargeting",
    "PackageSignalTargetingGroup",
    "PackageSignalTargetingGroups",
    "PackageUpdate",
    "Pagination",
    "PaginationRequest",
    "PaginationResponse",
    "Parameters",
    "PaymentTerms",
    "Performance",
    "PerformanceFeedback",
    "PixelTrackerAsset",
    "PixelTrackerEvent",
    "PixelTrackerMethod",
    "Placement",
    "PlacementPresentationDocument",
    "PlacementPresentationReference",
    "PlacementReference",
    "PlatformDeployment",
    "PlatformDestination",
    "Policy",
    "PolicyExemplar",
    "PolicyExemplars",
    "PolicyHistory",
    "PolicyRevision",
    "PolicySummary",
    "PostalArea",
    "PreviewOutputFormat",
    "PreviewRender",
    "PreviewRendererMetadata",
    "PreviewRenderingOrigin",
    "PriceGuidance",
    "PricingCurrency",
    "PricingModel",
    "PricingOption",
    "PrimaryCountry",
    "PrincipalAppliedResult",
    "PrincipalChangedWebhook",
    "PrincipalConfiguration",
    "PrincipalCurrentResult",
    "PrincipalDeclarationsState",
    "PrincipalKind",
    "PrincipalReadFailedResult",
    "PrincipalReadResult",
    "PrincipalRecognizedResult",
    "PrincipalState",
    "PrincipalSyncFailedResult",
    "PrincipalSyncResult",
    "PrincipalUnconfiguredResult",
    "PrincipalValidatedResult",
    "Product",
    "ProductCard",
    "ProductCardDetailed",
    "ProductCatalog",
    "ProductFilters",
    "ProductFormatDeclaration",
    "ProductFormatSellerPreference",
    "ProductSignalTargetingOption",
    "ProviderRegistrationTmpxMacro",
    "PublishedPostAsset",
    "Property",
    "PropertyId",
    "PropertyIdActivationKey",
    "PropertyIdentifierTypes",
    "PropertyList",
    "PropertyListChangedWebhook",
    "PropertyListFilters",
    "PropertyListReference",
    "PropertyTag",
    "PropertyTagActivationKey",
    "PropertyType",
    "Proposal",
    "Protocol",
    "ProtocolEnvelope",
    "ProtocolResponse",
    "Provenance",
    "ProvenanceDeclaredBy",
    "RequestSigningRequiredForItem",
    "ProvidePerformanceFeedbackByBuyerRefRequest",
    "ProvidePerformanceFeedbackByMediaBuyRequest",
    "ProvidePerformanceFeedbackErrorResponse",
    "ProvidePerformanceFeedbackRequest",
    "ProvidePerformanceFeedbackResponse",
    "ProvidePerformanceFeedbackResponse1",
    "ProvidePerformanceFeedbackSuccessResponse",
    "PublisherDomain",
    "PublisherDesignatedPreviewProvider",
    "PublisherIdentifierTypes",
    "PublisherPreviewRoute",
    "PublisherProperties",
    "PublisherPropertiesAll",
    "PublisherPropertiesById",
    "PublisherPropertiesByTag",
    "PushNotificationAuthentication",
    "PushNotificationConfig",
    "QuartileData",
    "QuerySummary",
    "ReachUnit",
    "RealEstateUnit",
    "Recovery",
    "ReferenceRenderer",
    "ReferenceRendererProvenance",
    "Refine",
    "RefinementApplied",
    "RefinementApplied1",
    "RefinementApplied2",
    "RefinementApplied3",
    "Renders",
    "RepeatableAssetGroup",
    "ReportPlanOutcomeRequest",
    "ReportPlanOutcomeResponse",
    "ReportPlanAdjustmentRequest",
    "ReportPlanAdjustmentResponse",
    "ReportUsageRequest",
    "ReportUsageResponse",
    "ReportingBucket",
    "ReportingCanonicalContentDigest",
    "ReportingCanonicalizationContract",
    "ReportingCapabilities",
    "ReportingControlTotal",
    "ReportingDatasetShareDestination",
    "ReportingDeliveryCapabilities",
    "ReportingDeliveryConfiguration",
    "ReportingDeliveryConfigurationState",
    "ReportingDeliveryMethod",
    "ReportingDeliveryOffering",
    "ReportingDeliveryReadyWebhook",
    "ReportingFileCompression",
    "ReportingFileEntry",
    "ReportingFileManifest",
    "ReportingFrequency",
    "ReportingMaterialization",
    "ReportingObligation",
    "ReportingPeriod",
    "ReportingReceipt",
    "ReportingReconciliationMode",
    "ReportingReportDefinition",
    "ReportingResource",
    "ReportingRevision",
    "ReportingSchedule",
    "ReportingScheduleOffering",
    "ReportingStatusIssue",
    "ReportingVerification",
    "ReportingVerificationProfile",
    "ReportingWebhook",
    "ReportingWebhookAuthentication",
    "ReportingWriteDestination",
    "Request",
    "ResolvedBrand",
    "ResolvedProperty",
    "Response",
    "ResponsePayloadJwsEnvelope",
    "ResponseType",
    "Responsive",
    "Results",
    "RightsPricingOption",
    "RightsTerms",
    "SchemaVariant",
    "Scheme",
    "Security",
    "SegmentIdActivationKey",
    "SellerAgentReference",
    "Setup",
    "SiCapabilities",
    "SiGetOfferingRequest",
    "SiGetOfferingResponse",
    "SiIdentity",
    "SiInitiateSessionRequest",
    "SiInitiateSessionResponse",
    "SiSendActionResponseRequest",
    "SiSendMessageRequest",
    "SiSendMessageResponse",
    "SiSendTextMessageRequest",
    "SiSponsoredContextDeclaredBy",
    "SiTerminateSessionRequest",
    "SiTerminateSessionResponse",
    "SiUiElement",
    "Signal",
    "SignalAvailabilityType",
    "SignalCatalogType",
    "SignalDefinitionEnrichment",
    "SignalFilters",
    "SignalListing",
    "SignalPricingOption",
    "SignalRef",
    "SignalTargeting",
    "SignalTargetingExpression",
    "SignalTargetingRules",
    "SignalType",
    "Snapshot",
    "SnapshotUnavailableReason",
    "Sort",
    "SortApplied",
    "SortDirection",
    "Source",
    "Status",
    "StatusSummary",
    "SyncAccountsAccount",
    "SyncAccountsCreditLimit",
    "SyncAccountsErrorResponse",
    "SyncAccountsRequest",
    "SyncAccountsResponse",
    "SyncAccountsResponse1",
    "SyncAccountsSetup",
    "SyncAccountsSuccessResponse",
    "SyncAudiencesAudience",
    "SyncAudiencesErrorResponse",
    "SyncAudiencesRequest",
    "SyncAudiencesResponse",
    "SyncAudiencesResponse1",
    "SyncAudiencesSubmittedResponse",
    "SyncAudiencesSuccessResponse",
    "SyncCatalogResult",
    "SyncCatalogsErrorResponse",
    "SyncCatalogsInputRequired",
    "SyncCatalogsRequest",
    "SyncCatalogsResponse",
    "SyncCatalogsResponse1",
    "SyncCatalogsSubmitted",
    "SyncCatalogsSubmittedResponse",
    "SyncCatalogsSuccessResponse",
    "SyncCatalogsWorking",
    "SyncCreativeResult",
    "SyncCreativesCreative",
    "SyncCreativesErrorResponse",
    "SyncCreativesRequest",
    "SyncCreativesResponse",
    "SyncCreativesResponse1",
    "SyncCreativesResponse3",
    "SyncCreativesSubmittedResponse",
    "SyncCreativesSuccessResponse",
    "SyncEventSourcesErrorResponse",
    "SyncEventSourcesRequest",
    "SyncEventSourcesResponse",
    "SyncEventSourcesResponse1",
    "SyncEventSourcesSetup",
    "SyncEventSourcesSuccessResponse",
    "SyncGovernanceAccount",
    "SyncGovernanceGovernanceAgent",
    "SyncGovernanceRequest",
    "SyncGovernanceResponse",
    "SyncAgentNotificationConfigsRequest",
    "SyncAgentNotificationConfigsResponse",
    "SyncPrincipalRequest",
    "SyncPrincipalResponse",
    "SyncReportingReceiptsRequest",
    "SyncReportingReceiptsResponse",
    "SyncPlansRequest",
    "SyncPlansResponse",
    "Tags",
    "TargetingOverlay",
    "TaskResult",
    "TaskType",
    "TasksListSort",
    "TextContent",
    "TextFormatAsset",
    "TextFormatGroupAsset",
    "TextSubAsset",
    "TimeBasedPricingOption",
    "TimeUnit",
    "TmpError",
    "TmpOffer",
    "Totals",
    "TrackingEvent",
    "Transform",
    "Unit",
    "UnknownFormatAsset",
    "UnknownGroupAsset",
    "UpdateCollectionListRequest",
    "UpdateCollectionListResponse",
    "UpdateContentStandardsErrorResponse",
    "UpdateContentStandardsRequest",
    "UpdateContentStandardsResponse",
    "UpdateContentStandardsResponse1",
    "UpdateContentStandardsSuccessResponse",
    "UpdateFrequency",
    "UpdateMediaBuyErrorResponse",
    "LegacyUpdateMediaBuyErrorResponse",
    "LegacyUpdateMediaBuySuccessResponse",
    "UpdateMediaBuyPackagesRequest",
    "UpdateMediaBuyPropertiesRequest",
    "UpdateMediaBuyRequest",
    "UpdateMediaBuyResponse",
    "UpdateMediaBuyResponse1",
    "UpdateMediaBuyResponse3",
    "UpdateMediaBuySubmittedResponse",
    "UpdateMediaBuySuccessResponse",
    "UpdatePropertyListRequest",
    "UpdatePropertyListResponse",
    "UpdateRightsRequest",
    "UpdateRightsResponse",
    "UrlAssetType",
    "UrlContent",
    "UrlDaastAsset",
    "UrlFormatAsset",
    "UrlFormatGroupAsset",
    "UrlPreviewRender",
    "UrlType",
    "UrlVastAsset",
    "V1CanonicalDimensions",
    "V1CanonicalGlobPattern",
    "V1CanonicalMapping",
    "V1CanonicalStructural",
    "V1CanonicalStructuralPattern",
    "V1CanonicalV2Projection",
    "V1V2CanonicalFormatMappingRegistry",
    "ValidateContentDeliveryErrorResponse",
    "ValidateContentDeliveryRequest",
    "ValidateContentDeliveryResponse",
    "ValidateContentDeliveryResponse1",
    "ValidateContentDeliverySuccessResponse",
    "ValidateInputRequest",
    "ValidateInputResponse",
    "ValidationMode",
    "VastAsset",
    "VastFormatAsset",
    "VastFormatGroupAsset",
    "VastTrackingEvent",
    "VastVersion",
    "VastTrackerAsset",
    "VcpmAuctionPricingOption",
    "VcpmFixedRatePricingOption",
    "VcpmPricingOption",
    "VehicleUnit",
    "ZipAsset",
    "VenueBreakdownItem",
    "VerifyBrandClaimPayload",
    "VerifyBrandClaimRequest",
    "VerifyBrandClaimResponse",
    "VerifyBrandClaimSignedResponse",
    "VerifyBrandClaimSignedSuccessPayload",
    "VerifyBrandClaimsErrorResponse",
    "VerifyBrandClaimsPayload",
    "VerifyBrandClaimsRequest",
    "VerifyBrandClaimsRequestBulk",
    "VerifyBrandClaimsResponse",
    "VerifyBrandClaimsResponseBulk",
    "VerifyBrandClaimsSignedResponse",
    "VerifyBrandClaimsSignedSuccessPayload",
    "VideoContent",
    "VideoFormatAsset",
    "VideoFormatGroupAsset",
    "ViewThreshold",
    "WcagLevel",
    "WebhookChallenge",
    "WebhookChallengeResponse",
    "WebhookContent",
    "WebhookFormatAsset",
    "WebhookFormatGroupAsset",
    "WebhookMetadata",
    "WebhookResponseType",
    "WholesaleFeedEvent",
    "WholesaleFeedSignal",
    "WholesaleFeedWebhook",
    "CpmVendorPricingOption",
    "CustomVendorPricingOption",
    "FlatFeeVendorPricingOption",
    "MissingMetric",
    "PercentOfMediaVendorPricingOption",
    "PerUnitVendorPricingOption",
    "ProductAllocation",
    "ProductFilterCountry",
    "PropertyIdentifier",
    "SignalCoverageForecast",
    "SignalCoverageRange",
    "TrustedMatch",
    "VendorPricingOptionUnion",
    "aliases",
    "generated",
    "is_activate_signal_error",
    "is_activate_signal_success",
    "is_adcp_error",
    "is_adcp_success",
    "is_build_creative_error",
    "is_build_creative_submitted",
    "is_build_creative_success",
    "is_calibrate_content_success",
    "is_create_media_buy_error",
    "is_create_media_buy_success",
    "is_get_account_financials_error",
    "is_get_account_financials_success",
    "is_get_creative_features_success",
    "is_log_event_error",
    "is_log_event_success",
    "is_performance_feedback_error",
    "is_performance_feedback_success",
    "is_sync_accounts_error",
    "is_sync_accounts_success",
    "is_sync_catalogs_error",
    "is_sync_catalogs_submitted",
    "is_sync_catalogs_success",
    "is_sync_creatives_error",
    "is_sync_creatives_submitted",
    "is_sync_creatives_success",
    "is_update_media_buy_error",
    "is_update_media_buy_success",
    "is_validate_content_delivery_success",
    "project_geo_postal_areas",
    "to_account_response",
    "unwrap_enum_value",
]
