# generated by datamodel-codegen:
#   filename:  media_buy/create_media_buy_request.json
#   timestamp: 2026-04-29T01:11:23+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import AnyUrl, AwareDatetime, ConfigDict, Field

from ..core import account_ref, brand_ref, business_entity
from ..core import context as context_1
from ..core import ext as ext_1
from ..core import push_notification_config as push_notification_config_1
from ..core import reporting_webhook as reporting_webhook_1
from ..core import start_timing
from ..enums import advertiser_industry as advertiser_industry_1
from ..enums import auth_scheme
from . import package_request


class TotalBudget(AdCPBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    amount: Annotated[float, Field(description="Total budget amount", ge=0.0)]
    currency: Annotated[str, Field(description="ISO 4217 currency code")]


class IoAcceptance(AdCPBaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    io_id: Annotated[
        str, Field(description="The io_id from the proposal's insertion_order being accepted")
    ]
    accepted_at: Annotated[
        AwareDatetime, Field(description="ISO 8601 timestamp when the IO was accepted")
    ]
    signatory: Annotated[
        str,
        Field(
            description="Who accepted the IO — agent identifier or human name",
            max_length=250,
            min_length=1,
        ),
    ]
    signature_id: Annotated[
        str | None,
        Field(
            description="Reference to the electronic signature from the signing service, when signing_url was used"
        ),
    ] = None


class Authentication(AdCPBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schemes: Annotated[
        list[auth_scheme.AuthenticationScheme],
        Field(
            description="Array of authentication schemes. Supported: ['Bearer'] for simple token auth, ['HMAC-SHA256'] for signature verification (recommended for production)",
            max_length=1,
            min_length=1,
        ),
    ]
    credentials: Annotated[
        str,
        Field(
            description="Credentials for authentication. For Bearer: token sent in Authorization header. For HMAC-SHA256: shared secret used to generate signature. Minimum 32 characters. Exchanged out-of-band during onboarding.",
            min_length=32,
        ),
    ]


class DeliveryMode(Enum):
    realtime = "realtime"
    batched = "batched"


class BatchFrequency(Enum):
    hourly = "hourly"
    daily = "daily"


class ArtifactWebhook(AdCPBaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    url: Annotated[AnyUrl, Field(description="Webhook endpoint URL for artifact delivery")]
    token: Annotated[
        str | None,
        Field(
            description="Optional client-provided token for webhook validation. Echoed back in webhook payload to validate request authenticity.",
            min_length=16,
        ),
    ] = None
    authentication: Annotated[
        Authentication,
        Field(description="Authentication configuration for webhook delivery (A2A-compatible)"),
    ]
    delivery_mode: Annotated[
        DeliveryMode,
        Field(
            description="How artifacts are delivered. 'realtime' pushes artifacts as impressions occur. 'batched' aggregates artifacts and pushes periodically (see batch_frequency)."
        ),
    ]
    batch_frequency: Annotated[
        BatchFrequency | None,
        Field(
            description="For batched delivery, how often to push artifacts. Required when delivery_mode is 'batched'."
        ),
    ] = None
    sampling_rate: Annotated[
        float | None,
        Field(
            description="Fraction of impressions to include (0-1). 1.0 = all impressions, 0.1 = 10% sample. Default: 1.0",
            ge=0.0,
            le=1.0,
        ),
    ] = None


class CreateMediaBuyRequest(AdCPBaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    adcp_major_version: Annotated[
        int | None,
        Field(
            description="The AdCP major version the buyer's payloads conform to. Sellers validate against their supported major_versions and return VERSION_UNSUPPORTED if unsupported. When omitted, the seller assumes its highest supported version.",
            ge=1,
            le=99,
        ),
    ] = None
    idempotency_key: Annotated[
        str,
        Field(
            description="Client-generated unique key for this request. If a request with the same idempotency_key and account has already been processed, the seller returns the existing media buy rather than creating a duplicate. MUST be unique per (seller, request) pair to prevent cross-seller correlation. Use a fresh UUID v4 for each request.",
            max_length=255,
            min_length=16,
            pattern="^[A-Za-z0-9_.:-]{16,255}$",
        ),
    ]
    plan_id: Annotated[
        str | None,
        Field(
            description="Campaign governance plan identifier. Required when the account has governance_agents. The seller includes this in the committed check_governance request so the governance agent can validate against the correct plan."
        ),
    ] = None
    account: Annotated[
        account_ref.AccountReference,
        Field(
            description="Account to bill for this media buy. Pass a natural key (brand, operator, optional sandbox) or a seller-assigned account_id from list_accounts."
        ),
    ]
    proposal_id: Annotated[
        str | None,
        Field(
            description="ID of a proposal from get_products to execute. When provided with total_budget, the publisher converts the proposal's allocation percentages into packages automatically. Alternative to providing packages array."
        ),
    ] = None
    total_budget: Annotated[
        TotalBudget | None,
        Field(
            description="Total budget for the media buy when executing a proposal. The publisher applies the proposal's allocation percentages to this amount to derive package budgets."
        ),
    ] = None
    packages: Annotated[
        list[package_request.PackageRequest] | None,
        Field(
            description="Array of package configurations. Required when not using proposal_id. When executing a proposal, this can be omitted and packages will be derived from the proposal's allocations.",
            min_length=1,
        ),
    ] = None
    brand: Annotated[
        brand_ref.BrandReference,
        Field(
            description="Brand reference for this media buy. Resolved to full brand identity at execution time from brand.json or the registry."
        ),
    ]
    advertiser_industry: Annotated[
        advertiser_industry_1.AdvertiserIndustry | None,
        Field(
            description="Industry classification for this specific campaign. A brand may operate across multiple industries (brand.json industries field), but each media buy targets one. For example, a consumer health company running a wellness campaign sends 'healthcare.wellness', not 'cpg'. Sellers map this to platform-native codes (e.g., Spotify ADV categories, LinkedIn industry IDs). When omitted, sellers may infer from the brand manifest's industries field."
        ),
    ] = None
    invoice_recipient: Annotated[
        business_entity.BusinessEntity | None,
        Field(
            description="Override the account's default billing entity for this specific buy. When provided, the seller invoices this entity instead. The seller MUST validate the invoice recipient is authorized for this account. When governance_agents are configured, the seller MUST include invoice_recipient in the check_governance request."
        ),
    ] = None
    io_acceptance: Annotated[
        IoAcceptance | None,
        Field(
            description="Acceptance of an insertion order from a committed proposal. Required when the proposal's insertion_order has requires_signature: true. References the io_id from the proposal's insertion_order."
        ),
    ] = None
    po_number: Annotated[str | None, Field(description="Purchase order number for tracking")] = None
    agency_estimate_number: Annotated[
        str | None,
        Field(
            description="Agency estimate or authorization number. Primary financial reference for broadcast buys — links the order to the agency's media plan and billing system. Travels with the order and Ad-IDs through the transaction lifecycle.",
            max_length=100,
        ),
    ] = None
    start_time: start_timing.StartTiming
    end_time: Annotated[
        AwareDatetime, Field(description="Campaign end date/time in ISO 8601 format")
    ]
    push_notification_config: Annotated[
        push_notification_config_1.PushNotificationConfig | None,
        Field(
            description="Optional webhook configuration for async task status notifications. Publisher will send webhooks when status changes (working, input-required, completed, failed). The client generates an operation_id and embeds it in the URL before sending — the publisher echoes it back in webhook payloads for correlation."
        ),
    ] = None
    reporting_webhook: Annotated[
        reporting_webhook_1.ReportingWebhook | None,
        Field(description="Optional webhook configuration for automated reporting delivery"),
    ] = None
    artifact_webhook: Annotated[
        ArtifactWebhook | None,
        Field(
            description="Optional webhook configuration for content artifact delivery. Used by governance agents to validate content adjacency. Seller pushes artifacts to this endpoint; orchestrator forwards to governance agent for validation."
        ),
    ] = None
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None
