# generated by datamodel-codegen:
#   filename:  media_buy/get_reporting_status_request.json
#   timestamp: 2026-09-01T19:37:00+00:00

from __future__ import annotations

from adcp.types._str_enum import StrEnum
from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import AwareDatetime, ConfigDict, Field, RootModel

from ..core import canonical_account_ref
from ..core import context as context_1
from ..core import ext as ext_1
from ..core import pagination_request, reporting_coverage, reporting_delivery_offering
from ..core.version_envelope import AdcpVersionEnvelope
from ..enums import reporting_finality, reporting_health


class DeliveryConfigId(RootModel[str]):
    root: Annotated[str, Field(max_length=64, min_length=1, pattern='^[A-Za-z0-9_.:-]{1,64}$')]


class Period(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    start: AwareDatetime
    end: AwareDatetime


class ReportingStatusView(StrEnum):
    summary = 'summary'
    periods = 'periods'
    revision = 'revision'


class GetReportingStatusRequest(AdcpVersionEnvelope):
    account: Annotated[
        canonical_account_ref.CanonicalAccountReference,
        Field(description='Account whose caller-owned reporting status is queried.'),
    ]
    view: ReportingStatusView
    media_buy_ids: Annotated[
        list[reporting_coverage.ReportingMediaBuyId] | None,
        Field(
            description='Optional summary/periods scope. Omit for every accessible media buy in the account.',
            max_length=100,
            min_length=1,
        ),
    ] = None
    delivery_config_ids: Annotated[
        list[DeliveryConfigId] | None,
        Field(
            description='Optional summary/periods scope. Use to reconcile billing, analytics, and pacing independently. Omit for every active caller-owned configuration.',
            max_length=16,
            min_length=1,
        ),
    ] = None
    feed_purposes: Annotated[
        list[reporting_delivery_offering.ReportingFeedPurpose] | None,
        Field(
            description='Optional summary/periods feed filter. The response echoes exact resolved configuration generations so this never creates an opaque aggregate.',
            min_length=1,
        ),
    ] = None
    period: Annotated[
        Period | None,
        Field(
            description="Half-open summary/periods horizon. Omit for the seller's documented operational default horizon; the response always echoes the evaluated scope."
        ),
    ] = None
    health: Annotated[
        list[reporting_health.ReportingHealth] | None,
        Field(
            description='Periods-view result filter only; it never changes summary health.',
            min_length=1,
        ),
    ] = None
    finality: Annotated[list[reporting_finality.ReportingFinality] | None, Field(min_length=1)] = (
        None
    )
    reporting_revision_id: Annotated[
        str | None,
        Field(
            description='Exact retained revision to resolve in revision view.',
            max_length=255,
            min_length=1,
            pattern='^[A-Za-z0-9_.:-]{1,255}$',
        ),
    ] = None
    pagination: Annotated[
        pagination_request.PaginationRequest | None,
        Field(
            description='Periods or revision-view pagination. Cursors are bound to the authenticated caller, account, filters, and ledger snapshot.'
        ),
    ] = None
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None
