# generated by datamodel-codegen:
#   filename:  media_buy/sync_catalogs_response.json
#   timestamp:  preserved-by-post-generate-fixes

from __future__ import annotations

from typing import Annotated, Literal, TypeAlias

from pydantic import AwareDatetime, ConfigDict, Field, StringConstraints

from ..core.version_envelope import AdcpVersionEnvelope
from ..core import context as context_1
from ..core import error as error_1
from ..core import ext as ext_1
from ..core.protocol_envelope import ProtocolEnvelope
from ..enums import catalog_action as catalog_action_1
from ..enums import catalog_item_status as catalog_item_status_1
from ..enums import task_status as task_status_1


class ItemIssue(AdcpVersionEnvelope):
    model_config = ConfigDict(extra='allow')
    item_id: str
    status: catalog_item_status_1.CatalogItemStatus
    reasons: list[str] | None = None


class Catalog(AdcpVersionEnvelope):
    model_config = ConfigDict(extra='allow')
    catalog_id: str
    action: catalog_action_1.CatalogAction
    platform_id: str | None = None
    item_count: Annotated[int, Field(ge=0)] | None = None
    items_approved: Annotated[int, Field(ge=0)] | None = None
    items_pending: Annotated[int, Field(ge=0)] | None = None
    items_rejected: Annotated[int, Field(ge=0)] | None = None
    item_issues: list[ItemIssue] | None = None
    last_synced_at: AwareDatetime | None = None
    next_fetch_at: AwareDatetime | None = None
    changes: list[str] | None = None
    errors: list[error_1.Error] | None = None
    warnings: list[str] | None = None


class SyncCatalogsResponse1(AdcpVersionEnvelope):
    model_config = ConfigDict(extra='allow')
    dry_run: bool | None = None
    catalogs: list[Catalog]
    sandbox: bool | None = None
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None


class SyncCatalogsResponse2(AdcpVersionEnvelope):
    model_config = ConfigDict(extra='allow')
    errors: Annotated[list[error_1.Error], Field(min_length=1)]
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None


class SyncCatalogsResponse3(AdcpVersionEnvelope, ProtocolEnvelope):
    model_config = ConfigDict(extra='allow', validate_default=True)
    status: Literal[task_status_1.TaskStatus.submitted] = task_status_1.TaskStatus.submitted
    task_id: str
    message: Annotated[str, StringConstraints(max_length=2000)] | None = None
    errors: list[error_1.Error] | None = None
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None


SyncCatalogsResponse: TypeAlias = SyncCatalogsResponse1 | SyncCatalogsResponse2 | SyncCatalogsResponse3


__all__ = [
    'SyncCatalogsResponse',
    'SyncCatalogsResponse1',
    'SyncCatalogsResponse2',
    'SyncCatalogsResponse3',
    'Catalog',
    'ItemIssue',
]
