# generated by datamodel-codegen:
#   filename:  error_details/account_moved.json
#   timestamp: 2026-08-17T23:02:13+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field

from ..core import canonical_account_ref


class AccountMovedDetails(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    current_account: Annotated[
        canonical_account_ref.CanonicalAccountReference,
        Field(
            description='Current canonical reference. Buyer-declared account sellers return the complete current natural key; account-id namespaces may return account_id.'
        ),
    ]
    revision: Annotated[
        int | None,
        Field(
            description='Current account revision when the seller exposes account revisions.', ge=1
        ),
    ] = None
