# generated by datamodel-codegen:
#   filename:  core/assets/vast_asset.json
#   timestamp: 2026-08-28T20:03:29+00:00

from __future__ import annotations

from adcp.types._str_enum import StrEnum
from typing import Any, Annotated, Literal

from adcp.types.base import AdCPBaseModel
from pydantic import AnyUrl, ConfigDict, Field, RootModel

from ...enums import vast_tracking_event
from ...enums import vast_version as vast_version_1
from .. import macro_bearing_url
from .. import provenance as provenance_1
from . import asset_union


class Field1(StrEnum):
    url = 'url'
    markup = 'markup'
    content = 'content'
    ad_request_url = 'ad_request_url'
    clickthrough_url = 'clickthrough_url'


class Location(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field: Annotated[Literal['url'], Field(description='Asset field containing this occurrence.')] = 'url'
    occurrence: Annotated[
        int,
        Field(
            description='Zero-based occurrence of this exact token within the named field.', ge=0
        ),
    ]
    context: asset_union.MacroValueContext


class UnavailableBehavior(StrEnum):
    preserve = 'preserve'
    omit_parameter = 'omit_parameter'
    dialect_sentinel = 'dialect_sentinel'
    reject = 'reject'


class Location26(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field: Annotated[
        Literal['content'], Field(description='Asset field containing this occurrence.')
    ] = 'content'
    occurrence: Annotated[
        int,
        Field(
            description='Zero-based occurrence of this exact token within the named field.', ge=0
        ),
    ]
    context: asset_union.MacroValueContext


class MacroDeclaration(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    declaration_id: Annotated[
        str,
        Field(
            description='Identifier unique within the enclosing asset, used to correlate validation results.',
            min_length=1,
            pattern='^[A-Za-z0-9_-]+$',
        ),
    ]
    token: Annotated[
        str,
        Field(
            description='Exact byte-preserved token expression at this occurrence, including delimiters.',
            min_length=1,
        ),
    ]
    dialect: asset_union.MacroDialect
    dialect_namespace: Annotated[
        AnyUrl | None,
        Field(
            description='Authority-controlled registry or mapping URI. Required for IAB VAST, IAB DAAST, and vendor dialects.'
        ),
    ] = None
    dialect_revision: Annotated[
        str | None,
        Field(
            description='Immutable registry/mapping revision, release, commit, or digest. Required for IAB VAST, IAB DAAST, and vendor dialects.',
            min_length=1,
        ),
    ] = None
    dialect_semantic: Annotated[
        str,
        Field(
            description='Exact semantic identifier in the cited dialect, such as `CACHEBUSTING`, `PLAYERSTATE`, or a documented vendor name. This is not inferred from token spelling.',
            min_length=1,
        ),
    ]
    mapping_status: asset_union.MacroMappingStatus
    universal_semantic: Annotated[
        asset_union.UniversalMacro | None,
        Field(
            description='Verified AdCP universal meaning. Present only when mapping_status is `verified_universal`.'
        ),
    ] = None
    operation: asset_union.MacroProcessingOperation
    performed_by: Annotated[
        asset_union.MacroResolver | None,
        Field(
            description='Actor authorized to perform the declared translation or value resolution. Omitted for preservation.'
        ),
    ] = None
    translation_target: Annotated[
        asset_union.MacroTranslationTarget | None,
        Field(
            description='Required only for `translate_to_native`. The output token contract that replaces this declaration after translation.'
        ),
    ] = None
    location: Location
    encoding: Annotated[
        asset_union.MacroEncoding,
        Field(
            description='Encoding for the concrete value. Translation/preservation uses `none` at depth zero.'
        ),
    ]
    required: Annotated[
        bool,
        Field(
            description='Whether terminal delivery must fail if the declared operation cannot complete.'
        ),
    ]
    unavailable_behavior: Annotated[
        UnavailableBehavior,
        Field(
            description='Action when the responsible actor has no value. Omission is legal only for a complete URL query-value occurrence; dialect sentinels require a cited dialect rule.'
        ),
    ]


class VastAsset3(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    asset_type: Annotated[
        Literal['vast'],
        Field(
            description='Discriminator identifying this as a VAST asset. See /schemas/creative/asset-types for the registry.'
        ),
    ] = 'vast'
    vast_version: Annotated[
        vast_version_1.VastVersion | None,
        Field(
            description='Exact VAST version declared by the supplied URL response or inline document. Required by the 3.2 canonical `video_vast` manifest path; optional only on the deprecated named-format compatibility path. Receivers MUST NOT relabel or synthesize a newer version merely because the destination accepts it.'
        ),
    ] = None
    macro_declarations: Annotated[
        list[MacroDeclaration] | None,
        Field(
            description='One declaration per exact occurrence in a field carried by this asset. A URL-delivered asset can declare only occurrences in its locator `url`; tokens discovered later in a fetched VAST response require document validation evidence or an inline/snapshotted asset and MUST NOT be guessed from the locator. IAB tokens cite a registry namespace and revision rather than copying the live registry into AdCP.',
            min_length=1,
        ),
    ] = None
    vpaid_enabled: Annotated[
        bool | None,
        Field(description='Whether VPAID (Video Player-Ad Interface Definition) is supported'),
    ] = None
    duration_ms: Annotated[
        int | None, Field(description='Expected video duration in milliseconds (if known)', ge=0)
    ] = None
    tracking_events: Annotated[
        list[vast_tracking_event.VastTrackingEvent] | None,
        Field(description='Tracking events supported by this VAST tag'),
    ] = None
    captions_url: Annotated[
        AnyUrl | None, Field(description='URL to captions file (WebVTT, SRT, etc.)')
    ] = None
    audio_description_url: Annotated[
        AnyUrl | None,
        Field(description='URL to audio description track for visually impaired users'),
    ] = None
    provenance: Annotated[
        provenance_1.Provenance | None,
        Field(
            description='Provenance metadata for this asset, overrides manifest-level provenance'
        ),
    ] = None
    delivery_type: Annotated[
        Literal['url'],
        Field(description='Discriminator indicating VAST is delivered via URL endpoint'),
    ] = 'url'
    url: Annotated[
        macro_bearing_url.MacroBearingUrl,
        Field(
            description='URL endpoint returning VAST XML. Macro delimiters remain byte-preserved; declarations distinguish occurrences in this locator URL from occurrences in inline or fetched VAST content.'
        ),
    ]


class MacroDeclaration20(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    declaration_id: Annotated[
        str,
        Field(
            description='Identifier unique within the enclosing asset, used to correlate validation results.',
            min_length=1,
            pattern='^[A-Za-z0-9_-]+$',
        ),
    ]
    token: Annotated[
        str,
        Field(
            description='Exact byte-preserved token expression at this occurrence, including delimiters.',
            min_length=1,
        ),
    ]
    dialect: asset_union.MacroDialect
    dialect_namespace: Annotated[
        AnyUrl | None,
        Field(
            description='Authority-controlled registry or mapping URI. Required for IAB VAST, IAB DAAST, and vendor dialects.'
        ),
    ] = None
    dialect_revision: Annotated[
        str | None,
        Field(
            description='Immutable registry/mapping revision, release, commit, or digest. Required for IAB VAST, IAB DAAST, and vendor dialects.',
            min_length=1,
        ),
    ] = None
    dialect_semantic: Annotated[
        str,
        Field(
            description='Exact semantic identifier in the cited dialect, such as `CACHEBUSTING`, `PLAYERSTATE`, or a documented vendor name. This is not inferred from token spelling.',
            min_length=1,
        ),
    ]
    mapping_status: asset_union.MacroMappingStatus
    universal_semantic: Annotated[
        asset_union.UniversalMacro | None,
        Field(
            description='Verified AdCP universal meaning. Present only when mapping_status is `verified_universal`.'
        ),
    ] = None
    operation: asset_union.MacroProcessingOperation
    performed_by: Annotated[
        asset_union.MacroResolver | None,
        Field(
            description='Actor authorized to perform the declared translation or value resolution. Omitted for preservation.'
        ),
    ] = None
    translation_target: Annotated[
        asset_union.MacroTranslationTarget | None,
        Field(
            description='Required only for `translate_to_native`. The output token contract that replaces this declaration after translation.'
        ),
    ] = None
    location: Location26
    encoding: Annotated[
        asset_union.MacroEncoding,
        Field(
            description='Encoding for the concrete value. Translation/preservation uses `none` at depth zero.'
        ),
    ]
    required: Annotated[
        bool,
        Field(
            description='Whether terminal delivery must fail if the declared operation cannot complete.'
        ),
    ]
    unavailable_behavior: Annotated[
        UnavailableBehavior,
        Field(
            description='Action when the responsible actor has no value. Omission is legal only for a complete URL query-value occurrence; dialect sentinels require a cited dialect rule.'
        ),
    ]


class VastAsset4(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    asset_type: Annotated[
        Literal['vast'],
        Field(
            description='Discriminator identifying this as a VAST asset. See /schemas/creative/asset-types for the registry.'
        ),
    ] = 'vast'
    vast_version: Annotated[
        vast_version_1.VastVersion | None,
        Field(
            description='Exact VAST version declared by the supplied URL response or inline document. Required by the 3.2 canonical `video_vast` manifest path; optional only on the deprecated named-format compatibility path. Receivers MUST NOT relabel or synthesize a newer version merely because the destination accepts it.'
        ),
    ] = None
    macro_declarations: Annotated[
        list[MacroDeclaration20] | None,
        Field(
            description='One declaration per exact occurrence in a field carried by this asset. A URL-delivered asset can declare only occurrences in its locator `url`; tokens discovered later in a fetched VAST response require document validation evidence or an inline/snapshotted asset and MUST NOT be guessed from the locator. IAB tokens cite a registry namespace and revision rather than copying the live registry into AdCP.',
            min_length=1,
        ),
    ] = None
    vpaid_enabled: Annotated[
        bool | None,
        Field(description='Whether VPAID (Video Player-Ad Interface Definition) is supported'),
    ] = None
    duration_ms: Annotated[
        int | None, Field(description='Expected video duration in milliseconds (if known)', ge=0)
    ] = None
    tracking_events: Annotated[
        list[vast_tracking_event.VastTrackingEvent] | None,
        Field(description='Tracking events supported by this VAST tag'),
    ] = None
    captions_url: Annotated[
        AnyUrl | None, Field(description='URL to captions file (WebVTT, SRT, etc.)')
    ] = None
    audio_description_url: Annotated[
        AnyUrl | None,
        Field(description='URL to audio description track for visually impaired users'),
    ] = None
    provenance: Annotated[
        provenance_1.Provenance | None,
        Field(
            description='Provenance metadata for this asset, overrides manifest-level provenance'
        ),
    ] = None
    delivery_type: Annotated[
        Literal['inline'],
        Field(description='Discriminator indicating VAST is delivered as inline XML content'),
    ] = 'inline'
    content: Annotated[str, Field(description='Inline VAST XML content')]


class VastAsset(RootModel[VastAsset3 | VastAsset4]):
    root: Annotated[
        VastAsset3 | VastAsset4,
        Field(
            description='VAST (Video Ad Serving Template) tag for third-party video ad serving. Unlike the hosted `video` asset, a VAST tag carries no `width`/`height`: a VAST response can return multiple renditions of differing dimensions, and the player selects one per device at serve time, so there is no single width/height for the ad. Dimensional, duration, and codec *constraints* for a placement live on the format/requirements layer, not on this asset.',
            discriminator='delivery_type',
            title='VAST Asset',
        ),
    ]
    def __getattr__(self, name: str) -> Any:
        """Proxy attribute access to the wrapped type."""
        if name.startswith('_'):
            raise AttributeError(name)
        return getattr(self.root, name)
