"""Types the AdCP ``adagents`` schemas declare.

Importing from the domain says which variant you mean, where the flat
``adcp.types`` namespace can only bind one class per name:

    from adcp.types.domains.adagents import <Type>

This domain has one schema, so every type it declares is here.

Auto-generated from the generated_poc module tree. DO NOT EDIT MANUALLY.
Generation date: 2026-10-03 13:33:59 UTC
"""

# ruff: noqa: E501, I001
from __future__ import annotations

from adcp.types.generated_poc.adagents import (
    AdcpAgentsAuthorization,
    AdcpAgentsAuthorization1,
    AdcpAgentsAuthorization2,
    AdcpAgentsAuthorization21,
    AdcpAgentsAuthorization210,
    AdcpAgentsAuthorization211,
    AdcpAgentsAuthorization212,
    AdcpAgentsAuthorization213,
    AdcpAgentsAuthorization22,
    AdcpAgentsAuthorization23,
    AdcpAgentsAuthorization24,
    AdcpAgentsAuthorization25,
    AdcpAgentsAuthorization26,
    AdcpAgentsAuthorization27,
    AdcpAgentsAuthorization28,
    AdcpAgentsAuthorization29,
    AuthorizedAgents,
    AuthorizedAgents1,
    AuthorizedAgents10,
    AuthorizedAgents11,
    AuthorizedAgents12,
    AuthorizedAgents13,
    AuthorizedAgents14,
    AuthorizedAgents15,
    AuthorizedAgents16,
    AuthorizedAgents17,
    AuthorizedAgents18,
    AuthorizedAgents19,
    AuthorizedAgents2,
    AuthorizedAgents20,
    AuthorizedAgents21,
    AuthorizedAgents22,
    AuthorizedAgents23,
    AuthorizedAgents24,
    AuthorizedAgents25,
    AuthorizedAgents26,
    AuthorizedAgents27,
    AuthorizedAgents28,
    AuthorizedAgents29,
    AuthorizedAgents3,
    AuthorizedAgents30,
    AuthorizedAgents31,
    AuthorizedAgents32,
    AuthorizedAgents33,
    AuthorizedAgents34,
    AuthorizedAgents35,
    AuthorizedAgents36,
    AuthorizedAgents37,
    AuthorizedAgents38,
    AuthorizedAgents39,
    AuthorizedAgents4,
    AuthorizedAgents40,
    AuthorizedAgents41,
    AuthorizedAgents42,
    AuthorizedAgents43,
    AuthorizedAgents44,
    AuthorizedAgents45,
    AuthorizedAgents46,
    AuthorizedAgents47,
    AuthorizedAgents48,
    AuthorizedAgents5,
    AuthorizedAgents6,
    AuthorizedAgents7,
    AuthorizedAgents8,
    AuthorizedAgents9,
    Contact,
    Country,
    DelegationType,
    PlacementTags,
    PropertyFeature,
    Reason,
    RevokedPublisherDomain,
    RevokedPublisherDomain1,
    RevokedPublisherDomain2,
    RevokedPublisherDomain3,
    RevokedPublisherDomain4,
    RevokedPublisherDomain5,
    RevokedPublisherDomain6,
    SignalId,
    SignalTag,
    SignalTags,
    Tags,
)

# Explicit exports
__all__ = [
    "AdcpAgentsAuthorization",
    "AdcpAgentsAuthorization1",
    "AdcpAgentsAuthorization2",
    "AdcpAgentsAuthorization21",
    "AdcpAgentsAuthorization210",
    "AdcpAgentsAuthorization211",
    "AdcpAgentsAuthorization212",
    "AdcpAgentsAuthorization213",
    "AdcpAgentsAuthorization22",
    "AdcpAgentsAuthorization23",
    "AdcpAgentsAuthorization24",
    "AdcpAgentsAuthorization25",
    "AdcpAgentsAuthorization26",
    "AdcpAgentsAuthorization27",
    "AdcpAgentsAuthorization28",
    "AdcpAgentsAuthorization29",
    "AuthorizedAgents",
    "AuthorizedAgents1",
    "AuthorizedAgents10",
    "AuthorizedAgents11",
    "AuthorizedAgents12",
    "AuthorizedAgents13",
    "AuthorizedAgents14",
    "AuthorizedAgents15",
    "AuthorizedAgents16",
    "AuthorizedAgents17",
    "AuthorizedAgents18",
    "AuthorizedAgents19",
    "AuthorizedAgents2",
    "AuthorizedAgents20",
    "AuthorizedAgents21",
    "AuthorizedAgents22",
    "AuthorizedAgents23",
    "AuthorizedAgents24",
    "AuthorizedAgents25",
    "AuthorizedAgents26",
    "AuthorizedAgents27",
    "AuthorizedAgents28",
    "AuthorizedAgents29",
    "AuthorizedAgents3",
    "AuthorizedAgents30",
    "AuthorizedAgents31",
    "AuthorizedAgents32",
    "AuthorizedAgents33",
    "AuthorizedAgents34",
    "AuthorizedAgents35",
    "AuthorizedAgents36",
    "AuthorizedAgents37",
    "AuthorizedAgents38",
    "AuthorizedAgents39",
    "AuthorizedAgents4",
    "AuthorizedAgents40",
    "AuthorizedAgents41",
    "AuthorizedAgents42",
    "AuthorizedAgents43",
    "AuthorizedAgents44",
    "AuthorizedAgents45",
    "AuthorizedAgents46",
    "AuthorizedAgents47",
    "AuthorizedAgents48",
    "AuthorizedAgents5",
    "AuthorizedAgents6",
    "AuthorizedAgents7",
    "AuthorizedAgents8",
    "AuthorizedAgents9",
    "Contact",
    "Country",
    "DelegationType",
    "PlacementTags",
    "PropertyFeature",
    "Reason",
    "RevokedPublisherDomain",
    "RevokedPublisherDomain1",
    "RevokedPublisherDomain2",
    "RevokedPublisherDomain3",
    "RevokedPublisherDomain4",
    "RevokedPublisherDomain5",
    "RevokedPublisherDomain6",
    "SignalId",
    "SignalTag",
    "SignalTags",
    "Tags",
]
