# generated by datamodel-codegen:
#   filename:  preview-render.json
#   timestamp: 2025-11-15T17:41:01+00:00

from __future__ import annotations

from typing import Literal

from adcp.types.base import AdCPBaseModel
from pydantic import AnyUrl, ConfigDict, Field, RootModel


class Dimensions(AdCPBaseModel):
    width: float = Field(..., ge=0.0)
    height: float = Field(..., ge=0.0)


class Embedding(AdCPBaseModel):
    recommended_sandbox: str | None = Field(
        None,
        description="Recommended iframe sandbox attribute value (e.g., 'allow-scripts allow-same-origin')",
    )
    requires_https: bool | None = Field(
        None, description='Whether this output requires HTTPS for secure embedding'
    )
    supports_fullscreen: bool | None = Field(
        None, description='Whether this output supports fullscreen mode'
    )
    csp_policy: str | None = Field(
        None, description='Content Security Policy requirements for embedding'
    )


class PreviewRender1(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    render_id: str = Field(
        ..., description='Unique identifier for this rendered piece within the variant'
    )
    output_format: Literal['url'] = Field(
        ..., description='Discriminator indicating preview_url is provided'
    )
    preview_url: AnyUrl = Field(
        ...,
        description='URL to an HTML page that renders this piece. Can be embedded in an iframe.',
    )
    role: str = Field(
        ...,
        description="Semantic role of this rendered piece. Use 'primary' for main content, 'companion' for associated banners, descriptive strings for device variants or custom roles.",
    )
    dimensions: Dimensions | None = Field(None, description='Dimensions for this rendered piece')
    embedding: Embedding | None = Field(
        None, description='Optional security and embedding metadata for safe iframe integration'
    )


class PreviewRender2(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    render_id: str = Field(
        ..., description='Unique identifier for this rendered piece within the variant'
    )
    output_format: Literal['html'] = Field(
        ..., description='Discriminator indicating preview_html is provided'
    )
    preview_html: str = Field(
        ...,
        description='Raw HTML for this rendered piece. Can be embedded directly in the page without iframe. Security warning: Only use with trusted creative agents as this bypasses iframe sandboxing.',
    )
    role: str = Field(
        ...,
        description="Semantic role of this rendered piece. Use 'primary' for main content, 'companion' for associated banners, descriptive strings for device variants or custom roles.",
    )
    dimensions: Dimensions | None = Field(None, description='Dimensions for this rendered piece')
    embedding: Embedding | None = Field(
        None, description='Optional security and embedding metadata'
    )


class PreviewRender3(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    render_id: str = Field(
        ..., description='Unique identifier for this rendered piece within the variant'
    )
    output_format: Literal['both'] = Field(
        ..., description='Discriminator indicating both preview_url and preview_html are provided'
    )
    preview_url: AnyUrl = Field(
        ...,
        description='URL to an HTML page that renders this piece. Can be embedded in an iframe.',
    )
    preview_html: str = Field(
        ...,
        description='Raw HTML for this rendered piece. Can be embedded directly in the page without iframe. Security warning: Only use with trusted creative agents as this bypasses iframe sandboxing.',
    )
    role: str = Field(
        ...,
        description="Semantic role of this rendered piece. Use 'primary' for main content, 'companion' for associated banners, descriptive strings for device variants or custom roles.",
    )
    dimensions: Dimensions | None = Field(None, description='Dimensions for this rendered piece')
    embedding: Embedding | None = Field(
        None, description='Optional security and embedding metadata for safe iframe integration'
    )


class PreviewRender(RootModel[PreviewRender1 | PreviewRender2 | PreviewRender3]):
    root: PreviewRender1 | PreviewRender2 | PreviewRender3 = Field(
        ...,
        description='A single rendered piece of a creative preview with discriminated output format',
        title='Preview Render',
    )

# Aliases for backward compatibility
UrlPreviewRender = PreviewRender1
HtmlPreviewRender = PreviewRender2
BothPreviewRender = PreviewRender3
