# generated by datamodel-codegen:
#   filename:  preview-output-format.json
#   timestamp: 2025-11-21T12:47:29+00:00

from __future__ import annotations

from enum import Enum


class PreviewOutputFormat(Enum):
    url = 'url'
    html = 'html'
