# generated by datamodel-codegen:
#   filename:  property.json
#   timestamp: 2025-11-15T17:41:08+00:00

from __future__ import annotations

from enum import Enum

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field, RootModel


class PropertyType(Enum):
    website = 'website'
    mobile_app = 'mobile_app'
    ctv_app = 'ctv_app'
    dooh = 'dooh'
    podcast = 'podcast'
    radio = 'radio'
    streaming_audio = 'streaming_audio'


class Tag(RootModel[str]):
    root: str = Field(
        ...,
        description="Lowercase tag with underscores (e.g., 'conde_nast_network', 'premium_content')",
        pattern='^[a-z0-9_]+$',
    )


class IdentifierTypes(Enum):
    domain = 'domain'
    subdomain = 'subdomain'
    network_id = 'network_id'
    ios_bundle = 'ios_bundle'
    android_package = 'android_package'
    apple_app_store_id = 'apple_app_store_id'
    google_play_id = 'google_play_id'
    roku_store_id = 'roku_store_id'
    fire_tv_asin = 'fire_tv_asin'
    samsung_app_id = 'samsung_app_id'
    apple_tv_bundle = 'apple_tv_bundle'
    bundle_id = 'bundle_id'
    venue_id = 'venue_id'
    screen_id = 'screen_id'
    openooh_venue_type = 'openooh_venue_type'
    rss_url = 'rss_url'
    apple_podcast_id = 'apple_podcast_id'
    spotify_show_id = 'spotify_show_id'
    podcast_guid = 'podcast_guid'


class Identifier(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: IdentifierTypes = Field(..., description='Type of identifier for this property')
    value: str = Field(
        ...,
        description="The identifier value. For domain type: 'example.com' matches base domain plus www and m subdomains; 'edition.example.com' matches that specific subdomain; '*.example.com' matches ALL subdomains but NOT base domain",
    )


class Property(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    property_id: str | None = Field(
        None,
        description="Unique identifier for this property (optional). Enables referencing properties by ID instead of repeating full objects. Recommended format: lowercase with underscores (e.g., 'cnn_ctv_app', 'instagram_mobile')",
        pattern='^[a-z0-9_]+$',
    )
    property_type: PropertyType = Field(..., description='Type of advertising property')
    name: str = Field(..., description='Human-readable property name')
    identifiers: list[Identifier] = Field(
        ..., description='Array of identifiers for this property', min_length=1
    )
    tags: list[Tag] | None = Field(
        None,
        description='Tags for categorization and grouping (e.g., network membership, content categories)',
    )
    publisher_domain: str | None = Field(
        None,
        description='Domain where adagents.json should be checked for authorization validation. Required for list_authorized_properties response. Optional in adagents.json (file location implies domain).',
    )
