# generated by datamodel-codegen:
#   filename:  reporting-frequency.json
#   timestamp: 2025-11-21T12:47:29+00:00

from __future__ import annotations

from enum import Enum


class ReportingFrequency(Enum):
    hourly = 'hourly'
    daily = 'daily'
    monthly = 'monthly'
