# generated by datamodel-codegen:
#   filename:  bundled/creative/sync_creatives_response.json
#   timestamp: 2026-04-29T01:11:23+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal

from adcp.types.base import AdCPBaseModel
from pydantic import (
    AnyUrl,
    AwareDatetime,
    ConfigDict,
    EmailStr,
    Field,
    RootModel,
    StringConstraints,
)


class Status(Enum):
    active = "active"
    pending_approval = "pending_approval"
    rejected = "rejected"
    payment_required = "payment_required"
    suspended = "suspended"
    closed = "closed"


class DataSubjectContestation(AdCPBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: AnyUrl
    email: EmailStr | None = None
    languages: list[str] | None = None


class DataSubjectContestation89(AdCPBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: AnyUrl | None = None
    email: EmailStr
    languages: list[str] | None = None


class Brand(AdCPBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    domain: Annotated[
        str,
        Field(
            description="Domain where /.well-known/brand.json is hosted, or the brand's operating domain",
            pattern="^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$",
        ),
    ]
    brand_id: Annotated[
        str | None,
        Field(
            description="Brand identifier within the house portfolio. Optional for single-brand domains.",
            examples=["tide", "cheerios", "air_jordan", "nike", "pampers"],
            pattern="^[a-z0-9_]+$",
            title="Brand ID",
        ),
    ] = None
    industries: Annotated[
        list[str] | None,
        Field(
            description="Inline override for the brand's industries. Useful when the caller cannot modify the brand's canonical brand.json but needs to declare industries for governance (e.g., Annex III vertical detection). brand.json remains the canonical source; when omitted here, governance agents SHOULD resolve from brand.json."
        ),
    ] = None
    data_subject_contestation: Annotated[
        DataSubjectContestation | DataSubjectContestation89 | None,
        Field(
            description="Inline override for the brand's contestation contact point. Useful when the operator does not control brand.json but needs to discharge Art 22(3) for this plan. brand.json is canonical; when omitted, governance agents resolve brand → house → missing."
        ),
    ] = None


class Billing(Enum):
    operator = "operator"
    agent = "agent"
    advertiser = "advertiser"


class Address(AdCPBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    street: Annotated[
        str, Field(description="Street address including building number", max_length=200)
    ]
    city: Annotated[str, Field(max_length=100)]
    postal_code: Annotated[str, Field(max_length=20)]
    region: Annotated[
        str | None, Field(description="State, province, or region", max_length=100)
    ] = None
    country: Annotated[
        str, Field(description="ISO 3166-1 alpha-2 country code", pattern="^[A-Z]{2}$")
    ]


class Role(Enum):
    billing = "billing"
    legal = "legal"
    creative = "creative"
    general = "general"


class Contact(AdCPBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: Annotated[
        Role, Field(description="Contact's functional role in the business relationship")
    ]
    name: Annotated[str | None, Field(description="Full name of the contact", max_length=200)] = (
        None
    )
    email: Annotated[EmailStr | None, Field(max_length=254)] = None
    phone: Annotated[str | None, Field(max_length=30)] = None


class Bank(AdCPBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    account_holder: Annotated[str, Field(description="Name on the bank account", max_length=200)]
    iban: Annotated[
        str | None,
        Field(
            description="International Bank Account Number (SEPA markets)",
            pattern="^[A-Z]{2}[0-9]{2}[A-Z0-9]{4,30}$",
        ),
    ] = None
    bic: Annotated[
        str | None,
        Field(
            description="Bank Identifier Code / SWIFT code (SEPA markets)",
            pattern="^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$",
        ),
    ] = None
    routing_number: Annotated[
        str | None,
        Field(
            description="Bank routing number for non-SEPA markets (e.g., US ABA routing number, Canadian transit/institution number)",
            max_length=30,
        ),
    ] = None
    account_number: Annotated[
        str | None, Field(description="Bank account number for non-SEPA markets", max_length=30)
    ] = None


class BillingEntity(AdCPBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    legal_name: Annotated[
        str, Field(description="Registered legal name of the business entity", max_length=200)
    ]
    vat_id: Annotated[
        str | None,
        Field(
            description="VAT identification number (e.g., DE123456789 for Germany, FR12345678901 for France). Required for B2B invoicing in the EU. Must be normalized: no spaces, dots, or dashes.",
            pattern="^[A-Z]{2}[A-Z0-9]{2,13}$",
        ),
    ] = None
    tax_id: Annotated[
        str | None,
        Field(
            description="Tax identification number for jurisdictions that do not use VAT (e.g., US EIN)",
            max_length=30,
        ),
    ] = None
    registration_number: Annotated[
        str | None,
        Field(
            description="Company registration number (e.g., HRB 12345 for German Handelsregister)",
            max_length=50,
        ),
    ] = None
    address: Annotated[
        Address | None, Field(description="Postal address for invoicing and legal correspondence")
    ] = None
    contacts: Annotated[
        list[Contact] | None,
        Field(
            description="Contacts for billing, legal, and operational matters. Contains personal data subject to GDPR and equivalent regulations. Implementations MUST use this data only for invoicing and account management.",
            max_length=10,
        ),
    ] = None
    bank: Annotated[
        Bank | None,
        Field(
            description="Bank account details for payment processing. Write-only: included in requests to provide payment coordinates, but MUST NOT be echoed in responses. Sellers store these details and confirm receipt without returning them."
        ),
    ] = None
    ext: Annotated[
        dict[str, Any] | None,
        Field(
            description="Extension object for platform-specific, vendor-namespaced parameters. Extensions are always optional and must be namespaced under a vendor/platform key (e.g., ext.gam, ext.roku). Used for custom capabilities, partner-specific configuration, and features being proposed for standardization.",
            title="Extension Object",
        ),
    ] = None


class PaymentTerms(Enum):
    net_15 = "net_15"
    net_30 = "net_30"
    net_45 = "net_45"
    net_60 = "net_60"
    net_90 = "net_90"
    prepay = "prepay"


class CreditLimit(AdCPBaseModel):
    amount: Annotated[float, Field(ge=0.0)]
    currency: Annotated[str, Field(pattern="^[A-Z]{3}$")]


class Setup(AdCPBaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    url: Annotated[
        AnyUrl | None,
        Field(
            description="URL where the human can complete the required action (credit application, legal agreement, add funds)."
        ),
    ] = None
    message: Annotated[str, Field(description="Human-readable description of what's needed.")]
    expires_at: Annotated[
        AwareDatetime | None, Field(description="When this setup link expires.")
    ] = None


class AccountScope(Enum):
    operator = "operator"
    brand = "brand"
    operator_brand = "operator_brand"
    agent = "agent"


class Category(RootModel[str]):
    root: Annotated[str, Field(max_length=64, pattern="^[a-z][a-z0-9_]*$")]


class GovernanceAgent(AdCPBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: Annotated[AnyUrl, Field(description="Governance agent endpoint URL. Must use HTTPS.")]
    categories: Annotated[
        list[Category] | None,
        Field(
            description="Governance categories this agent handles (e.g., ['budget_authority', 'strategic_alignment']). When omitted, the agent handles all categories.",
            max_length=20,
        ),
    ] = None


class Protocol(Enum):
    s3 = "s3"
    gcs = "gcs"
    azure_blob = "azure_blob"


class Format(Enum):
    jsonl = "jsonl"
    csv = "csv"
    parquet = "parquet"
    avro = "avro"
    orc = "orc"


class Compression(Enum):
    gzip = "gzip"
    none = "none"


class ReportingBucket(AdCPBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    protocol: Annotated[
        Protocol, Field(description="Cloud storage protocol", title="Cloud Storage Protocol")
    ]
    bucket: Annotated[
        str,
        Field(
            description="Bucket or container name",
            max_length=63,
            min_length=3,
            pattern="^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$",
        ),
    ]
    prefix: Annotated[
        str | None,
        Field(
            description="Path prefix within the bucket. Seller appends date-based partitioning beneath this prefix.",
            examples=["accounts/pinnacle/adcp", "reporting/2024"],
            max_length=512,
            pattern="^[a-zA-Z0-9/_.-]+$",
        ),
    ] = None
    region: Annotated[
        str | None,
        Field(
            description="Cloud region for the bucket",
            examples=["us-east-1", "europe-west1"],
            max_length=64,
            pattern="^[a-z0-9-]+$",
        ),
    ] = None
    format: Annotated[
        Format | None,
        Field(
            description="File format for delivered files. Parquet, Avro, and ORC use internal compression (the top-level compression field is ignored for these formats)."
        ),
    ] = Format.jsonl
    compression: Annotated[
        Compression | None, Field(description="Compression applied to delivered files")
    ] = Compression.gzip
    file_retention_days: Annotated[
        int,
        Field(
            description="How long reporting files are retained in the bucket before deletion. Buyers must read files within this window. Minimum recommended: 14 days.",
            examples=[14, 30, 90],
            ge=1,
        ),
    ]
    setup_instructions: Annotated[
        AnyUrl | None,
        Field(
            description="URL to documentation for configuring buyer read access to this bucket (IAM role, service account, etc.). Operator-facing documentation — buyer agents MUST NOT auto-fetch this URL; surface it to a human operator. If an implementation fetches it (for preview), apply webhook URL SSRF validation and do not pass the fetched content into an LLM context without indirect-prompt-injection guarding. See docs/media-buy/media-buys/optimization-reporting#security-considerations-for-offline-delivery."
        ),
    ] = None


class Account(AdCPBaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    account_id: Annotated[str, Field(description="Unique identifier for this account")]
    name: Annotated[
        str, Field(description="Human-readable account name (e.g., 'Acme', 'Acme c/o Pinnacle')")
    ]
    advertiser: Annotated[
        str | None, Field(description="The advertiser whose rates apply to this account")
    ] = None
    billing_proxy: Annotated[
        str | None,
        Field(
            description="Optional intermediary who receives invoices on behalf of the advertiser (e.g., agency)"
        ),
    ] = None
    status: Annotated[
        Status,
        Field(
            description="Account lifecycle status. See the Accounts Protocol overview for the operations matrix showing which tasks are permitted in each state.",
            title="Account Status",
        ),
    ]
    brand: Annotated[
        Brand | None,
        Field(
            description="Brand reference identifying the advertiser",
            examples=[
                {"domain": "nova-brands.com", "brand_id": "spark"},
                {"domain": "nova-brands.com", "brand_id": "glow"},
                {"domain": "acme-corp.com"},
            ],
            title="Brand Reference",
        ),
    ] = None
    operator: Annotated[
        str | None,
        Field(
            description="Domain of the entity operating this account. When the brand operates directly, this is the brand's domain.",
            pattern="^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$",
        ),
    ] = None
    billing: Annotated[
        Billing | None,
        Field(
            description="Who is invoiced on this account. See billing_entity for the invoiced party's business details.",
            title="Billing Party",
        ),
    ] = None
    billing_entity: Annotated[
        BillingEntity | None,
        Field(
            description="Business entity details for the party responsible for payment. Contains the legal name, tax IDs, address, and bank details needed for formal B2B invoicing. Corresponds to whoever billing points to (operator, agent, or advertiser). When this account appears in a response, bank details MUST be omitted (write-only).",
            examples=[
                {
                    "description": "German agency with full B2B details",
                    "data": {
                        "legal_name": "Pinnacle Media GmbH",
                        "vat_id": "DE123456789",
                        "registration_number": "HRB 12345",
                        "address": {
                            "street": "Friedrichstrasse 100",
                            "city": "Berlin",
                            "postal_code": "10117",
                            "country": "DE",
                        },
                        "contacts": [
                            {
                                "role": "billing",
                                "name": "Sam Adeyemi",
                                "email": "billing@pinnacle-media.com",
                                "phone": "+49 30 12345678",
                            }
                        ],
                        "bank": {
                            "account_holder": "Pinnacle Media GmbH",
                            "iban": "DE89370400440532013000",
                            "bic": "COBADEFFXXX",
                        },
                    },
                },
                {
                    "description": "US advertiser with EIN and domestic bank details",
                    "data": {
                        "legal_name": "Acme Corporation",
                        "tax_id": "12-3456789",
                        "address": {
                            "street": "123 Main St",
                            "city": "New York",
                            "postal_code": "10001",
                            "region": "NY",
                            "country": "US",
                        },
                        "contacts": [
                            {
                                "role": "billing",
                                "name": "AP Department",
                                "email": "ap@acme-corp.com",
                            }
                        ],
                        "bank": {
                            "account_holder": "Acme Corporation",
                            "routing_number": "021000021",
                            "account_number": "123456789",
                        },
                    },
                },
            ],
            title="Business Entity",
        ),
    ] = None
    rate_card: Annotated[
        str | None, Field(description="Identifier for the rate card applied to this account")
    ] = None
    payment_terms: Annotated[
        PaymentTerms | None,
        Field(
            description="Payment terms agreed for this account. Binding for all invoices when the account is active.",
            title="Payment Terms",
        ),
    ] = None
    credit_limit: Annotated[
        CreditLimit | None, Field(description="Maximum outstanding balance allowed")
    ] = None
    setup: Annotated[
        Setup | None,
        Field(
            description="Present when status is 'pending_approval'. Contains next steps for completing account activation."
        ),
    ] = None
    account_scope: Annotated[
        AccountScope | None,
        Field(
            description="How the seller scoped a billing account relative to the operator and brand dimensions.",
            title="Account Scope",
        ),
    ] = None
    governance_agents: Annotated[
        list[GovernanceAgent] | None,
        Field(
            description="Governance agent endpoints registered on this account. Authentication credentials are write-only and not included in responses — use sync_governance to set or update credentials.",
            max_length=10,
        ),
    ] = None
    reporting_bucket: Annotated[
        ReportingBucket | None,
        Field(
            description="Cloud storage bucket where the seller delivers offline reporting files for this account. Seller provisions a dedicated bucket or a per-account prefix within a shared bucket, and grants the buyer read access out-of-band. Access MUST be scoped at the IAM layer so each account can only read its own prefix — bucket-wide grants are non-compliant even with per-account prefixes. Seller MUST revoke access when the account's status transitions to inactive, suspended, or closed. See security considerations for offline delivery in docs/media-buy/media-buys/optimization-reporting. Only present when the seller supports offline delivery (reporting_delivery_methods includes 'offline' in capabilities)."
        ),
    ] = None
    sandbox: Annotated[
        bool | None,
        Field(
            description="When true, this is a sandbox account — no real platform calls, no real spend. For explicit accounts (require_operator_auth: true), sandbox accounts are pre-existing test accounts on the platform discovered via list_accounts. For implicit accounts, sandbox is part of the natural key: the same brand/operator pair can have both a production and sandbox account."
        ),
    ] = None
    ext: Annotated[
        dict[str, Any] | None,
        Field(
            description="Extension object for platform-specific, vendor-namespaced parameters. Extensions are always optional and must be namespaced under a vendor/platform key (e.g., ext.gam, ext.roku). Used for custom capabilities, partner-specific configuration, and features being proposed for standardization.",
            title="Extension Object",
        ),
    ] = None


class Action(Enum):
    created = "created"
    updated = "updated"
    unchanged = "unchanged"
    failed = "failed"
    deleted = "deleted"


class Status34(Enum):
    processing = "processing"
    pending_review = "pending_review"
    approved = "approved"
    rejected = "rejected"
    archived = "archived"


class Recovery(Enum):
    transient = "transient"
    correctable = "correctable"
    terminal = "terminal"


class Error(AdCPBaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    code: Annotated[
        str,
        Field(
            description="Error code for programmatic handling. Standard codes are defined in error-code.json and enable autonomous agent recovery. Sellers MAY use codes not in the standard vocabulary for platform-specific errors; agents MUST handle unknown codes gracefully by falling back to the recovery classification.",
            max_length=64,
            min_length=1,
        ),
    ]
    message: Annotated[str, Field(description="Human-readable error message")]
    field: Annotated[
        str | None,
        Field(description="Field path associated with the error (e.g., 'packages[0].targeting')"),
    ] = None
    suggestion: Annotated[str | None, Field(description="Suggested fix for the error")] = None
    retry_after: Annotated[
        float | None,
        Field(
            description="Seconds to wait before retrying the operation. Sellers MUST return values between 1 and 3600. Clients MUST clamp values outside this range.",
            ge=1.0,
            le=3600.0,
        ),
    ] = None
    details: Annotated[
        dict[str, Any] | None, Field(description="Additional task-specific error details")
    ] = None
    recovery: Annotated[
        Recovery | None,
        Field(
            description="Agent recovery classification. transient: retry after delay (rate limit, service unavailable, timeout). correctable: fix the request and resend (invalid field, budget too low, creative rejected). terminal: requires human action (account suspended, payment required, account not found)."
        ),
    ] = None


class Creative(AdCPBaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    creative_id: Annotated[str, Field(description="Creative ID from the request")]
    account: Annotated[
        Account | None,
        Field(
            description="Account that owns this creative",
            examples=[
                {
                    "description": "Direct advertiser account",
                    "data": {
                        "account_id": "acc_acme_direct",
                        "name": "Acme",
                        "advertiser": "Acme Corp",
                        "brand": {"domain": "acme-corp.com"},
                        "operator": "acme-corp.com",
                        "status": "active",
                        "billing": "operator",
                        "account_scope": "brand",
                        "rate_card": "acme_vip_2024",
                        "payment_terms": "net_30",
                    },
                },
                {
                    "description": "Advertiser account with agency billing proxy",
                    "data": {
                        "account_id": "acc_acme_pinnacle",
                        "name": "Acme c/o Pinnacle",
                        "advertiser": "Acme Corp",
                        "billing_proxy": "Pinnacle Media",
                        "brand": {"domain": "acme-corp.com"},
                        "operator": "pinnacle-media.com",
                        "status": "active",
                        "billing": "operator",
                        "account_scope": "operator_brand",
                        "rate_card": "acme_vip_2024",
                        "payment_terms": "net_60",
                    },
                },
                {
                    "description": "Agency as direct buyer",
                    "data": {
                        "account_id": "acc_pinnacle",
                        "name": "Pinnacle",
                        "advertiser": "Pinnacle Media",
                        "brand": {"domain": "pinnacle-media.com"},
                        "operator": "pinnacle-media.com",
                        "status": "active",
                        "billing": "operator",
                        "account_scope": "operator",
                        "rate_card": "agency_standard",
                        "payment_terms": "net_45",
                    },
                },
                {
                    "description": "Account with brand identity and operator (via sync_accounts)",
                    "data": {
                        "account_id": "acc_spark_001",
                        "name": "Spark (via Pinnacle)",
                        "advertiser": "Nova Brands",
                        "status": "active",
                        "brand": {"domain": "nova-brands.com", "brand_id": "spark"},
                        "operator": "pinnacle-media.com",
                        "billing": "agent",
                        "account_scope": "operator_brand",
                        "payment_terms": "net_30",
                    },
                },
                {
                    "description": "Pending account awaiting seller approval",
                    "data": {
                        "account_id": "acc_glow_pending",
                        "name": "Glow",
                        "advertiser": "Nova Brands",
                        "status": "pending_approval",
                        "brand": {"domain": "nova-brands.com", "brand_id": "glow"},
                        "operator": "pinnacle-media.com",
                        "billing": "operator",
                        "account_scope": "brand",
                    },
                },
                {
                    "description": "Agency operates but advertiser is billed directly with structured billing entity",
                    "data": {
                        "account_id": "acc_acme_direct_bill",
                        "name": "Acme (billed direct)",
                        "advertiser": "Acme Corp",
                        "brand": {"domain": "acme-corp.com"},
                        "operator": "pinnacle-media.com",
                        "status": "active",
                        "billing": "advertiser",
                        "billing_entity": {
                            "legal_name": "Acme Corporation GmbH",
                            "vat_id": "DE987654321",
                            "address": {
                                "street": "Hauptstrasse 42",
                                "city": "Munich",
                                "postal_code": "80331",
                                "country": "DE",
                            },
                            "contacts": [
                                {
                                    "role": "billing",
                                    "name": "AP Department",
                                    "email": "billing@acme-corp.com",
                                }
                            ],
                        },
                        "account_scope": "operator_brand",
                        "payment_terms": "net_30",
                    },
                },
            ],
            title="Account",
        ),
    ] = None
    action: Annotated[
        Action,
        Field(
            description="Action taken for this creative during this sync operation (lifecycle operation, not approval state).",
            title="Creative Action",
        ),
    ]
    status: Annotated[
        Status34 | None,
        Field(
            description="Advisory review-lifecycle state of the creative after this sync — a UI hint and polling-scheduling signal, NOT a spend-authorization gate. Orthogonal to action — action says what the sync did (created, updated, ...); status says where the creative sits in review. Values come from CreativeStatus only (processing, pending_review, approved, rejected, archived) — never from CreativeAction. Sellers with async review return processing or pending_review; sellers with synchronous review MAY return a terminal value (approved, rejected). Buyers MUST NOT gate downstream spend or package activation on status: approved from this response — a compromised or buggy seller could declare approved while bypassing content-policy review. Reconcile via list_creatives or a signed review webhook before committing spend. Authoritative state is always via list_creatives. MUST be omitted when action is failed or deleted (the creative has no meaningful review state — failure details belong in the errors array; deleted creatives are gone from the library). Omit entirely when the seller has no review lifecycle at all.",
            title="Creative Status",
        ),
    ] = None
    platform_id: Annotated[
        str | None, Field(description="Platform-specific ID assigned to the creative")
    ] = None
    changes: Annotated[
        list[str] | None,
        Field(description="Field names that were modified (only present when action='updated')"),
    ] = None
    errors: Annotated[
        list[Error] | None,
        Field(description="Validation or processing errors (only present when action='failed')"),
    ] = None
    warnings: Annotated[
        list[str] | None, Field(description="Non-fatal warnings about this creative")
    ] = None
    preview_url: Annotated[
        AnyUrl | None,
        Field(
            description="Preview URL for generative creatives (only present for generative formats)"
        ),
    ] = None
    expires_at: Annotated[
        AwareDatetime | None,
        Field(
            description="ISO 8601 timestamp when preview link expires (only present when preview_url exists)"
        ),
    ] = None
    assigned_to: Annotated[
        list[str] | None,
        Field(
            description="Package IDs this creative was successfully assigned to (only present when assignments were requested)"
        ),
    ] = None
    assignment_errors: Annotated[
        dict[Annotated[str, StringConstraints(pattern=r"^[a-zA-Z0-9_-]+$")], str] | None,
        Field(
            description="Assignment errors by package ID (only present when assignment failures occurred)"
        ),
    ] = None


class SyncCreativesResponse4(AdCPBaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    dry_run: Annotated[
        bool | None, Field(description="Whether this was a dry run (no actual changes made)")
    ] = None
    creatives: Annotated[
        list[Creative],
        Field(
            description="Results for each creative processed. Items with action='failed' indicate per-item validation/processing failures, not operation-level failures."
        ),
    ]
    sandbox: Annotated[
        bool | None,
        Field(description="When true, this response contains simulated data from sandbox mode."),
    ] = None
    context: Annotated[
        dict[str, Any] | None,
        Field(
            description="Opaque correlation data that is echoed unchanged in responses. Used for internal tracking, UI session IDs, trace IDs, and other caller-specific identifiers that don't affect protocol behavior. Context data is never parsed by AdCP agents - it's simply preserved and returned.",
            title="Context Object",
        ),
    ] = None
    ext: Annotated[
        dict[str, Any] | None,
        Field(
            description="Extension object for platform-specific, vendor-namespaced parameters. Extensions are always optional and must be namespaced under a vendor/platform key (e.g., ext.gam, ext.roku). Used for custom capabilities, partner-specific configuration, and features being proposed for standardization.",
            title="Extension Object",
        ),
    ] = None


class Error35(Error):
    pass


class SyncCreativesResponse5(AdCPBaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    errors: Annotated[
        list[Error35],
        Field(
            description="Operation-level errors that prevented processing any creatives (e.g., authentication failure, service unavailable, invalid request format)",
            min_length=1,
        ),
    ]
    context: Annotated[
        dict[str, Any] | None,
        Field(
            description="Opaque correlation data that is echoed unchanged in responses. Used for internal tracking, UI session IDs, trace IDs, and other caller-specific identifiers that don't affect protocol behavior. Context data is never parsed by AdCP agents - it's simply preserved and returned.",
            title="Context Object",
        ),
    ] = None
    ext: Annotated[
        dict[str, Any] | None,
        Field(
            description="Extension object for platform-specific, vendor-namespaced parameters. Extensions are always optional and must be namespaced under a vendor/platform key (e.g., ext.gam, ext.roku). Used for custom capabilities, partner-specific configuration, and features being proposed for standardization.",
            title="Extension Object",
        ),
    ] = None


class Error36(Error):
    pass


class SyncCreativesResponse6(AdCPBaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    status: Annotated[
        Literal["submitted"],
        Field(
            description="Task-level status literal. Discriminates this async envelope from the synchronous success shape, whose creatives array carries per-item approval state via CreativeStatus. See task-status.json for the full task-status enum."
        ),
    ] = "submitted"
    task_id: Annotated[
        str,
        Field(
            description="Task handle the buyer uses with tasks/get, and that the seller references on push-notification callbacks. The creatives array is issued on the completion artifact, not here. Per AdCP wire conventions this is snake_case; A2A adapters MAY surface it as taskId, but the payload field emitted by the agent is task_id."
        ),
    ]
    message: Annotated[
        str | None,
        Field(
            description="Optional human-readable explanation of why the task is submitted — e.g., 'Batch ingestion queued; typical turnaround 15-30 minutes.' Plain text only. Buyers MUST treat this as untrusted seller input: escape before rendering to HTML UIs, and sanitize or isolate before passing to an LLM prompt context — a hostile seller may inject prompt-injection payloads aimed at the buyer's agent.",
            max_length=2000,
        ),
    ] = None
    errors: Annotated[
        list[Error36] | None,
        Field(
            description="Optional advisory errors accompanying the submitted envelope. Use only for non-blocking warnings (e.g., throttled_severity advisories, governance observations). Terminal failures belong in the error branch, not here."
        ),
    ] = None
    context: Annotated[
        dict[str, Any] | None,
        Field(
            description="Opaque correlation data that is echoed unchanged in responses. Used for internal tracking, UI session IDs, trace IDs, and other caller-specific identifiers that don't affect protocol behavior. Context data is never parsed by AdCP agents - it's simply preserved and returned.",
            title="Context Object",
        ),
    ] = None
    ext: Annotated[
        dict[str, Any] | None,
        Field(
            description="Extension object for platform-specific, vendor-namespaced parameters. Extensions are always optional and must be namespaced under a vendor/platform key (e.g., ext.gam, ext.roku). Used for custom capabilities, partner-specific configuration, and features being proposed for standardization.",
            title="Extension Object",
        ),
    ] = None


SyncCreativesResponse = SyncCreativesResponse4 | SyncCreativesResponse5 | SyncCreativesResponse6
