# generated by datamodel-codegen:
#   filename:  brand/get_brand_identity_response.json
#   timestamp:  preserved-by-post-generate-fixes

from __future__ import annotations

from typing import Annotated, Any, Literal, TypeAlias

from pydantic import AnyUrl, ConfigDict, Field, StringConstraints

from ..core.version_envelope import AdcpVersionEnvelope
from ..core import context as context_1
from ..core import error as error_1
from ..core import ext as ext_1
from ..enums import asset_content_type as asset_content_type_1
from ..enums import right_use as right_use_1


class House(AdcpVersionEnvelope):
    model_config = ConfigDict(extra='allow')
    domain: str
    name: str


class Logo(AdcpVersionEnvelope):
    model_config = ConfigDict(extra='allow')
    url: AnyUrl
    orientation: Literal['square', 'horizontal', 'vertical', 'stacked'] | None = None
    background: Literal['dark-bg', 'light-bg', 'transparent-bg'] | None = None
    variant: Literal['primary', 'secondary', 'icon', 'wordmark', 'full-lockup'] | None = None
    tags: list[str] | None = None
    usage: str | None = None
    width: int | None = None
    height: int | None = None


class Colors(AdcpVersionEnvelope):
    model_config = ConfigDict(extra='allow')
    primary: Annotated[str, StringConstraints(pattern='^#[0-9A-Fa-f]{6}$')] | Annotated[list[Annotated[str, StringConstraints(pattern='^#[0-9A-Fa-f]{6}$')]], Field(min_length=1)] | None = None
    secondary: Annotated[str, StringConstraints(pattern='^#[0-9A-Fa-f]{6}$')] | Annotated[list[Annotated[str, StringConstraints(pattern='^#[0-9A-Fa-f]{6}$')]], Field(min_length=1)] | None = None
    accent: Annotated[str, StringConstraints(pattern='^#[0-9A-Fa-f]{6}$')] | Annotated[list[Annotated[str, StringConstraints(pattern='^#[0-9A-Fa-f]{6}$')]], Field(min_length=1)] | None = None
    background: Annotated[str, StringConstraints(pattern='^#[0-9A-Fa-f]{6}$')] | Annotated[list[Annotated[str, StringConstraints(pattern='^#[0-9A-Fa-f]{6}$')]], Field(min_length=1)] | None = None
    text: Annotated[str, StringConstraints(pattern='^#[0-9A-Fa-f]{6}$')] | Annotated[list[Annotated[str, StringConstraints(pattern='^#[0-9A-Fa-f]{6}$')]], Field(min_length=1)] | None = None


class File(AdcpVersionEnvelope):
    model_config = ConfigDict(extra='allow')
    url: Annotated[str, StringConstraints(pattern='^https://')]
    weight: Annotated[int, Field(ge=100, le=900)] | None = None
    weight_range: Annotated[list[Annotated[int, Field(ge=100, le=900)]], Field(min_length=2, max_length=2)] | None = None
    style: Literal['normal', 'italic', 'oblique'] | None = None


class FontRole2(AdcpVersionEnvelope):
    model_config = ConfigDict(extra='allow')
    family: str
    files: Annotated[list[File], Field(max_length=36)] | None = None
    opentype_features: Annotated[list[Annotated[str, StringConstraints(pattern='^[a-z0-9]{4}$')]], Field(max_length=20)] | None = None
    fallbacks: Annotated[list[Annotated[str, StringConstraints(max_length=100)]], Field(max_length=10)] | None = None


class Fonts(AdcpVersionEnvelope):
    model_config = ConfigDict(extra='allow')
    primary: str | FontRole2 | None = None
    secondary: str | FontRole2 | None = None


class Tone(AdcpVersionEnvelope):
    model_config = ConfigDict(extra='allow')
    voice: str | None = None
    attributes: list[str] | None = None
    dos: list[str] | None = None
    donts: list[str] | None = None


class VoiceSynthesis(AdcpVersionEnvelope):
    model_config = ConfigDict(extra='allow')
    provider: str | None = None
    voice_id: str | None = None
    rights_offering_id: str | None = None
    settings: dict[str, Any] | None = None


class Asset(AdcpVersionEnvelope):
    model_config = ConfigDict(extra='allow')
    asset_id: str
    asset_type: asset_content_type_1.AssetContentType
    url: AnyUrl
    tags: list[str] | None = None
    name: str | None = None
    description: str | None = None
    width: int | None = None
    height: int | None = None
    duration_seconds: float | None = None
    file_size_bytes: int | None = None
    format: str | None = None


class Rights(AdcpVersionEnvelope):
    model_config = ConfigDict(extra='allow')
    available_uses: list[right_use_1.RightUse] | None = None
    countries: list[Annotated[str, StringConstraints(pattern='^[A-Z]{2}$')]] | None = None
    excluded_countries: list[Annotated[str, StringConstraints(pattern='^[A-Z]{2}$')]] | None = None
    exclusivity_model: str | None = None
    content_restrictions: list[str] | None = None


class GetBrandIdentityResponse1(AdcpVersionEnvelope):
    model_config = ConfigDict(extra='allow')
    brand_id: str
    house: House
    names: list[dict[str, str]]
    description: str | None = None
    industries: Annotated[list[str], Field(min_length=1)] | None = None
    keller_type: Literal['master', 'sub_brand', 'endorsed', 'independent'] | None = None
    logos: list[Logo] | None = None
    colors: Colors | None = None
    fonts: Fonts | None = None
    visual_guidelines: dict[str, Any] | None = None
    tone: Tone | None = None
    tagline: str | Annotated[list[dict[str, Annotated[str, StringConstraints(min_length=1)]]], Field(min_length=1)] | None = None
    voice_synthesis: VoiceSynthesis | None = None
    assets: list[Asset] | None = None
    rights: Rights | None = None
    available_fields: list[Literal['description', 'industries', 'keller_type', 'logos', 'colors', 'fonts', 'visual_guidelines', 'tone', 'tagline', 'voice_synthesis', 'assets', 'rights']] | None = None
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None


class GetBrandIdentityResponse2(AdcpVersionEnvelope):
    model_config = ConfigDict(extra='allow')
    errors: Annotated[list[error_1.Error], Field(min_length=1)]
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None


GetBrandIdentityResponse: TypeAlias = GetBrandIdentityResponse1 | GetBrandIdentityResponse2


__all__ = [
    'GetBrandIdentityResponse',
    'GetBrandIdentityResponse1',
    'GetBrandIdentityResponse2',
    'Asset',
    'Colors',
    'File',
    'FontRole2',
    'Fonts',
    'House',
    'Logo',
    'Rights',
    'Tone',
    'VoiceSynthesis',
]
