# generated by datamodel-codegen:
#   filename:  brand/update_rights_response.json
#   timestamp:  preserved-by-post-generate-fixes

from __future__ import annotations

from typing import Annotated, TypeAlias

from pydantic import AwareDatetime, ConfigDict, Field

from ..core.version_envelope import AdcpVersionEnvelope
from . import rights_terms as rights_terms_1
from ..core import context as context_1
from ..core import error as error_1
from ..core import ext as ext_1
from ..core import generation_credential as generation_credential_1
from ..core import rights_constraint as rights_constraint_1


class UpdateRightsResponse1(AdcpVersionEnvelope):
    model_config = ConfigDict(extra='allow')
    rights_id: str
    terms: rights_terms_1.RightsTerms
    generation_credentials: list[generation_credential_1.GenerationCredential] | None = None
    rights_constraint: rights_constraint_1.RightsConstraint | None = None
    paused: bool | None = None
    implementation_date: AwareDatetime | None = None
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None


class UpdateRightsResponse2(AdcpVersionEnvelope):
    model_config = ConfigDict(extra='allow')
    errors: Annotated[list[error_1.Error], Field(min_length=1)]
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None


UpdateRightsResponse: TypeAlias = UpdateRightsResponse1 | UpdateRightsResponse2


__all__ = [
    'UpdateRightsResponse',
    'UpdateRightsResponse1',
    'UpdateRightsResponse2',
]
