# generated by datamodel-codegen:
#   filename:  core/async_response_refs/media_buy/build_creative_async_response_working.json
#   timestamp: 2026-05-29T23:56:01+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field

from ... import context as context_1
from ... import ext as ext_1


class BuildCreativeWorking(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    percentage: Annotated[
        float | None, Field(description='Completion percentage (0-100)', ge=0.0, le=100.0)
    ] = None
    current_step: Annotated[
        str | None,
        Field(
            description="Current step or phase of the operation (e.g., 'generating_assets', 'resolving_macros', 'rendering_preview')"
        ),
    ] = None
    total_steps: Annotated[
        int | None, Field(description='Total number of steps in the operation', ge=1)
    ] = None
    step_number: Annotated[int | None, Field(description='Current step number', ge=1)] = None
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None
